[project]
name = "isdf_gw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cupy-cuda13x>=13.6.0",
    "h5py>=3.14.0",
    "jax[cuda13]>=0.9.0",
    "jaxlib>=0.9.0",
    "matplotlib>=3.10.3",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.20",
    "mkdocstrings>=0.30.1",
    "mkdocstrings-python>=1.18.2",
    "numpy>=2.3.1",
    "scipy>=1.16.0",
    "xmlschema>=4.1.0",
    "xsdata[cli]>=25.7",
]

[project.scripts]
cohsex_isdf = "isdf.gw_isdf.cohsex_isdf:main"
kmeans_isdf = "isdf.isdf_init.kmeans_isdf:main"
bse_isdf = "isdf.bse_isdf.bse_isdf:main"
load_psp = "isdf.psp.load_psp:main"
load_upf = "isdf.psp.load_upf:main"

[tool.uv]
package = true

[tool.uv.workspace]
members = [
    
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pdoc>=15.0.4",
    "pydoc-markdown>=4.8.2",
]
jax = [
    "jax[cuda13]>=0.9.0",
    "jaxlib>=0.9.0",
]
build = [
    "scikit-build-core>=0.11.0",
    "cmake>=4.0.0",
    "ninja>=1.10.0",
    "pybind11>=3.0.0",
    "nanobind>=2.0.0",
]
