"""Tier-1 device-invariance gate: μ-pad-extent invariance at FIXED device count.

Root cause pinned in ``reports/device_invariance_2026-07-08/ROOT_CAUSE.md``
(lorrax_sandbox): ``n_rmu_padded = round_up(n_rmu, world_size)`` changes with
the device count, and several solves used to run on the PADDED μ extent —
so the pad extent (hence the device count) deterministically changed the
answer.  Two manifestations, both fixed by solving at the LOGICAL extent:

* bispinor: the transverse ζ_T pivoted LU (``isdf/core.py:solve_zeta``) —
  pad-shape LU roundoff amplified O(1) in the near-null indefinite modes
  (MoS2 668→672 moved Σ^B tile(2,2) from −0.15 to −117.9 eV);
* charge: the per-q W-solve LU (``w_isdf._get_w_solve_fn``) and the
  single-device dense Cholesky (``isdf/core.py:factor_c_q``), plus the PPM
  mode census / window statistics over the padded mode space
  (``ppm_sigma._prepare_sigma_state``).

This gate runs each e2e fixture TWICE at fixed P — once normally and once
with the test-only ``LORRAX_EXTRA_MU_PAD`` knob forcing extra zero pad rows
(``runtime/padding.py:padded_mu_extent``) — and compares:

* **bispinor** (static COHSEX + Σ^B): output must be **BIT-IDENTICAL**
  (tol 0, modulo the run-timestamp header).  The pad value 4 pins the
  historically catastrophic transverse extent 668→672.
* **gnppm** (dynamic GN-PPM Σ_C): the mode census, minimax node counts,
  invalid count, unfulfilled fraction, and the Σ_X column must be **exactly
  equal**; Σ_C / Σ_XC / eqp are gated at ≤ 2e-4 eV.  Bit-identity is NOT
  achievable for the dynamic path: the in-memory arrays keep the padded μ
  extent, so XLA fusion tiling regroups partial sums per extent (measured
  1–2 ULP on ζ/V at P=1), and the near-singular GN-PPM fit ratio
  (Ω² ∝ Wc/(Wc0−Wcp), denominators at the 1e-14 validity threshold)
  amplifies that to a measured 6.3e-5 eV on Σ_C (2.2e-5 eV off-pole).
  Removing it entirely would require never padding μ in any kernel —
  a Fix-3-class robustness/architecture item, not a pad-extent defect.
  Any REAL pad defect (O(1) or discrete) trips the exact-equality gates
  or the 2e-4 eV bound immediately.

The gate is sharp only on a SINGLE device (the multi-device distributed
Cholesky factorises at the padded extent by construction — block-cyclic
layouts need mesh divisibility — with a measured ≤1e-7 rel wobble), so the
subprocess is pinned to one GPU via CUDA_VISIBLE_DEVICES.

Cross-P invariance (different device counts, ~1e-7 reduction-order floor)
is Tier 2 — a multi-GPU script, not part of this suite: see
``tests/multi_device/``.
"""

import re
import shutil
import sys
from pathlib import Path

import numpy as np
import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

# Reuse the e2e subprocess runner + GPU gating from the regression harness
# (tests/ is a package; put its dir on sys.path for a bare sibling import
# under any pytest import mode — same pattern as test_sigma_ppm_gates).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from test_gw_jax_regression import (          # noqa: E402
    _REG,
    _gpu_available,
    _parse_eqp_rows,
    _requested_platform,
    _run_gw_jax,
)

# (case_id, fixture dir, input file, sigma output file, sigma labels,
#  extra pad, sigma_c_tol_ev [None = full bit-identity])
_PAD_CASES = [
    ("gnppm_pad12", _REG / "gnppm_debug", "gnppm_test.in",
     "sigma_diag_gnppm_test.dat", ("sigX", "sigC", "sigXC"), 12, 2.0e-4),
    ("bispinor_pad4", _REG / "bispinor_debug", "bispinor_test.in",
     "sigma_diag_bispinor_test.dat", ("sigSX", "sigCOH", "sigTOT"), 4, None),
]


def _normalize(text: str) -> str:
    """Drop the run-timestamp header ('# Generated by LORRAX ... at ...');
    every numeric byte still participates in the identity check."""
    return "\n".join(
        ln for ln in text.splitlines()
        if not ln.startswith("# Generated by LORRAX")
    )


def _census_lines(log_text: str) -> tuple:
    """PPM census + adaptive-window signature from run.log — the integer
    quantities Fix 2 makes pad-invariant (exact-equality gate)."""
    windows = tuple(re.findall(
        r'window "(\w+)" \((?:crossing|Laplace)\): (\d+) nodes', log_text))
    m = re.search(r"GN invalid modes: (\d+)/(\d+)", log_text)
    u = re.search(r"unfulfilled=([\d.]+)%", log_text)
    return (windows,
            m.groups() if m else None,
            u.group(1) if u else None)


def _run_case(tmp_path, case_dir, input_name, output_name, extra_mu_pad):
    """Copy the fixture, run gw.gw_jax on ONE GPU with the given extra pad;
    return (output texts dict, census signature, stdout)."""
    tag = f"pad{extra_mu_pad}"
    run_dir = tmp_path / f"{case_dir.name}_{tag}"
    shutil.copytree(
        case_dir,
        run_dir,
        ignore=shutil.ignore_patterns(
            "tmp", output_name,
            "eqp_test.dat", "eqp0_test.dat", "eqp1_test.dat",
            "sigma_diag.dat", "eqp0.dat", "eqp1.dat",
        ),
    )
    # NOTE: no CUDA_VISIBLE_DEVICES override — inherit the harness's device
    # pinning (the standard suite invocation is LORRAX_NGPU=1, one visible
    # GPU).  Forcing device "0" breaks under launchers that pin the step to
    # a different physical GPU.  The gate's exactness statement assumes a
    # single device — see module docstring.
    extra_env = {
        "LORRAX_EXTRA_MU_PAD": str(int(extra_mu_pad)),
    }
    result = _run_gw_jax(run_dir, input_name, _requested_platform(),
                         extra_env=extra_env)
    if result.returncode != 0:
        pytest.fail(
            f"{case_dir.name} [{tag}] run failed.\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    out = run_dir / output_name
    assert out.exists(), f"no sigma output written: {out}"
    texts = {output_name: _normalize(out.read_text())}
    for eqp in ("eqp0.dat", "eqp1.dat", "eqp0_test.dat", "eqp1_test.dat"):
        p = run_dir / eqp
        if p.exists():
            texts[eqp] = _normalize(p.read_text())
    return texts, _census_lines(result.stdout), run_dir


def _rows(text: str, labels, tmp_path, tag) -> np.ndarray:
    """_parse_eqp_rows wants a path; give it one."""
    p = tmp_path / f"_cmp_{tag}.dat"
    p.write_text(text)
    return _parse_eqp_rows(p, labels)


@pytest.mark.regression
@pytest.mark.parametrize(
    "case_id,case_dir,input_name,output_name,labels,extra_pad,sigc_tol",
    _PAD_CASES,
    ids=[c[0] for c in _PAD_CASES],
)
def test_mu_pad_extent_invariance(
    tmp_path, case_id, case_dir, input_name, output_name, labels,
    extra_pad, sigc_tol,
):
    """EXTRA_MU_PAD=0 vs =N at fixed P=1: bit-identical (bispinor) /
    exact census + Σ_X with a 2e-4 eV Σ_C bound (gnppm)."""
    platform = _requested_platform()
    if platform in {"gpu", "cuda"} and not _gpu_available():
        pytest.skip("CUDA GPU not available.")
    assert (case_dir / input_name).exists(), f"missing fixture {case_dir}"

    base, census_b, _ = _run_case(
        tmp_path, case_dir, input_name, output_name, 0)
    padded, census_p, _ = _run_case(
        tmp_path, case_dir, input_name, output_name, extra_pad)

    assert set(base) == set(padded), (
        f"{case_id}: output-file sets differ: {sorted(base)} vs {sorted(padded)}"
    )
    # Census / node counts / invalid count / unfulfilled: exactly equal
    # always (integers + printed fractions; Fix 2 acceptance).
    assert census_b == census_p, (
        f"{case_id}: PPM census/window signature changed under a pad-extent "
        f"flip at fixed P — a census/stat still reads the pad extent.\n"
        f"pad0:  {census_b}\npad{extra_pad}: {census_p}"
    )

    if sigc_tol is None:
        # Full bit-identity (static COHSEX chain).
        mismatches = [n for n in sorted(base) if base[n] != padded[n]]
        assert not mismatches, (
            f"{case_id}: pad-extent flip changed {mismatches} at FIXED P — "
            f"a computation still runs on the padded μ extent."
        )
        return

    # Dynamic GN-PPM chain: Σ_X exact; Σ_C/Σ_XC/eqp bounded (see module
    # docstring for why bit-identity is out of reach here).
    a = _rows(base[output_name], labels, tmp_path, "a")
    b = _rows(padded[output_name], labels, tmp_path, "b")
    assert a.shape == b.shape, f"{case_id}: sigma row-count changed"
    # columns: kpt, band, sigX, sigC, sigXC, VH_re, VH_im
    np.testing.assert_array_equal(
        a[:, 2], b[:, 2],
        err_msg=f"{case_id}: Σ_X changed under the pad flip — the "
                f"ζ/V_q/exchange chain reads the pad extent.")
    d = np.max(np.abs(a[:, 3:6] - b[:, 3:6]))
    assert d <= sigc_tol, (
        f"{case_id}: Σ_C/Σ_XC moved {d:.3e} eV > {sigc_tol:g} eV under the "
        f"pad flip (measured residual through the near-singular PPM fit is "
        f"6.3e-5 eV; anything above the bound is a new pad defect)."
    )
    for eqp in ("eqp0.dat", "eqp1.dat"):
        if eqp not in base:
            continue
        def _eqp_col(text):
            # data rows are "ik n Edft Eqp"; k-point header rows are 4
            # floats (kx ky kz w) — distinguished by '.' in field 0.
            vals = []
            for ln in text.splitlines():
                s = ln.split()
                if len(s) == 4 and not ln.startswith('#') and '.' not in s[0]:
                    vals.append(float(s[3]))
            return np.array(vals)

        ea, eb = _eqp_col(base[eqp]), _eqp_col(padded[eqp])
        assert ea.shape == eb.shape, f"{case_id}: {eqp} row count changed"
        de = float(np.max(np.abs(ea - eb))) if ea.size else 0.0
        assert de <= sigc_tol, (
            f"{case_id}: {eqp} moved {de:.3e} eV > {sigc_tol:g} eV under "
            f"the pad flip."
        )
