"""The fill and the wrap must agree — asserted structurally, not measured.

Companion to ``tests/test_minibz_sampler_lattice_classes.py``.  That module
measures that the mini-BZ estimator is unbiased on cells where the
2026-04-05 defect bit; this one asserts the defect's CLASS directly, so a
reintroduction refuses instead of silently biasing a table.

THE CLASS: *the cloud was generated from one set of basis vectors and folded
against another*.  ``randvals @ bvec.T`` fills the parallelepiped spanned by
the COLUMNS of ``bvec``; :func:`gw.vcoul.wrap_points_to_voronoi` folds
against ``shifts @ bvec``, the lattice generated by its ROWS.  Nothing in
either expression knows about the other, which is why four months of decks
went past it.

The guard lives in :mod:`gw.coulomb.sampler` and runs on the FILL PATH — at
import (:func:`_selftest_fill_wrap_guard`, so it is never vacuous) and on
every draw (:func:`_fill_and_wrap`).  It is a convention check: a 3x3
inverse and a comparison, no sampling, no physical tolerance.  These tests
assert that it exists, that it fires, that it does not fire on the shipped
spelling, and — the part with teeth — that no fill site in the tree can skip
it.
"""
import ast
import inspect
import pathlib

import numpy as np
import pytest

from gw.coulomb import sampler as S

# Triclinic on purpose.  On a symmetric basis `U @ bvec.T` and `U @ bvec`
# are the SAME DRAW bitwise, so a guard test built on a cubic cell would
# pass for the wrong reason — the same blindness that hid the bug.
BVEC_TRI = np.array([[1.00, 0.00, 0.00],
                     [0.31, 0.95, 0.00],
                     [0.17, 0.23, 0.87]], dtype=np.float64)


def test_the_guard_ran_at_import_and_is_not_vacuous():
    """Importing the sampler executes the self-test; re-running it is cheap.

    A guard that never fires is indistinguishable from no guard.  The module
    proves at import that its own predicate rejects ``bvec.T`` on a triclinic
    basis; if that ever stops being true, import fails rather than the next
    production table quietly drifting.
    """
    assert hasattr(S, "_selftest_fill_wrap_guard")
    S._selftest_fill_wrap_guard()          # raises AssertionError if vacuous


def test_the_shipped_spelling_passes():
    S.assert_fill_matches_wrap(BVEC_TRI, BVEC_TRI)
    got = S._fill_and_wrap(np.zeros((4, 3)), BVEC_TRI, 1)
    assert got.shape == (4, 3)


def test_the_deleted_spelling_refuses():
    """`randvals @ bvec.T` cannot be drawn any more; it raises."""
    with pytest.raises(S.MiniBZBasisMismatch) as e:
        S.assert_fill_matches_wrap(BVEC_TRI.T, BVEC_TRI)
    assert "NOT a fundamental domain" in str(e.value)

    def bad_fill(X):
        return np.asarray(X, dtype=np.float64) @ BVEC_TRI.T

    with pytest.raises(S.MiniBZBasisMismatch):
        S._fill_and_wrap(np.zeros((4, 3)), BVEC_TRI, 1, fill_fn=bad_fill)


def test_probe_reads_the_spelling_as_written_not_the_comment():
    """`probe_fill_basis` recovers the basis an EXPRESSION actually uses.

    The three spellings in the tree — ``U @ bvec``, ``(bvec.T @ U.T).T`` and
    the deleted ``U @ bvec.T`` — differ by one transpose in a place no
    reviewer looks.  Probing with the identity tells them apart without
    trusting any comment.
    """
    assert np.allclose(S.probe_fill_basis(lambda X: X @ BVEC_TRI), BVEC_TRI)
    assert np.allclose(S.probe_fill_basis(lambda X: (BVEC_TRI.T @ X.T).T),
                       BVEC_TRI)
    assert np.allclose(S.probe_fill_basis(lambda X: X @ BVEC_TRI.T),
                       BVEC_TRI.T)


def test_a_different_fundamental_domain_is_named_as_such():
    """The predicate that actually governs bias is UNIMODULARITY of
    ``M = fill @ inv(wrap)``, not "signed row permutation".

    A unimodular ``M`` means the fill parallelepiped is *a* fundamental
    domain of the wrap lattice, so the fold is measure-preserving and the
    estimator is unbiased even though the convention differs.  MEASURED
    (Frontera job 7890705, see the sibling module): on the ``2pi inv(A).T``
    fcc cell ``M`` is integer unimodular but NOT a row permutation, and the
    deleted spelling deviates 5.0e-03 there — at the MC self-noise.  The
    guard still refuses, but the message has to say which class it is in, or
    the next reader re-derives this from scratch.
    """
    M = np.array([[0.0, 0.0, 1.0],
                  [1.0, 1.0, 1.0],
                  [-1.0, 0.0, 0.0]], dtype=np.float64)
    assert abs(abs(np.linalg.det(M)) - 1.0) < 1e-12
    with pytest.raises(S.MiniBZBasisMismatch) as e:
        S.assert_fill_matches_wrap(M @ BVEC_TRI, BVEC_TRI)
    assert "DIFFERENT fundamental domain" in str(e.value)


# ---------------------------------------------------------------------------
# The teeth: a NEW fill site cannot skip the guard.
# ---------------------------------------------------------------------------
_WRAPPERS = {"wrap_points_to_voronoi", "_wrap"}
_GUARDS = {"assert_fill_matches_wrap", "_fill_and_wrap"}

_SOURCES = [
    "gw/coulomb/sampler.py",
    "gw/coulomb/base.py",
    "bse/vq_interp.py",
]


def _src_root():
    import gw
    return pathlib.Path(inspect.getfile(gw)).resolve().parent.parent


def _called_names(node):
    out = set()
    for n in ast.walk(node):
        if isinstance(n, ast.Call):
            f = n.func
            if isinstance(f, ast.Name):
                out.add(f.id)
            elif isinstance(f, ast.Attribute):
                out.add(f.attr)
    return out


@pytest.mark.parametrize("relpath", _SOURCES)
def test_every_function_that_folds_also_asserts_the_basis(relpath):
    """Every function that Voronoi-folds must also assert fill == wrap.

    This is the regression guard for the guard.  Adding a fourth mini-BZ
    sampler with its own inline ``U @ bvec.T`` is exactly how the 2026-04-05
    defect arrived (three independent implementations, one wrong); this test
    makes that edit fail at collection time instead of at the next
    re-derivation of a production table.

    ``gw.coulomb.sampler._fill_and_wrap`` is itself a fold site and is
    allowed — it IS the guard.
    """
    path = _src_root() / relpath
    tree = ast.parse(path.read_text(), filename=str(path))
    offenders = []
    for fn in ast.walk(tree):
        if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        called = _called_names(fn)
        if not (called & _WRAPPERS):
            continue
        if fn.name in ("_wrap", "_fill_and_wrap"):
            continue                      # the guard's own plumbing
        if not (called & _GUARDS):
            offenders.append(fn.name)
    assert not offenders, (
        f"{relpath}: {offenders} fold points into a Voronoi cell without "
        f"asserting that the cloud was FILLED from the same basis.  Route "
        f"the fill through gw.coulomb.sampler._fill_and_wrap, or probe the "
        f"fill expression and call assert_fill_matches_wrap on it.  See "
        f"tests/test_minibz_sampler_lattice_classes.py for what happens "
        f"when the two disagree.")


def test_the_teeth_test_has_something_to_bite():
    """Guard against the previous test passing because it found nothing.

    If a refactor renames the wrap helper, `_WRAPPERS` stops matching and
    the parametrized test above goes vacuously green.  Count the fold sites
    it actually inspected.
    """
    seen = 0
    for relpath in _SOURCES:
        tree = ast.parse((_src_root() / relpath).read_text())
        for fn in ast.walk(tree):
            if isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)) and (
                    _called_names(fn) & _WRAPPERS):
                seen += 1
    assert seen >= 4, (
        f"only {seen} Voronoi-fold sites found across {_SOURCES} — the wrap "
        f"helper was probably renamed and the convention test above is now "
        f"vacuous")
