"""``minimax`` — certified quadrature rules, served by lookup, with provenance.

Everything LORRAX knows about minimax quadrature for the GW frequency
integrals: the shipped table catalog and the rule that selects from it, the
provenance record every served rule carries, the refusals that name every
gap, and — behind an announced escape hatch — the offline solvers that
generated the tables in the first place.  Numbers in, numbers out: no
decks, no bands, no HDF5, no jax.

THE PACKAGE IS THE DOOR.  Everything a consumer needs is a top-level name
here; importing ``minimax.<submodule>`` from lorrax is a layering violation
the monorepo's ``tests/test_layering.py`` fails on.

WHY THIS SERVICE IS DIFFERENT FROM THE FIVE BEFORE IT
-----------------------------------------------------
The other extractions moved code.  This one changes a contract, because
the thing being extracted was measurably not keeping the one it had.  The
survey re-solved one of the module's own shipped tables, with the module's
own function, on the module's own arguments, and got a different answer:
four more nodes and a conditioning number nine hundred times worse.  Not a
different answer in the tenth digit — a different mathematical object.  We
had already written down that Frontera and Perlmutter disagreed about this
in a frozen test, with a note that nobody had determined which was right.
It is not an oddity of two clusters.  It is what that solver does above a
bandwidth of about twenty-four, everywhere, and the third data point came
from a laptop.

Nobody noticed because six places in the lookup path caught every possible
exception and returned "not found".  A missing catalog file, an unreadable
table, a malformed entry — all of them meant the same thing to the caller:
no table, so solve it yourself, quietly, for a few minutes, on whatever
numerical libraries this machine happens to have.  And the line the run
printed when it finished said ``err<1e-06``, which is the accuracy that
was *requested*, not the accuracy that was *achieved*.

So the promise changes shape.  Instead of "here is a rule accurate to your
target", this service says "here is table number so-and-so, whose contents
hash to this value, generated by that commit on that backend, measured to
achieve this error with this amplification".  That is a promise it can
keep on any machine, because it is a promise about an artifact rather than
about a computation — the same settlement the phase already reached for
centroid sets.  When it does not have a table for what you asked, it says
so by name, and names both levers: how to move the physics into the
catalog, and what command would extend the catalog to cover you.

WHO CALLS WHAT
--------------
``serve(family=…, target=…, range_value=…, error_bound=…, n_max=…)``
    THE production entry point.  Looks up; on a miss, takes the R1 stage-1
    escape hatch (announced, uncertified) or refuses.
    ``gw.minimax_screening``'s three ``solve_*`` wrappers are thin
    rescalers over it — they turn the scaled ``[1, R]`` / ``[0, A]`` table
    into Rydberg windows, which is why the extraction is bit-identical by
    construction rather than by tolerance.
``lookup(...)``
    Lookup and ONLY lookup.  Never solves; refuses F1–F4 by name.
``nearest_certified(...)``
    What a refusal offers.  Pure catalog algebra; never raises.
``catalog()`` → :class:`CatalogView`
    Enumerable, assertable, no solve.  What the certification tier (WP6)
    and the request census read.
``TARGETS`` / ``FAMILIES``
    The vocabulary as declarative data, importable without loading a
    catalog or solving anything.  ``FAMILIES`` is R4's 2×2 written down:
    a sampling frequency's real and imaginary parts are each zero or not,
    and each combination needs a different family.  Three cells have code;
    the fourth is where MPA lives.
``family_for_character(character)``
    That 2×2's dispatch, with F6 for the empty cell.
``Quadrature`` / ``Provenance``
    What comes back.  ``Provenance.one_line()`` is what the driver logs.
``G_hgl``, ``noncrossing_grids``, ``crossing_grids``, …
    The OFFLINE solvers, on the door but imported LAZILY (PEP 562): they
    are the only thing here that needs scipy, and a production lookup must
    not pay for it.  A generator campaign touches these; a run does not.

Dependencies: numpy.  ``import minimax`` touches no jax, no scipy and no
lorrax — measured, not asserted, in
``services/minimax/tests/test_minimax_import_isolation.py``.
"""

from __future__ import annotations

from minimax._catalog import (
    CatalogEntry,
    catalog_view,
    clear_caches,
    load_catalog_dict,
    load_table,
    nearest_below,
    parse_catalog,
    parse_entry,
    provenance_for,
    select_entry,
)
#: The ``complex_laplace`` family's selection rule, as a NAMED MODULE and
#: not as a handful of names on the door.  It is on the public surface —
#: ``from minimax import beta_selector`` — because it is one family's rule
#: and it carries its own small vocabulary: two clause constants, a
#: selection record and a refusal record, each of which would collide with
#: or blur a generic name here (``select`` beside ``select_entry``,
#: ``load_catalog`` beside ``load_catalog_dict``, a second
#: ``reset_announcements``).  A module is the honest shape for that, and
#: it is not the door rule's "consumer reaches a submodule" violation:
#: this IS the door for that family, and ``lookup(family=
#: 'complex_laplace', ...)`` routes through it.  Importing it costs numpy
#: and json, which the door already spends.
#:
#: ``damped_line_selector`` is here for the same reason and ``family_axes``
#: because it is the DECLARATION both of them read -- which axis of which
#: family rounds which way, in one place, so two doors cannot drift apart
#: on it.  ``damped_line_selector`` has no production consumer yet (the fit
#: stage still runs two sweeps where the catalog exists so it can run one);
#: it is on the surface anyway, because a door nobody can reach is how a
#: shipped catalog quietly becomes unreachable bytes.
from minimax import beta_selector, damped_line_selector, family_axes
from minimax.door import (
    RUNTIME_SOLVE_ENV,
    catalog,
    family_for_character,
    lookup,
    nearest_certified,
    reset_announcements,
    runtime_solve_allowed,
    serve,
    solve_uncertified,
)
from minimax.records import (
    SOURCES,
    CatalogView,
    Provenance,
    Quadrature,
    runtime_provenance,
)
from minimax.refusals import (
    AmplificationCap,
    CatalogCorrupt,
    CatalogUnavailable,
    MinimaxRefusal,
    NoCertifiedTable,
    SamplingUnsupported,
    TableUnreadable,
    UncertifiedSolveRefused,
    UnknownTarget,
)
from minimax.targets import (
    CHARACTERS,
    FAMILIES,
    TARGETS,
    FamilySpec,
    TargetSpec,
    families_for_character,
)

#: The offline solver half, reached lazily.  These are the names
#: ``common.minimax`` published before the extraction, and they are on the
#: door — not behind ``minimax.solver`` — because they have real external
#: consumers (the generator tool, the certification tier, the imag-table
#: cells), and a consumer reaching a submodule is the door rule's first
#: violation.  There is no compat shim at the old path: ``common.minimax``
#: had exactly one production importer, it was repointed here in the same
#: commit, and the phase's shim ratchet
#: (``tests/test_service_path_bootstrap.py``) pins the old path gone.
#:
#: Lazy because :mod:`minimax.solver` is the service's ONLY scipy consumer.
#: Serving a certified table must not import an optimiser, and this is how
#: that stays true while keeping the names on the door.
#:
#: SEVERAL OF THESE HAVE NO CALLER, AND THAT IS ON PURPOSE FOR NOW.  The
#: Remez solver, the binary-search crossing builder, the two error models
#: and the three rescalers are 469 of ``solver.py``'s 1059 lines and
#: nothing in the tree calls them; the deletion manifest is written up in
#: ``~/lorrax_service_phase/DELETION_MANIFEST_minimax.md`` and is waiting
#: on the owner's sign-off.  Until that arrives the extraction must not
#: SHRINK the surface it moved — a move and a deletion in one commit is
#: two changes wearing one diff — so every name ``common.minimax``
#: published is published here.  Sign-off deletes the code and these rows
#: together, in one commit that is about deletion and nothing else.
_SOLVER_NAMES = (
    # target functions
    "G_hgl", "G_fermi", "tau_max_hgl", "tau_max_fermi",
    # the three grid drivers production reached for
    "noncrossing_grids", "noncrossing_imag_grids", "crossing_grids",
    # the solvers under them
    "solve_noncrossing", "solve_noncrossing_imag", "solve_crossing",
    "evaluate_noncrossing", "evaluate_noncrossing_imag", "evaluate_crossing",
    # error models + the binary-search crossing builder
    "predict_N_noncrossing", "error_estimate_noncrossing",
    "predict_N_crossing", "build_crossing_quadrature",
    # the rescalers
    "rescale_noncrossing", "rescale_crossing", "rescale_noncrossing_imag",
    # Underscore-private BY HISTORY and on the door anyway, for the same
    # reason `vcoul._minibz_kernel_bare` is: it has a real cross-package
    # consumer.  `tests/test_minimax_imag_tables.py` asserts that the
    # shipped complex_laplace payload's `alpha.real` fits THIS function --
    # R4's "the imaginary-axis family and the complex-Laplace family are one
    # campaign" claim, discharged against the production target rather than
    # against a restatement of it.  A consumer reaching `minimax.solver` for
    # it would be the door rule's first violation.
    "_imag_target",
)

# Pure offline fitting routines.  They use SciPy, so keep them behind the
# same lazy door as the historical solvers: a production table lookup must
# not import an optimiser.
_FREQUENCY_FIT_NAMES = (
    "DampedReciprocalFit", "fit_damped_reciprocal",
)

# Delivered-error fitting on a weighted complex support.  Also SciPy
# (linprog), so it lives behind the same lazy door: a production table
# lookup must not import an optimiser.
_RECIPROCAL_FIT_NAMES = (
    "ReciprocalMeasureProblem", "ComplexTimeRule",
    "evaluate_rule", "delivered_error", "rule_amplification",
    "solve_fixed_time_weights",
    "solve_fixed_time_weights_fast",
)
_TIME_NODE_SEARCH_NAMES = (
    "ComplexTimeSearchOptions", "support_arc",
    "candidate_time_dictionary", "fit_reciprocal_measure",
)


def __getattr__(name: str):
    """PEP 562 lazy door for the solver half.

    ``from minimax import noncrossing_grids`` imports scipy at that
    moment and not before.  ``import minimax`` never does.
    """
    if name in _SOLVER_NAMES:
        from minimax import solver as _solver          # noqa: PLC0415
        return getattr(_solver, name)
    if name in _FREQUENCY_FIT_NAMES:
        from minimax import frequency_fit as _fit      # noqa: PLC0415
        return getattr(_fit, name)
    if name in _RECIPROCAL_FIT_NAMES:
        from minimax import reciprocal_fit as _measure  # noqa: PLC0415
        return getattr(_measure, name)
    if name in _TIME_NODE_SEARCH_NAMES:
        from minimax import time_node_search as _search  # noqa: PLC0415
        return getattr(_search, name)
    raise AttributeError(f"module 'minimax' has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(_SOLVER_NAMES)
                  | set(_FREQUENCY_FIT_NAMES)
                  | set(_RECIPROCAL_FIT_NAMES)
                  | set(_TIME_NODE_SEARCH_NAMES))


__all__ = [
    # --- the vocabulary, as data -------------------------------------------
    "TARGETS", "FAMILIES", "CHARACTERS", "TargetSpec", "FamilySpec",
    "families_for_character", "family_for_character",
    # --- what you get back -------------------------------------------------
    "Quadrature", "Provenance", "CatalogView", "SOURCES",
    "runtime_provenance",
    # --- lookup, and only lookup -------------------------------------------
    "beta_selector", "damped_line_selector", "family_axes",
    "lookup", "nearest_certified", "catalog", "serve", "solve_uncertified",
    "runtime_solve_allowed", "RUNTIME_SOLVE_ENV", "reset_announcements",
    # --- the catalog algebra, for the certification tier and the census ----
    "CatalogEntry", "catalog_view", "load_catalog_dict", "parse_catalog",
    "parse_entry", "select_entry", "nearest_below", "clear_caches",
    "load_table", "provenance_for",
    # --- the refusals ------------------------------------------------------
    "MinimaxRefusal", "NoCertifiedTable", "AmplificationCap", "UnknownTarget",
    "CatalogUnavailable", "TableUnreadable", "CatalogCorrupt",
    "UncertifiedSolveRefused", "SamplingUnsupported",
    # --- generic complex-frequency fitting (lazy; scipy) -------------------
    *_FREQUENCY_FIT_NAMES,
    # --- delivered-error fitting on a weighted support (lazy; scipy) -------
    *_RECIPROCAL_FIT_NAMES,
    *_TIME_NODE_SEARCH_NAMES,
    # --- the offline solvers (lazy; scipy) ---------------------------------
    *_SOLVER_NAMES,
]
