"""BerkeleyGW ``eqp0.dat`` / ``eqp1.dat`` writer for LORRAX gw_jax outputs.

Reproduces the exact text format BerkeleyGW emits at
``Sigma/sigma_main.f90:3174-3193`` so the BSE / band-structure interface
files from a LORRAX gw_jax run are byte-identical (modulo numerics) to
a reference BGW Sigma run.

Physics
-------
We never materialize ``V_xc`` itself — the standard rearrangement

    E_DFT(k,n) = K + I + V_H + V_xc       (mean-field eigenvalue)
    E_GW(k,n,ω) = K + I + V_H + Σ_xc(ω)

means

    Δ(k,n,ω) ≡ E_GW(ω) - E_DFT
            = (K + I + V_H + Σ_xc(ω)) - E_DFT
            = kin_ion[k,n,n] + V_H[k,n,n] + Σ_xc[k,n,n](ω) - E_DFT[k,n]

reads directly off LORRAX outputs without ever forming ``V_xc``.  The
diagonal QP energies BGW writes are the standard Newton iteration on
the on-shell Σ:

    eqp0[k,n] = E_DFT[k,n] + Δ(k,n, E_DFT[k,n])               (zeroth order)
    eqp1[k,n] = E_DFT[k,n] + Z[k,n] · Δ(k,n, E_DFT[k,n])      (linearized)
    Z[k,n]   = 1 / (1 - dRe[Σ_c]/dω | ω = E_DFT[k,n])

Σ_x and V_H are ω-independent, so only Σ_c contributes to Z.

Inputs (per LORRAX gw_jax run directory)
----------------------------------------
- ``WFN.h5``                 — IBZ wedge k-points + DFT energies in Ry
- ``kin_ion.h5``             — K+I matrix elements in Ry (nk_full, nb, nb)
- ``sigma_mnk.h5``           — Σ_x, Σ_c(ω), V_H matrix elements in eV; ω in eV
                               relative to the DFT mid-gap Fermi level
- ``qp_wfn_rotations.h5``    — band_range + kirr_to_kfull mapping

Output format (BGW ``Sigma/sigma_main.f90:3175-3193``)
-----------------------------------------------------
A single provenance comment line is prepended:

    # Generated by LORRAX <version> at <UTC ISO timestamp>

then per IBZ k-point one block:

    header  ``(3f13.9, i8)``       kx_frac ky_frac kz_frac (nspin·nb)
    body    ``(2i8, 2f15.9)``      ispin iband_abs E_DFT_eV E_QP_eV

Everything past the comment line is byte-identical to BGW's own
``eqp.dat``.  The LORRAX reader (:func:`bse.bse_io.read_bgw_eqp`)
transparently skips leading ``#`` lines; for downstream BGW binaries
(BSE/Inteqp) that don't, strip the comment with ``tail -n +2``.

CLI
---
    python -m gw.eqp_bgw <run_dir>
"""

from __future__ import annotations

import argparse
import os
from typing import Optional

import h5py
import numpy as np

from common.units import RYD_TO_EV
from common.provenance import provenance_header


# ---------------------------------------------------------------------------
# Pure formatter (matches BGW sigma_main.f90 byte-for-byte)
# ---------------------------------------------------------------------------

def write_bgw_eqp(
	path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	e_qp_ev: np.ndarray,
	*,
	band_offset: int,
	nspin: int = 1,
) -> str:
	"""Write a BerkeleyGW ``eqp{0,1}.dat`` file.

	Parameters
	----------
	path
	    Output file path.
	kpoints_irr_frac : (nk, 3)
	    IBZ-wedge k-points in fractional crystal coordinates.
	e_dft_ev, e_qp_ev : (nk, nb)
	    DFT and quasiparticle eigenvalues in eV, indexed over the
	    sigma-window bands.
	band_offset
	    0-based absolute band index of the first sigma-window band; the
	    BGW file uses 1-based labels ``band_offset + 1 .. band_offset + nb``.
	nspin
	    Number of spin channels (LORRAX runs at nspin=1).
	"""
	kpts = np.asarray(kpoints_irr_frac, dtype=np.float64)
	e_dft = np.asarray(e_dft_ev, dtype=np.float64)
	e_qp = np.asarray(e_qp_ev, dtype=np.float64)
	nk, nb = e_dft.shape
	if kpts.shape != (nk, 3):
		raise ValueError(f"kpoints shape {kpts.shape} does not match e_dft {(nk, 3)}")
	if e_qp.shape != (nk, nb):
		raise ValueError(f"e_qp shape {e_qp.shape} does not match e_dft {(nk, nb)}")

	# ── Writer gate (pre-write) ──────────────────────────────────────
	# The NaN-producing distributed back-solve of 2026-07 reached disk
	# with rc=0 and was caught only because somebody afterwards counted
	# the floats in eqp0.dat: ``%15.9f`` renders a NaN as the token
	# ``nan``, so the *count of parseable floats* drops while the line
	# count does not.  That check is made structural here — the writer
	# refuses to pretend a NaN-bearing array is a result, and re-reads
	# what it wrote to confirm the file it produced parses to exactly the
	# expected number of finite floats.
	from common import sanity
	sanity.check_finite(f"{os.path.basename(path)} E_DFT column", e_dft)
	sanity.check_finite(f"{os.path.basename(path)} E_QP column", e_qp)

	abs_path = os.path.abspath(path)
	if os.path.dirname(abs_path):
		os.makedirs(os.path.dirname(abs_path), exist_ok=True)

	with open(abs_path, "w") as fh:
		fh.write(provenance_header())
		for ik in range(nk):
			kx, ky, kz = (float(kpts[ik, j]) for j in range(3))
			# Fortran (3f13.9, i8)
			fh.write(f"{kx:13.9f}{ky:13.9f}{kz:13.9f}{nspin * nb:8d}\n")
			for ispin in range(1, nspin + 1):
				for ib in range(nb):
					iband = band_offset + ib + 1  # 1-based BGW absolute band
					# Fortran (2i8, 2f15.9) — BGW format consumes only 4 args
					# even though the spec advertises 3f15.9; sigma_main.f90 passes
					# (ispin, iband, E_DFT, E_QP).
					fh.write(
						f"{ispin:8d}{iband:8d}"
						f"{float(e_dft[ik, ib]):15.9f}{float(e_qp[ik, ib]):15.9f}\n"
					)
	verify_eqp_file(abs_path, nk=nk, nb=nb, nspin=nspin)
	return abs_path


def verify_eqp_file(
	path: str, *, nk: int, nb: int, nspin: int = 1,
	print_fn=print,
) -> bool:
	"""Re-read a written ``eqp*.dat`` and assert its structural float count.

	The invariant: after the ``#`` provenance line the file holds ``nk``
	k-point headers (3 floats + 1 int) and ``nk·nspin·nb`` body rows
	(2 ints + 2 floats).  So a healthy file parses to exactly

	    n_float = nk·3 + nk·nspin·nb·2

	*finite* floats.  ``float("nan")`` parses fine, so the count alone is
	not enough — non-finite tokens are counted separately and reported.
	This is the check that caught the NaN-producing back-solve after the
	fact; running it inside the writer turns "somebody noticed later" into
	"the run said so at the time".

	Returns True when the file is structurally sound.  Cost is one pass
	over a few-thousand-line text file, i.e. nothing.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return True
	expect_rows = int(nk) * int(nspin) * int(nb)
	expect_floats = int(nk) * 3 + expect_rows * 2
	n_float = 0
	n_nonfinite = 0
	n_header = 0
	n_body = 0
	with open(path, "r") as fh:
		for line in fh:
			if line.startswith("#") or not line.strip():
				continue
			tok = line.split()
			# Header rows are (3f13.9, i8) — the first token is a float and
			# carries a '.'.  Body rows are (2i8, 2f15.9) — the first two
			# tokens are bare integers.  Discriminating on content rather
			# than column width keeps this correct if either format ever
			# widens a field.
			if len(tok) == 4 and "." in tok[0]:
				n_header += 1
				vals = tok[:3]
			elif len(tok) == 4:
				n_body += 1
				vals = tok[2:]
			else:
				n_nonfinite += len(tok)   # malformed → count as suspect
				continue
			for v in vals:
				try:
					x = float(v)
				except ValueError:
					n_nonfinite += 1
					continue
				if np.isfinite(x):
					n_float += 1
				else:
					n_nonfinite += 1
	base = os.path.basename(path)
	ok = sanity.check_count(
		f"{base} finite-float count", n_float, expect_floats,
		print_fn=print_fn,
		detail=(f"{n_header}/{nk} k-headers, {n_body}/{expect_rows} band rows, "
		        f"{n_nonfinite} non-finite/unparseable tokens.  A NaN or Inf "
		        f"in the QP column renders as a token %15.9f cannot round-trip "
		        f"— the file looks complete but its numbers are not."))
	ok = sanity.check_count(f"{base} band rows", n_body, expect_rows,
	                        print_fn=print_fn) and ok
	return ok


# ---------------------------------------------------------------------------
# Numerics: eqp0 / eqp1 from per-state Σ on a global ω-grid
# ---------------------------------------------------------------------------

def compute_z_factor_from_omega_grid(
	*,
	sigma_c_omega_diag_ev: np.ndarray,  # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray,           # (n_omega,)  — ω axis relative to E_F
	e_dft_rel_ev: np.ndarray,           # (nk, nb)    — E_DFT - E_F
	dE_ev: float = 0.5,
) -> tuple[np.ndarray, np.ndarray]:
	"""Interpolate Σ_c at E_DFT and central-difference Z = 1 / (1 − dRe[Σ_c]/dω).

	Returns ``(sigma_c_at_dft_diag_ev, z_factor)``, both shape ``(nk, nb)``.
	``sigma_c_at_dft_diag_ev`` is complex; ``z_factor`` is real.

	``dE_ev`` plays the role of BGW's ``finite_difference_spacing``; 0.5 eV
	matches the BGW default.  For the ω-grid spacing of 0.25 eV used by
	gw_jax this falls cleanly on grid points.
	"""
	nk, nb = e_dft_rel_ev.shape
	if sigma_c_omega_diag_ev.shape != (omega_rel_ev.size, nk, nb):
		raise ValueError(
			f"sigma_c_omega shape {sigma_c_omega_diag_ev.shape} mismatched against "
			f"({omega_rel_ev.size}, {nk}, {nb})"
		)

	from .qsgw_utils import interp_along_omega
	sigma_c_at_dft = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev)
	sigma_c_plus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev + dE_ev)
	sigma_c_minus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev - dE_ev)

	# Central-difference dRe[Σ_c]/dω at E_DFT
	dsigma_dE = (np.real(sigma_c_plus) - np.real(sigma_c_minus)) / (2.0 * dE_ev)
	z_factor = 1.0 / (1.0 - dsigma_dE)
	return sigma_c_at_dft, z_factor


def _implied_vxc_window_ev() -> tuple[float, float]:
	"""The physical window for ``V_xc = E_DFT − (kin_ion + V_H)``, in eV.

	Single-sources the bounds from ``gw.gw_output`` when that module
	exposes them, so the writer-side gate and the driver-side
	``_warn_on_unphysical_h0`` can never drift apart.  The literals below
	are the same numbers, kept as a fallback so this module stays
	importable on its own (the post-hoc ``python -m gw.eqp_bgw`` CLI does
	not otherwise need the driver).
	"""
	try:
		from . import gw_output as _gwo
		return (float(getattr(_gwo, "_VXC_IMPLIED_MIN_EV", -50.0)),
		        float(getattr(_gwo, "_VXC_IMPLIED_MAX_EV", 2.0)))
	except ImportError:
		return (-50.0, 2.0)


def _warn_on_unphysical_implied_vxc(
	*, e_dft_ev, kin_ion_diag_ev, hartree_diag_ev,
) -> None:
	"""Gate the mean-field side of eqp{0,1} on the DFT eigenvalue identity.

	``E_DFT = ⟨T+V_ion+V_NL⟩ + ⟨V_H⟩ + ⟨V_xc⟩`` is exact, so a correct run
	must reproduce a physical ``V_xc = E_DFT − (kin_ion + V_H)``
	band-by-band.  That is the invariant this checks.

	Why not check the QP shift itself.  The first version of this gate
	bracketed ``Δ = eqp0 − E_DFT`` at ±50 eV, reasoning that GW moves
	states by a few eV.  That is **wrong for deep states**: Δ = Σ_xc −
	V_xc, and semicore bands carry bare-exchange Σ_x of order −100 eV
	against an equally large V_xc, so a perfectly healthy run legitimately
	shows |Δ| ≫ 50 eV.  It fired on 72 of 120 states of the cohsex_debug
	fixture — a run that simultaneously reproduced its reference eqp to
	1e-6 eV.  The implied-V_xc form has no such sensitivity: the large,
	legitimate Σ_xc cancels out of it entirely, because Σ never enters.

	This is deliberately the same invariant, and the same window, as
	``gw_output._warn_on_unphysical_h0``.  That one guards the live driver
	path; this one additionally covers the post-hoc ``make_eqp_bgw`` CLI,
	which rebuilds eqp{0,1} from ``kin_ion.h5`` + ``sigma_mnk.h5`` on disk
	— exactly the stale-artifact scenario — and had no guard at all.  It
	is warn-only and prints nothing on a healthy run, so it adds no noise
	where the driver already reports.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return
	implied_vxc = (np.asarray(e_dft_ev, dtype=np.float64)
	               - (np.asarray(kin_ion_diag_ev, dtype=np.float64)
	                  + np.real(np.asarray(hartree_diag_ev))))
	lo, hi = _implied_vxc_window_ev()
	sanity.check_in_range(
		"implied Vxc = E_DFT − (kin_ion + V_H)", implied_vxc, lo, hi,
		unit="eV")


def compute_eqp_diag(
	*,
	kin_ion_diag_ev: np.ndarray,        # (nk, nb)
	hartree_diag_ev: np.ndarray,        # (nk, nb)
	sigma_x_diag_ev: np.ndarray,        # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray, # (nk, nb)  — on-shell Σ_c
	e_dft_ev: np.ndarray,               # (nk, nb)
	z_factor: np.ndarray | None = None, # (nk, nb)  — None ⇒ Z=1 (static modes)
) -> tuple[np.ndarray, np.ndarray]:
	"""Return zeroth-order and Z-linearized BGW QP energies.

	Computes::

	    Δ(k,n)  = (kin_ion + V_H + Σ_x + Σ_c(E_DFT) − E_DFT).real
	    eqp0    = E_DFT + Δ                          (zeroth-order Newton)
	    eqp1    = E_DFT + Z · Δ                      (linearized; Z=1 if None)

	For static modes (COHSEX) the on-shell Σ_c is just the static value and
	there is no ω-grid to differentiate, so callers pass ``z_factor=None``
	and ``eqp1 == eqp0`` trivially — matching BGW's behavior in static runs.

	For dynamic modes (GN-PPM, HL-PPM) the caller obtains both
	``sigma_c_at_dft_diag_ev`` and ``z_factor`` from
	:func:`compute_z_factor_from_omega_grid`.
	"""
	sigma_xc_at_dft = sigma_x_diag_ev + sigma_c_at_dft_diag_ev
	delta_at_dft = (
		kin_ion_diag_ev + hartree_diag_ev + sigma_xc_at_dft - e_dft_ev
	).real

	# NOTE: the mean-field (implied-V_xc) gate deliberately does NOT live
	# here.  ``compute_eqp_diag`` is shared by the live driver path, and
	# there ``gw_output.write_results`` already runs
	# ``_warn_on_unphysical_h0`` on these very arrays immediately before
	# calling the writer — checking again would emit two identical
	# complaints about one problem.  The gate is attached to
	# :func:`make_eqp_bgw` instead, which is the path that has no guard.
	eqp0 = e_dft_ev + delta_at_dft
	if z_factor is None:
		eqp1 = eqp0  # Z=1 trivially
	else:
		eqp1 = e_dft_ev + z_factor * delta_at_dft
	return eqp0, eqp1


def write_eqp_bgw_pair(
	*,
	eqp0_path: str,
	eqp1_path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	eqp0_ev: np.ndarray,
	eqp1_ev: np.ndarray,
	band_offset: int,
	nspin: int = 1,
) -> tuple[str, str]:
	"""Write the BGW-format eqp0.dat + eqp1.dat pair from precomputed arrays.

	Both files share the same provenance header, k-point list, and
	``E_DFT`` column; only the ``E_QP`` column differs (zeroth-order
	vs. Z-linearized).
	"""
	write_bgw_eqp(eqp0_path, kpoints_irr_frac, e_dft_ev, eqp0_ev,
	              band_offset=band_offset, nspin=nspin)
	write_bgw_eqp(eqp1_path, kpoints_irr_frac, e_dft_ev, eqp1_ev,
	              band_offset=band_offset, nspin=nspin)
	return eqp0_path, eqp1_path


# ---------------------------------------------------------------------------
# In-memory entry point — used by the standard ``gw_output.write_results``
# path during a live gw_jax run (avoids re-reading sigma_mnk.h5 from disk).
# ---------------------------------------------------------------------------

def write_eqp_bgw_in_memory(
	*,
	eqp0_path: str,
	eqp1_path: str,
	kpoints_irr_frac: np.ndarray,
	band_offset: int,
	e_dft_ev: np.ndarray,                                  # (nk, nb)
	kin_ion_diag_ev: np.ndarray,                           # (nk, nb)
	hartree_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_x_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray,                    # (nk, nb)
	# Optional: full ω-grid for the Z-factor (PPM modes only).
	# If None ⇒ Z=1 ⇒ eqp1 == eqp0 (BGW behavior in static modes).
	sigma_c_omega_diag_ev: np.ndarray | None = None,       # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray | None = None,                # (n_omega,)
	e_dft_rel_ev: np.ndarray | None = None,                # (nk, nb), required if dynamic
	dE_ev: float = 0.5,
	nspin: int = 1,
) -> tuple[str, str]:
	"""Compute and write BGW-format ``eqp0.dat`` / ``eqp1.dat`` from in-memory arrays.

	Parallel of :func:`make_eqp_bgw` (the post-hoc CLI orchestrator) for the
	live gw_jax write path: the caller already has ``Σ_x``, ``V_H``,
	``kin_ion``, ``E_DFT`` in memory, so reloading them from disk would be
	wasteful.  Both entry points now share :func:`compute_eqp_diag`,
	:func:`compute_z_factor_from_omega_grid`, and :func:`write_eqp_bgw_pair`
	— there is one source of truth for the eqp{0,1} math and BGW formatter.
	"""
	if sigma_c_omega_diag_ev is None:
		# Static mode: no ω-grid, Z = 1 trivially.
		z_factor = None
	else:
		if omega_rel_ev is None or e_dft_rel_ev is None:
			raise ValueError(
				"sigma_c_omega_diag_ev requires omega_rel_ev and e_dft_rel_ev"
			)
		# Re-derive σ_c at E_DFT from the full ω-grid for self-consistency
		# with the Z-factor central difference.
		sigma_c_at_dft_diag_ev, z_factor = compute_z_factor_from_omega_grid(
			sigma_c_omega_diag_ev=sigma_c_omega_diag_ev,
			omega_rel_ev=omega_rel_ev,
			e_dft_rel_ev=e_dft_rel_ev,
			dE_ev=dE_ev,
		)

	eqp0_ev, eqp1_ev = compute_eqp_diag(
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_diag_ev,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft_diag_ev,
		e_dft_ev=e_dft_ev,
		z_factor=z_factor,
	)
	return write_eqp_bgw_pair(
		eqp0_path=eqp0_path, eqp1_path=eqp1_path,
		kpoints_irr_frac=kpoints_irr_frac,
		e_dft_ev=e_dft_ev, eqp0_ev=eqp0_ev, eqp1_ev=eqp1_ev,
		band_offset=band_offset, nspin=nspin,
	)


# ---------------------------------------------------------------------------
# Orchestrator: read the run directory and emit eqp{0,1}.dat
# ---------------------------------------------------------------------------

def make_eqp_bgw(
	run_dir: str,
	*,
	wfn_path: Optional[str] = None,
	kin_ion_path: Optional[str] = None,
	sigma_mnk_path: Optional[str] = None,
	qp_rotations_path: Optional[str] = None,
	eqp0_out: str = "eqp0.dat",
	eqp1_out: str = "eqp1.dat",
	finite_difference_spacing_ev: float = 0.5,
) -> tuple[str, str]:
	"""Emit BGW-format ``eqp0.dat`` and ``eqp1.dat`` from a LORRAX gw_jax run.

	All file paths default to standard names inside ``run_dir``.  Returns
	``(eqp0_path, eqp1_path)``.
	"""
	wfn_path = wfn_path or os.path.join(run_dir, "WFN.h5")
	kin_ion_path = kin_ion_path or os.path.join(run_dir, "kin_ion.h5")
	sigma_mnk_path = sigma_mnk_path or os.path.join(run_dir, "sigma_mnk.h5")
	qp_rotations_path = qp_rotations_path or os.path.join(run_dir, "qp_wfn_rotations.h5")
	eqp0_path = (
		eqp0_out if os.path.isabs(eqp0_out) else os.path.join(run_dir, eqp0_out)
	)
	eqp1_path = (
		eqp1_out if os.path.isabs(eqp1_out) else os.path.join(run_dir, eqp1_out)
	)

	# IBZ k-points + per-state DFT energies (Ry → eV)
	with h5py.File(wfn_path, "r") as wfn:
		kpoints_irr = np.asarray(wfn["mf_header/kpoints/rk"])
		nspin = int(np.asarray(wfn["mf_header/kpoints/nspin"]))
		# energies: (nspin, nk, nbands_total) in Ry
		energies_ry = np.asarray(wfn["mf_header/kpoints/el"])
		ifmax = np.asarray(wfn["mf_header/kpoints/ifmax"])  # (nspin, nk) 1-based
	if nspin != 1:
		raise NotImplementedError("LORRAX runs at nspin=1; got nspin={}".format(nspin))

	nk_irr = kpoints_irr.shape[0]

	# IBZ → full-BZ index map; band_range
	with h5py.File(qp_rotations_path, "r") as qp:
		band_range = np.asarray(qp["band_range"], dtype=np.int64)
		kirr_to_kfull = np.asarray(qp["kirr_to_kfull"], dtype=np.int64)
	band_start, band_stop = int(band_range[0]), int(band_range[1])
	nb_window = band_stop - band_start
	if kirr_to_kfull.size != nk_irr:
		raise ValueError(
			f"kirr_to_kfull size {kirr_to_kfull.size} != IBZ kpts {nk_irr}"
		)

	# DFT energies on the IBZ wedge for the sigma window (eV)
	# energies_ry shape (nspin=1, nk_irr, nb_total); take spin 0.
	e_dft_ev = energies_ry[0, :, band_start:band_stop] * RYD_TO_EV
	if e_dft_ev.shape != (nk_irr, nb_window):
		raise ValueError(
			f"WFN energies shape {energies_ry.shape} inconsistent with "
			f"band_range {(band_start, band_stop)} on {nk_irr} IBZ kpts"
		)

	# Mid-gap Fermi level from the IBZ DFT energies (matches gw_jax convention)
	n_occ = int(np.max(ifmax[0]))                       # 1-based highest occ
	occ_idx_local = n_occ - 1 - band_start              # within the window
	if occ_idx_local < 0 or occ_idx_local + 1 >= nb_window:
		raise ValueError(
			"sigma window does not bracket VBM/CBM: band_range="
			f"[{band_start},{band_stop}), VBM index={n_occ - 1}"
		)
	vbm_ev = float(np.max(e_dft_ev[:, : occ_idx_local + 1]))
	cbm_ev = float(np.min(e_dft_ev[:, occ_idx_local + 1 :]))
	efermi_ev = 0.5 * (vbm_ev + cbm_ev)
	e_dft_rel_ev = e_dft_ev - efermi_ev

	# kin_ion (Ry → eV), pulled on the IBZ wedge directly
	with h5py.File(kin_ion_path, "r") as kih:
		kin_full = np.asarray(kih["kin_ion"])
	if kin_full.ndim != 3:
		raise ValueError(f"kin_ion dataset must be (nk, nb, nb); got {kin_full.shape}")
	kin_irr = kin_full[kirr_to_kfull, band_start:band_stop, band_start:band_stop]
	kin_ion_diag_ev = np.real(np.diagonal(kin_irr, axis1=1, axis2=2)) * RYD_TO_EV

	# sigma_mnk.h5: σ_x, σ_c(ω), V_H, ω axis (all already in eV, ω relative to E_F)
	with h5py.File(sigma_mnk_path, "r") as sf:
		omega_rel_ev = np.asarray(sf["omega_ev"], dtype=np.float64)
		sigma_x_full = np.asarray(sf["sigma_sx_kij_ev"])
		hartree_full = np.asarray(sf["hartree_kij_ev"])
		sigma_c_full = np.asarray(sf["sigma_c_kij_ev"])
	# Subset to IBZ wedge × sigma-window bands
	sigma_x_irr = sigma_x_full[kirr_to_kfull][:, band_start:band_stop, band_start:band_stop]
	hartree_irr = hartree_full[kirr_to_kfull][:, band_start:band_stop, band_start:band_stop]
	sigma_c_irr = sigma_c_full[:, kirr_to_kfull][:, :, band_start:band_stop, band_start:band_stop]

	sigma_x_diag = np.diagonal(sigma_x_irr, axis1=1, axis2=2)
	hartree_diag = np.diagonal(hartree_irr, axis1=1, axis2=2)
	sigma_c_omega_diag = np.diagonal(sigma_c_irr, axis1=2, axis2=3)  # (n_omega, nk, nb)

	# Mean-field gate — this CLI is the unguarded path.  Unlike the live
	# driver (where ``gw_output.write_results`` runs the same check just
	# before writing), ``make_eqp_bgw`` rebuilds eqp{0,1} from whatever
	# ``kin_ion.h5`` / ``sigma_mnk.h5`` happen to be sitting in
	# ``run_dir`` — the stale-artifact scenario, with no guard at all.
	_warn_on_unphysical_implied_vxc(
		e_dft_ev=e_dft_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=np.real(hartree_diag),
	)

	sigma_c_at_dft, z_factor = compute_z_factor_from_omega_grid(
		sigma_c_omega_diag_ev=sigma_c_omega_diag,
		omega_rel_ev=omega_rel_ev,
		e_dft_rel_ev=e_dft_rel_ev,
		dE_ev=finite_difference_spacing_ev,
	)
	eqp0_ev, eqp1_ev = compute_eqp_diag(
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=np.real(hartree_diag),
		sigma_x_diag_ev=np.real(sigma_x_diag),
		sigma_c_at_dft_diag_ev=sigma_c_at_dft,
		e_dft_ev=e_dft_ev,
		z_factor=z_factor,
	)
	return write_eqp_bgw_pair(
		eqp0_path=eqp0_path, eqp1_path=eqp1_path,
		kpoints_irr_frac=kpoints_irr,
		e_dft_ev=e_dft_ev, eqp0_ev=eqp0_ev, eqp1_ev=eqp1_ev,
		band_offset=band_start, nspin=1,
	)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
	p = argparse.ArgumentParser(allow_abbrev=False,
		prog="python -m gw.eqp_bgw",
		description="Reproduce BGW eqp0.dat / eqp1.dat from a LORRAX gw_jax run.",
	)
	p.add_argument("run_dir", help="Run directory containing WFN.h5, kin_ion.h5, sigma_mnk.h5, qp_wfn_rotations.h5")
	p.add_argument("--wfn", default=None, help="Path to WFN.h5 (default: <run_dir>/WFN.h5)")
	p.add_argument("--kin-ion", default=None, help="Path to kin_ion.h5")
	p.add_argument("--sigma-mnk", default=None, help="Path to sigma_mnk.h5")
	p.add_argument("--qp-rotations", default=None, help="Path to qp_wfn_rotations.h5")
	p.add_argument("--eqp0", default="eqp0.dat", help="Output eqp0 filename (relative to run_dir unless absolute)")
	p.add_argument("--eqp1", default="eqp1.dat", help="Output eqp1 filename (relative to run_dir unless absolute)")
	p.add_argument(
		"--finite-difference-spacing",
		type=float, default=0.5,
		help="dE (eV) for the Z-factor central difference (BGW default 0.5)",
	)
	return p


def main(argv: Optional[list[str]] = None) -> int:
	args = _build_parser().parse_args(argv)
	eqp0_path, eqp1_path = make_eqp_bgw(
		args.run_dir,
		wfn_path=args.wfn,
		kin_ion_path=args.kin_ion,
		sigma_mnk_path=args.sigma_mnk,
		qp_rotations_path=args.qp_rotations,
		eqp0_out=args.eqp0,
		eqp1_out=args.eqp1,
		finite_difference_spacing_ev=args.finite_difference_spacing,
	)
	print(f"wrote: {eqp0_path}")
	print(f"wrote: {eqp1_path}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
