"""BerkeleyGW ``eqp0.dat`` / ``eqp1.dat`` writer for LORRAX gw_jax outputs.

Reproduces the exact text format BerkeleyGW emits at
``Sigma/sigma_main.f90:3174-3193`` so the BSE / band-structure interface
files from a LORRAX gw_jax run are byte-identical (modulo numerics) to
a reference BGW Sigma run.

Physics
-------
We never materialize ``V_xc`` itself — the standard rearrangement

    E_DFT(k,n) = K + I + V_H + V_xc       (mean-field eigenvalue)
    E_GW(k,n,ω) = K + I + V_H + Σ_xc(ω)

means

    Δ(k,n,ω) ≡ E_GW(ω) - E_DFT
            = (K + I + V_H + Σ_xc(ω)) - E_DFT
            = kin_ion[k,n,n] + V_H[k,n,n] + Σ_xc[k,n,n](ω) - E_DFT[k,n]

reads directly off LORRAX outputs without ever forming ``V_xc``.  The
diagonal QP energies BGW writes are the standard Newton iteration on
the on-shell Σ:

    eqp0[k,n] = E_DFT[k,n] + Δ(k,n, E_DFT[k,n])               (zeroth order)
    eqp1[k,n] = E_ref[k,n] + Z[k,n] · Δ(k,n, E_ref[k,n])      (linearized)
    Z[k,n]   = 1 / (1 - dRe[Σ_c]/dω | ω = E_ref[k,n])

Σ_x and V_H are ω-independent, so only Σ_c contributes to Z.

``E_ref`` is the spectrum Σ WAS EVALUATED AT, which is E_DFT in a
one-shot G0W0 run — BGW's case, and the case these files are formatted
for — and the converged QP energies under self-consistency, where
linearizing at E_DFT instead would centre the difference eV away from
the pole.  :func:`compute_eqp_diag` owns that choice and documents it;
eqp0 is at E_DFT always.

Inputs (per LORRAX gw_jax run directory)
----------------------------------------
- ``WFN.h5``                 — IBZ wedge k-points + DFT energies in Ry
- ``kin_ion.h5``             — K+I matrix elements in Ry (nk_full, nb, nb).
                               When stamped ``has_hartree=True`` it ALSO
                               contains the exact FFT-grid ⟨V_H⟩, and this
                               CLI then suppresses ``sigma_mnk.h5``'s ISDF
                               Hartree column rather than adding it twice
                               (same contract as ``gw.sigma_dispatch``).
- ``sigma_mnk.h5``           — Σ_x, Σ_c(ω), V_H matrix elements in eV; ω in eV
                               relative to the DFT mid-gap Fermi level
- ``qp_wfn_rotations.h5``    — band_range + kirr_to_kfull mapping

Output format (BGW ``Sigma/sigma_main.f90:3175-3193``)
-----------------------------------------------------
A single provenance comment line is prepended:

    # Generated by LORRAX <version> at <UTC ISO timestamp>

then per IBZ k-point one block:

    header  ``(3f13.9, i8)``       kx_frac ky_frac kz_frac (nspin·nb)
    body    ``(2i8, 2f15.9)``      ispin iband_abs E_DFT_eV E_QP_eV

Everything past the comment line is byte-identical to BGW's own
``eqp.dat``.  The LORRAX reader (:func:`bse.bse_io.read_bgw_eqp`)
transparently skips leading ``#`` lines; for downstream BGW binaries
(BSE/Inteqp) that don't, strip the comment with ``tail -n +2``.

Design — one assembly, one formatter, two ways in
-------------------------------------------------
There are two legitimate ways to want eqp{0,1}: during a live gw_jax run
(the arrays are already in memory) and afterwards from a run directory
(the "rebuild QP energies from artifacts without re-running Σ" workflow,
which proved essential this campaign).  They differ ONLY in how the
arrays are obtained::

        load artifacts              in-memory arrays
              |                            |
    make_eqp_bgw                     gw_output.write_results
              \\                          /
               +---- assemble_eqp() ----+     mean-field gate,
                        |                     Z-factor, Newton update
               EqpAssembly.write()            the BGW formatter

Everything physical happens in :func:`assemble_eqp`; :func:`make_eqp_bgw`
has no independent semantics and consumes only a completed live-driver
receipt, whose Hartree operand is the exact G-space result.

CLI
---
    python -m gw.eqp_bgw <run_dir>
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import Optional

import h5py
import numpy as np

from common.units import RYD_TO_EV
from common.provenance import provenance_header


# ---------------------------------------------------------------------------
# Pure formatter (matches BGW sigma_main.f90 byte-for-byte)
# ---------------------------------------------------------------------------

def write_bgw_eqp(
	path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	e_qp_ev: np.ndarray,
	*,
	band_offset: int,
	nspin: int = 1,
	comments: tuple[str, ...] = (),
) -> str:
	"""Write a BerkeleyGW ``eqp{0,1}.dat`` file.

	Parameters
	----------
	path
	    Output file path.
	kpoints_irr_frac : (nk, 3)
	    IBZ-wedge k-points in fractional crystal coordinates.
	e_dft_ev, e_qp_ev : (nk, nb)
	    DFT and quasiparticle eigenvalues in eV, indexed over the
	    sigma-window bands.
	band_offset
	    0-based absolute band index of the first sigma-window band; the
	    BGW file uses 1-based labels ``band_offset + 1 .. band_offset + nb``.
	nspin
	    Number of spin channels (LORRAX runs at nspin=1).
	comments
	    Optional diagnostic lines written after the provenance header.  The
	    formatter supplies the leading ``# `` so the file remains readable by
	    BerkeleyGW-compatible parsers.  The ordinary ``eqp0.dat`` / ``eqp1.dat``
	    path passes none and remains byte-identical to the historical format.
	"""
	kpts = np.asarray(kpoints_irr_frac, dtype=np.float64)
	e_dft = np.asarray(e_dft_ev, dtype=np.float64)
	e_qp = np.asarray(e_qp_ev, dtype=np.float64)
	nk, nb = e_dft.shape
	if kpts.shape != (nk, 3):
		raise ValueError(f"kpoints shape {kpts.shape} does not match e_dft {(nk, 3)}")
	if e_qp.shape != (nk, nb):
		raise ValueError(f"e_qp shape {e_qp.shape} does not match e_dft {(nk, nb)}")

	# ── Writer gate (pre-write) ──────────────────────────────────────
	# The NaN-producing distributed back-solve of 2026-07 reached disk
	# with rc=0 and was caught only because somebody afterwards counted
	# the floats in eqp0.dat: ``%15.9f`` renders a NaN as the token
	# ``nan``, so the *count of parseable floats* drops while the line
	# count does not.  That check is made structural here — the writer
	# refuses to pretend a NaN-bearing array is a result, and re-reads
	# what it wrote to confirm the file it produced parses to exactly the
	# expected number of finite floats.
	# REFUSAL, not a warning.  The 2026-08-15 bcc-Fe run wrote 7176 of 7176
	# E_QP entries as NaN through this very call and exited rc=0; the warning
	# it emitted is the only thing that noticed, and a warning does not reach
	# an exit code (JID 57051742, CLAIMS 204).  A file whose QP column is not
	# a number is not a result, and the reader downstream cannot tell the
	# difference from the line count.  ``LORRAX_ALLOW_NONFINITE_RESULT=1``
	# writes it anyway, for the forensic case, and says so.
	from common import sanity
	sanity.refuse_nonfinite(
		f"{os.path.basename(path)} E_DFT column", e_dft,
		detail="the mean-field spectrum this file reports beside the QP one.")
	sanity.refuse_nonfinite(
		f"{os.path.basename(path)} E_QP column", e_qp,
		detail="%15.9f renders a NaN as the token 'nan', so the file would "
		       "look complete while its numbers were not.")

	abs_path = os.path.abspath(path)
	if os.path.dirname(abs_path):
		os.makedirs(os.path.dirname(abs_path), exist_ok=True)

	with open(abs_path, "w") as fh:
		fh.write(provenance_header())
		for comment in comments:
			line = str(comment)
			if "\n" in line or "\r" in line:
				raise ValueError(
					"write_bgw_eqp comments must each be one line; got "
					f"{line!r}")
			fh.write(f"# {line}\n")
		for ik in range(nk):
			kx, ky, kz = (float(kpts[ik, j]) for j in range(3))
			# Fortran (3f13.9, i8)
			fh.write(f"{kx:13.9f}{ky:13.9f}{kz:13.9f}{nspin * nb:8d}\n")
			for ispin in range(1, nspin + 1):
				for ib in range(nb):
					iband = band_offset + ib + 1  # 1-based BGW absolute band
					# Fortran (2i8, 2f15.9) — BGW format consumes only 4 args
					# even though the spec advertises 3f15.9; sigma_main.f90 passes
					# (ispin, iband, E_DFT, E_QP).
					fh.write(
						f"{ispin:8d}{iband:8d}"
						f"{float(e_dft[ik, ib]):15.9f}{float(e_qp[ik, ib]):15.9f}\n"
					)
	verify_eqp_file(abs_path, nk=nk, nb=nb, nspin=nspin)
	return abs_path


def read_bgw_eqp(eqp_file: str):
	"""Read a BerkeleyGW ``eqp{0,1}.dat`` — the inverse of :func:`write_bgw_eqp`.

	Returns ``(kpts_irr (nk, 3), e_dft (nk, nb), e_qp (nk, nb),
	band_offset)``; the energies are eV and the k-points are the CRYSTAL
	COORDINATES the block headers carry, on the irreducible wedge the
	writer emitted.

	``band_offset`` is the 0-BASED ABSOLUTE index of column 0, recovered
	from the file's own 1-based ``iband`` labels — the inverse of
	:func:`write_bgw_eqp`'s ``band_offset``.  It is returned rather than
	dropped because a consumer slicing an absolute band window
	(``bandstructure.htransform``) cannot place these columns without it,
	and the previous reader discarded it, which is why that consumer grew
	a second eqp parser instead of using this one.

	**Lives beside the writer on purpose.**  It used to sit in
	``bse.bse_window``, which made it reachable only from BSE — so
	``bandstructure.htransform`` grew a second, incompatible eqp parser of
	its own rather than take a ``bandstructure → bse`` edge that exists
	nowhere else in the tree.  One format, one reader, one writer, in one
	module: a change to the layout cannot now update only half of them.

	Ragged band counts are tolerated (short blocks are NaN-padded to the
	widest), because a caller slicing a band window must be able to see
	which states are absent rather than read a zero.
	"""
	kpts: list[list[float]] = []
	e_dft_blocks: list[list[float]] = []
	e_qp_blocks: list[list[float]] = []
	first_band: int | None = None

	with open(eqp_file) as f:
		while True:
			header = f.readline()
			if not header:
				break
			stripped = header.strip()
			if not stripped:
				break
			if stripped.startswith("#"):
				continue
			parts = header.split()
			if len(parts) < 4:
				break
			kpts.append([float(parts[0]), float(parts[1]), float(parts[2])])
			n_bands = int(parts[3])

			e_dft_k, e_qp_k = [], []
			for _ in range(n_bands):
				cols = f.readline().split()
				# (ispin, iband, E_DFT, E_QP); iband is 1-based ABSOLUTE.
				if first_band is None:
					first_band = int(cols[1])
				e_dft_k.append(float(cols[2]))
				e_qp_k.append(float(cols[3]))
			e_dft_blocks.append(e_dft_k)
			e_qp_blocks.append(e_qp_k)

	if not kpts:
		raise ValueError(
			f"no k-point blocks parsed from {os.path.basename(eqp_file)} — "
			f"expected the BerkeleyGW eqp layout this module writes "
			f"(a '(3f13.9,i8)' k header, then that many '(2i8,2f15.9)' rows)")

	max_band = max(len(b) for b in e_dft_blocks)
	n_kpts = len(kpts)
	e_dft = np.full((n_kpts, max_band), np.nan)
	e_qp = np.full((n_kpts, max_band), np.nan)
	for i in range(n_kpts):
		nb = len(e_dft_blocks[i])
		e_dft[i, :nb] = e_dft_blocks[i]
		e_qp[i, :nb] = e_qp_blocks[i]
	return np.array(kpts), e_dft, e_qp, int(first_band) - 1


def verify_eqp_file(
	path: str, *, nk: int, nb: int, nspin: int = 1,
	print_fn=print,
) -> bool:
	"""Re-read a written ``eqp*.dat`` and assert its structural float count.

	The invariant: after the ``#`` provenance line the file holds ``nk``
	k-point headers (3 floats + 1 int) and ``nk·nspin·nb`` body rows
	(2 ints + 2 floats).  So a healthy file parses to exactly

	    n_float = nk·3 + nk·nspin·nb·2

	*finite* floats.  ``float("nan")`` parses fine, so the count alone is
	not enough — non-finite tokens are counted separately and reported.
	This is the check that caught the NaN-producing back-solve after the
	fact; running it inside the writer turns "somebody noticed later" into
	"the run said so at the time".

	Returns True when the file is structurally sound.  Cost is one pass
	over a few-thousand-line text file, i.e. nothing.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return True
	expect_rows = int(nk) * int(nspin) * int(nb)
	expect_floats = int(nk) * 3 + expect_rows * 2
	n_float = 0
	n_nonfinite = 0
	n_header = 0
	n_body = 0
	with open(path, "r") as fh:
		for line in fh:
			if line.startswith("#") or not line.strip():
				continue
			tok = line.split()
			# Header rows are (3f13.9, i8) — the first token is a float and
			# carries a '.'.  Body rows are (2i8, 2f15.9) — the first two
			# tokens are bare integers.  Discriminating on content rather
			# than column width keeps this correct if either format ever
			# widens a field.
			if len(tok) == 4 and "." in tok[0]:
				n_header += 1
				vals = tok[:3]
			elif len(tok) == 4:
				n_body += 1
				vals = tok[2:]
			else:
				n_nonfinite += len(tok)   # malformed → count as suspect
				continue
			for v in vals:
				try:
					x = float(v)
				except ValueError:
					n_nonfinite += 1
					continue
				if np.isfinite(x):
					n_float += 1
				else:
					n_nonfinite += 1
	base = os.path.basename(path)
	ok = sanity.check_count(
		f"{base} finite-float count", n_float, expect_floats,
		print_fn=print_fn,
		detail=(f"{n_header}/{nk} k-headers, {n_body}/{expect_rows} band rows, "
		        f"{n_nonfinite} non-finite/unparseable tokens.  A NaN or Inf "
		        f"in the QP column renders as a token %15.9f cannot round-trip "
		        f"— the file looks complete but its numbers are not."))
	ok = sanity.check_count(f"{base} band rows", n_body, expect_rows,
	                        print_fn=print_fn) and ok
	return ok


# ---------------------------------------------------------------------------
# Numerics: eqp0 / eqp1 from per-state Σ on a global ω-grid
# ---------------------------------------------------------------------------

def compute_z_factor_from_omega_grid(
	*,
	sigma_c_omega_diag_ev: np.ndarray,  # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray,           # (n_omega,)  — ω axis relative to E_F
	e_dft_rel_ev: np.ndarray,           # (nk, nb)    — the CENTRE, E - E_F
	dE_ev: float = 0.5,
) -> tuple[np.ndarray, np.ndarray]:
	"""Interpolate Σ_c at a centre energy and central-difference
	Z = 1 / (1 − dRe[Σ_c]/dω) there.

	Returns ``(sigma_c_at_centre_diag_ev, z_factor)``, both shape
	``(nk, nb)``.  The Σ_c value is complex; ``z_factor`` is real.

	``e_dft_rel_ev`` NAMES THE CENTRE, and the name is the one-shot case,
	not a claim about every caller.  eqp0 always wants E_DFT − E_F here;
	eqp1 wants the energies the Σ spectrum was BUILT at (see
	:func:`assemble_eqp`), which is the same array in a one-shot run and
	the converged QP energies under self-consistency.  Whatever is passed
	must be ω-relative on the SAME reference the ω grid was built with.

	``dE_ev`` plays the role of BGW's ``finite_difference_spacing``; 0.5 eV
	matches the BGW default.  For the ω-grid spacing of 0.25 eV used by
	gw_jax this falls cleanly on grid points.
	"""
	nk, nb = e_dft_rel_ev.shape
	if sigma_c_omega_diag_ev.shape != (omega_rel_ev.size, nk, nb):
		raise ValueError(
			f"sigma_c_omega shape {sigma_c_omega_diag_ev.shape} mismatched against "
			f"({omega_rel_ev.size}, {nk}, {nb})"
		)

	# ``clamp``, named rather than inherited.  The +/- dE_ev probes are
	# DESIGNED to leave the grid at its two outermost samples -- a central
	# difference at the edge has nowhere else to stand -- so a refusal here
	# would fire on every healthy deck.  What the clamp costs is worth
	# stating: where BOTH probes clamp to the same endpoint the numerator
	# is exactly zero, dRe[sigma_c]/domega comes back 0 and Z comes back
	# exactly 1, i.e. eqp1 degenerates to eqp0 for that state.  That is a
	# recognisable signature rather than a plausible wrong number, which is
	# why it is tolerable here and is not at the OUTPUT path
	# (dynamic_sigma.eval_sigma_c_at_dft_energies, which reports its count).
	from .qsgw_utils import interp_along_omega
	sigma_c_at_dft = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev,
		out_of_range="clamp")
	sigma_c_plus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev + dE_ev,
		out_of_range="clamp")
	sigma_c_minus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev - dE_ev,
		out_of_range="clamp")

	# Central-difference dRe[Σ_c]/dω at the centre
	dsigma_dE = (np.real(sigma_c_plus) - np.real(sigma_c_minus)) / (2.0 * dE_ev)
	z_factor = 1.0 / (1.0 - dsigma_dE)
	return sigma_c_at_dft, z_factor


def _implied_vxc_window_ev() -> tuple[float, float]:
	"""The physical window for ``V_xc = E_DFT − (kin_ion + V_H)``, in eV.

	Single-sources the bounds from ``gw.gw_output`` when that module
	exposes them, so the writer-side gate and the driver-side
	``_warn_on_unphysical_h0`` can never drift apart.  The literals below
	are the same numbers, kept as a fallback so this module stays
	importable on its own (the post-hoc ``python -m gw.eqp_bgw`` CLI does
	not otherwise need the driver).
	"""
	try:
		from . import gw_output as _gwo
		return (float(getattr(_gwo, "_VXC_IMPLIED_MIN_EV", -50.0)),
		        float(getattr(_gwo, "_VXC_IMPLIED_MAX_EV", 2.0)))
	except ImportError:
		return (-50.0, 2.0)


def _warn_on_unphysical_implied_vxc(
	*, e_dft_ev, kin_ion_diag_ev, hartree_diag_ev,
) -> None:
	"""Gate the mean-field side of eqp{0,1} on the DFT eigenvalue identity.

	``E_DFT = ⟨T+V_ion+V_NL⟩ + ⟨V_H⟩ + ⟨V_xc⟩`` is exact, so a correct run
	must reproduce a physical ``V_xc = E_DFT − (kin_ion + V_H)``
	band-by-band.  That is the invariant this checks.

	Why not check the QP shift itself.  The first version of this gate
	bracketed ``Δ = eqp0 − E_DFT`` at ±50 eV, reasoning that GW moves
	states by a few eV.  That is **wrong for deep states**: Δ = Σ_xc −
	V_xc, and semicore bands carry bare-exchange Σ_x of order −100 eV
	against an equally large V_xc, so a perfectly healthy run legitimately
	shows |Δ| ≫ 50 eV.  It fired on 72 of 120 states of the cohsex_debug
	fixture — a run that simultaneously reproduced its reference eqp to
	1e-6 eV.  The implied-V_xc form has no such sensitivity: the large,
	legitimate Σ_xc cancels out of it entirely, because Σ never enters.

	This is deliberately the same invariant, and the same window, as
	``gw_output._warn_on_unphysical_h0``.

	**Status:** since AD, :func:`assemble_eqp` runs the live-field
	``_warn_on_unphysical_h0`` for BOTH entry points, so this function is
	no longer on the live path.  It is retained as (a) the fallback the
	assembly uses when ``gw.gw_output`` is not importable (no jax on the
	host — the post-hoc CLI's own environment) and (b) the ``common.sanity``
	spelling of the same bracket, which the pure-python gate suite calls
	directly.  Warn-only; prints nothing on a healthy run.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return
	implied_vxc = (np.asarray(e_dft_ev, dtype=np.float64)
	               - (np.asarray(kin_ion_diag_ev, dtype=np.float64)
	                  + np.real(np.asarray(hartree_diag_ev))))
	lo, hi = _implied_vxc_window_ev()
	sanity.check_in_range(
		"implied Vxc = E_DFT − (kin_ion + V_H)", implied_vxc, lo, hi,
		unit="eV")


def compute_eqp_diag(
	*,
	kin_ion_diag_ev: np.ndarray,        # (nk, nb)
	hartree_diag_ev: np.ndarray,        # (nk, nb)
	sigma_x_diag_ev: np.ndarray,        # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray, # (nk, nb)  — on-shell Σ_c
	e_dft_ev: np.ndarray,               # (nk, nb)
	z_factor: np.ndarray | None = None, # (nk, nb)  — None ⇒ Z=1 (static modes)
	# The eqp1 linearization point, when it is NOT E_DFT (see below).
	# Both or neither; None ⇒ the historical at-DFT linearization.
	sigma_c_at_eval_diag_ev: np.ndarray | None = None,  # (nk, nb)
	e_eval_ev: np.ndarray | None = None,                # (nk, nb)
) -> tuple[np.ndarray, np.ndarray]:
	"""Return zeroth-order and Z-linearized BGW QP energies.

	Computes::

	    Δ(k,n,E) = (kin_ion + V_H + Σ_x + Σ_c(E) − E).real
	    eqp0     = E_DFT + Δ(E_DFT)                  (zeroth-order Newton)
	    eqp1     = E_ref  + Z · Δ(E_ref)             (linearized; Z=1 if None)

	**Where E_ref is, and why it is not always E_DFT.** eqp1 is one Newton
	step on the QP equation ``E = h₀ + ReΣ(E)``, linearized about a
	reference energy; Z = 1/(1 − dΣ/dω) is the derivative AT that same
	reference.  BGW's G0W0 takes E_ref = E_DFT because that is the only
	spectrum a one-shot run has, and this function does the same whenever
	``e_eval_ev is None`` — bit-for-bit the historical expression.  Under
	self-consistency the spectrum Σ was built from is the converged QP
	one, so E_DFT is the wrong place to linearize: the central difference
	then samples Σ(ω) eV away from the pole it is meant to characterise
	(2.4 eV at Γ on the sodium 8×8×8 deck), and the residual Δ it
	multiplies is not small.  Passing the evaluation energies makes the
	step consistent — at convergence Δ(E_qp) ≈ 0 and eqp1 reproduces the
	converged iterate, which is the statement eqp1 is supposed to make.

	eqp0 is UNTOUCHED by this: it stays the at-E_DFT zeroth-order value
	that pairs with the ``E_DFT`` column of the file, in every mode.

	For static modes (COHSEX) the on-shell Σ_c is just the static value and
	there is no ω-grid to differentiate, so callers pass ``z_factor=None``
	and ``eqp1 == eqp0`` trivially — matching BGW's behavior in static runs.

	For dynamic modes (GN-PPM, HL-PPM, MPA) the caller obtains
	``sigma_c_at_dft_diag_ev``, ``sigma_c_at_eval_diag_ev`` and
	``z_factor`` from :func:`compute_z_factor_from_omega_grid`.
	"""
	if (sigma_c_at_eval_diag_ev is None) != (e_eval_ev is None):
		raise ValueError(
			"compute_eqp_diag: sigma_c_at_eval_diag_ev and e_eval_ev are "
			"the two halves of ONE linearization point — pass both or "
			"neither; got "
			f"sigma_c_at_eval={'set' if sigma_c_at_eval_diag_ev is not None else 'None'}, "
			f"e_eval={'set' if e_eval_ev is not None else 'None'}")
	sigma_xc_at_dft = sigma_x_diag_ev + sigma_c_at_dft_diag_ev
	delta_at_dft = (
		kin_ion_diag_ev + hartree_diag_ev + sigma_xc_at_dft - e_dft_ev
	).real

	# NOTE: the mean-field (implied-V_xc) gate deliberately does NOT live
	# here.  ``compute_eqp_diag`` is the pure math kernel, shared by every
	# path including callers that legitimately want no output at all
	# (``gw_output.write_freq_debug``), and a gate here reported one
	# broken H₀ twice in two wordings.  It lives one level up, in
	# :func:`assemble_eqp`, which BOTH entry points go through — so it
	# still fires exactly once on the live driver and on the post-hoc
	# CLI.  Pinned by
	# ``tests/test_sanity_gates.py::test_compute_eqp_diag_does_not_duplicate_the_mean_field_gate``.
	eqp0 = e_dft_ev + delta_at_dft
	if z_factor is None:
		eqp1 = eqp0  # Z=1 trivially
	elif e_eval_ev is None:
		eqp1 = e_dft_ev + z_factor * delta_at_dft
	else:
		delta_at_eval = (
			kin_ion_diag_ev + hartree_diag_ev
			+ sigma_x_diag_ev + sigma_c_at_eval_diag_ev - e_eval_ev
		).real
		eqp1 = e_eval_ev + z_factor * delta_at_eval
	return eqp0, eqp1


# ---------------------------------------------------------------------------
# Hartree reaches this module only as the already-resolved live G-space
# matrix.  Source selection and legacy artifact substitution do not exist.
# THE assembly — H₀ + Σ → eqp0/eqp1.  Both entry points go through this.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EqpAssembly:
	"""Everything the BGW eqp{0,1} formatter needs, and nothing else.

	Produced by :func:`assemble_eqp` — the *only* place the mean-field gate,
	the Z-factor and the Newton update are applied — and
	consumed by :meth:`write`, which is the *only* BGW formatter.  The
	live driver (``gw.gw_output.write_results``) and the post-hoc CLI
	(:func:`make_eqp_bgw`) differ solely in how they obtain the input
	arrays; from this object onward the two paths are the same code.
	"""

	kpoints_irr_frac: np.ndarray
	band_offset: int
	e_dft_ev: np.ndarray
	eqp0_ev: np.ndarray
	eqp1_ev: np.ndarray
	kin_ion_diag_ev: np.ndarray
	hartree_diag_ev: np.ndarray          # total Hdir = V_H + H_T
	hartree_scalar_diag_ev: np.ndarray   # scalar V_H used by DFT diagnostics
	sigma_x_diag_ev: np.ndarray
	sigma_c_at_dft_diag_ev: np.ndarray
	#: The exact output-conditioned diagonal curve used to derive both
	#: ``sigma_c_at_dft_diag_ev`` and ``z_factor``.  The persisted full
	#: operator cube remains raw; this smaller curve is an assembly operand.
	sigma_c_omega_diag_ev: np.ndarray | None
	z_factor: np.ndarray | None
	implied_vxc_ev: np.ndarray | None
	hartree_transverse_diag_ev: np.ndarray | None = None
	nspin: int = 1
	#: Where eqp1 was linearized, when that was not E_DFT (self-consistent
	#: runs).  None on every one-shot path, where it IS E_DFT.
	e_eval_ev: np.ndarray | None = None

	def write(self, *, eqp0_path: str, eqp1_path: str) -> tuple[str, str]:
		"""Emit the exact-BGW-format eqp0.dat / eqp1.dat pair."""
		return write_eqp_bgw_pair(
			eqp0_path=eqp0_path, eqp1_path=eqp1_path,
			kpoints_irr_frac=self.kpoints_irr_frac,
			e_dft_ev=self.e_dft_ev,
			eqp0_ev=self.eqp0_ev, eqp1_ev=self.eqp1_ev,
			band_offset=self.band_offset, nspin=self.nspin,
		)


def assemble_eqp(
	*,
	kpoints_irr_frac: np.ndarray,
	band_offset: int,
	e_dft_ev: np.ndarray,                                  # (nk, nb)
	kin_ion_diag_ev: np.ndarray,                           # (nk, nb)
	hartree_diag_ev: np.ndarray,                           # (nk, nb) pre-seam
	sigma_x_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray | None = None,      # (nk, nb)
	# Optional: full ω-grid for the Z-factor (PPM modes only).
	# If None ⇒ Z=1 ⇒ eqp1 == eqp0 (BGW behaviour in static modes).
	sigma_c_omega_diag_ev: np.ndarray | None = None,       # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray | None = None,                # (n_omega,)
	e_dft_rel_ev: np.ndarray | None = None,                # (nk, nb)
	# The eqp1 linearization point — see step 3 below.  Absolute eV and
	# ω-relative eV of the SAME energies; both or neither.
	e_eval_ev: np.ndarray | None = None,                   # (nk, nb)
	e_eval_rel_ev: np.ndarray | None = None,               # (nk, nb)
	dE_ev: float = 0.5,
	nspin: int = 1,
	hartree_scalar_diag_ev: np.ndarray | None = None,
	hartree_transverse_diag_ev: np.ndarray | None = None,
	mean_field_gate: bool = True,
	print_fn=print,
) -> EqpAssembly:
	"""Assemble BGW QP energies from H₀ and Σ.  **One implementation.**

	Order of operations, and each step happens exactly once:

	1. validate the live G-space direct-field components;
	2. the mean-field gate on H₀
	   (``gw.gw_output._warn_on_unphysical_h0`` — the live-field
	   implied-V_xc check; warn-only, never raises);
	3. for a dynamic run, derive both Σ_c(E_DFT) and Z from the SAME
	   output-conditioned diagonal C(omega) curve; for a static run, consume
	   the supplied Σ_c diagonal.  When the
	   caller says the Σ spectrum was evaluated somewhere else
	   (``e_eval_ev``), a SECOND interpolation and central-difference
	   Z there, which is where eqp1 is linearized
	   (:func:`compute_z_factor_from_omega_grid`, and
	   :func:`compute_eqp_diag` for why);
	4. the Newton update (:func:`compute_eqp_diag`).

	**The evaluation point, and the one-omega-reference rule.**
	``e_eval_ev`` / ``e_eval_rel_ev`` are the same energies in absolute
	and ω-relative eV, and the caller forms the relative one with the SAME
	reference it formed ``e_dft_rel_ev`` with — the reference the Σ(ω)
	grid was built with, never a second opinion about it.  Passing them
	equal to the DFT arrays is not merely allowed but the one-shot case,
	and the code then takes the single-interpolation path and reproduces
	the historical numbers bit-for-bit.

	The gate lives HERE rather than in ``compute_eqp_diag`` (which must
	stay a silent pure function — pinned by
	``tests/test_sanity_gates.py::test_compute_eqp_diag_does_not_duplicate_the_mean_field_gate``)
	and no longer at the two call sites, so a single broken H₀ reports
	itself exactly once, in one wording, on both entry points.
	"""
	hartree_used = np.real(np.asarray(hartree_diag_ev, dtype=np.float64))
	if hartree_scalar_diag_ev is None:
		if hartree_transverse_diag_ev is not None:
			raise ValueError(
				"assemble_eqp: H_T was supplied without its scalar V_H twin; "
				"component-aware direct fields require scalar, transverse, and "
				"their aggregate together.")
		hartree_scalar_used = np.asarray(hartree_used, dtype=np.float64)
		hartree_transverse_used = None
	else:
		hartree_scalar_used = np.asarray(
			hartree_scalar_diag_ev, dtype=np.float64)
		hartree_transverse_used = (
			None if hartree_transverse_diag_ev is None else np.asarray(
				hartree_transverse_diag_ev, dtype=np.float64))
		expected_total = hartree_scalar_used
		if hartree_transverse_used is not None:
			expected_total = hartree_scalar_used + hartree_transverse_used
		if not np.array_equal(
			np.asarray(hartree_used, dtype=np.float64), expected_total):
			raise ValueError(
				"assemble_eqp: direct-field aggregate is not exactly "
				"V_H_scalar + H_transverse; refusing an unauthenticated Hdir.")

	implied_vxc = None
	if mean_field_gate:
		implied_vxc = _warn_on_unphysical_h0(
			e_dft_ev=e_dft_ev,
			kin_ion_diag_ev=kin_ion_diag_ev,
			hartree_diag_ev=hartree_scalar_used,
			print_fn=print_fn,
		)
		# No second check here on purpose.  ``_warn_on_unphysical_h0``
		# emits its failure through ``common.sanity.warn``, so the
		# ``*** LORRAX SANITY FAILURE`` grep token and the strict-mode
		# raise both come from that ONE call — for the live driver and
		# for the post-hoc CLI alike.  O's policy kept, its duplicate
		# wording dropped.

	if (e_eval_ev is None) != (e_eval_rel_ev is None):
		raise ValueError(
			"assemble_eqp: e_eval_ev and e_eval_rel_ev are the absolute and "
			"ω-relative halves of ONE linearization point — pass both or "
			"neither")
	sigma_c_at_eval = None
	if sigma_c_omega_diag_ev is None:
		# Static mode: no ω-grid, Z = 1 trivially.
		if sigma_c_at_dft_diag_ev is None:
			raise ValueError(
				"assemble_eqp needs either sigma_c_at_dft_diag_ev (static "
				"modes) or sigma_c_omega_diag_ev + omega_rel_ev + "
				"e_dft_rel_ev (dynamic modes)")
		z_factor = None
		sigma_c_at_dft = sigma_c_at_dft_diag_ev
		# No derivative to centre; eqp1 == eqp0 whatever was passed.
		e_eval_ev = None
	else:
		if omega_rel_ev is None or e_dft_rel_ev is None:
			raise ValueError(
				"sigma_c_omega_diag_ev requires omega_rel_ev and e_dft_rel_ev")
		if sigma_c_at_dft_diag_ev is not None:
			raise ValueError(
				"dynamic assemble_eqp derives both C(E_DFT) and Z from its one "
				"sigma_c_omega_diag_ev curve; a second C(E_DFT) operand would "
				"duplicate the correlation producer.")
		sigma_c_at_dft, z_factor = compute_z_factor_from_omega_grid(
			sigma_c_omega_diag_ev=sigma_c_omega_diag_ev,
			omega_rel_ev=omega_rel_ev,
			e_dft_rel_ev=e_dft_rel_ev,
			dE_ev=dE_ev,
		)
		# THE SECOND CENTRE, and only when it is a different one.  The
		# equality test is what keeps every one-shot run — where the Σ
		# spectrum IS evaluated at E_DFT, so the caller passes the same
		# numbers — on the single-centre code above.  It is an
		# ``array_equal``, not a tolerance:
		# these arrays are either literally the same energies or a
		# different spectrum.
		if e_eval_rel_ev is not None and not np.array_equal(
			np.asarray(e_eval_rel_ev, dtype=np.float64),
			np.asarray(e_dft_rel_ev, dtype=np.float64),
		):
			sigma_c_at_eval, z_factor = compute_z_factor_from_omega_grid(
				sigma_c_omega_diag_ev=sigma_c_omega_diag_ev,
				omega_rel_ev=omega_rel_ev,
				e_dft_rel_ev=e_eval_rel_ev,
				dE_ev=dE_ev,
			)
			print_fn(
				"  eqp1 linearization: Σ was evaluated away from E_DFT this "
				f"call (max |E_eval − E_DFT| = "
				f"{float(np.max(np.abs(np.asarray(e_eval_ev, dtype=np.float64) - np.asarray(e_dft_ev, dtype=np.float64)))):.4f} eV) "
				"— Z and the Σ_c it multiplies are centred there, not at "
				"E_DFT.  eqp0 stays at E_DFT.")
		else:
			e_eval_ev = None

	eqp0_ev, eqp1_ev = compute_eqp_diag(
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_used,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft,
		e_dft_ev=e_dft_ev,
		z_factor=z_factor,
		sigma_c_at_eval_diag_ev=sigma_c_at_eval,
		e_eval_ev=e_eval_ev,
	)
	return EqpAssembly(
		kpoints_irr_frac=np.asarray(kpoints_irr_frac, dtype=np.float64),
		band_offset=int(band_offset),
		e_dft_ev=np.asarray(e_dft_ev, dtype=np.float64),
		eqp0_ev=eqp0_ev, eqp1_ev=eqp1_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_used,
		hartree_scalar_diag_ev=hartree_scalar_used,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft,
		sigma_c_omega_diag_ev=(
			None if sigma_c_omega_diag_ev is None
			else np.asarray(sigma_c_omega_diag_ev, dtype=np.complex128)),
		z_factor=z_factor,
		implied_vxc_ev=implied_vxc,
		hartree_transverse_diag_ev=hartree_transverse_used,
		nspin=int(nspin),
		e_eval_ev=(None if e_eval_ev is None
		           else np.asarray(e_eval_ev, dtype=np.float64)),
	)


def _warn_on_unphysical_h0(**kwargs):
	"""The live-field mean-field gate, single-sourced from the driver.

	Lives in ``gw.gw_output`` (with its window constants) because that is
	where the diagnosis text belongs; imported lazily here so this module
	stays importable on its own for the post-hoc CLI, exactly as
	:func:`_implied_vxc_window_ev` does.  If the driver is not importable
	(no jax on the host) the assembly falls back to the local
	warn-only bracket rather than skipping the check.
	"""
	try:
		from . import gw_output as _gwo
	except ImportError:
		_warn_on_unphysical_implied_vxc(
			e_dft_ev=kwargs["e_dft_ev"],
			kin_ion_diag_ev=kwargs["kin_ion_diag_ev"],
			hartree_diag_ev=kwargs["hartree_diag_ev"],
		)
		return None
	return _gwo._warn_on_unphysical_h0(**kwargs)


def write_eqp_bgw_pair(
	*,
	eqp0_path: str,
	eqp1_path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	eqp0_ev: np.ndarray,
	eqp1_ev: np.ndarray,
	band_offset: int,
	nspin: int = 1,
) -> tuple[str, str]:
	"""Write the BGW-format eqp0.dat + eqp1.dat pair from precomputed arrays.

	Both files share the same provenance header, k-point list, and
	``E_DFT`` column; only the ``E_QP`` column differs (zeroth-order
	vs. Z-linearized).
	"""
	write_bgw_eqp(eqp0_path, kpoints_irr_frac, e_dft_ev, eqp0_ev,
	              band_offset=band_offset, nspin=nspin)
	write_bgw_eqp(eqp1_path, kpoints_irr_frac, e_dft_ev, eqp1_ev,
	              band_offset=band_offset, nspin=nspin)
	return eqp0_path, eqp1_path


#: Occupations this far from an integer are FRACTIONAL, i.e. a smeared
#: Fermi surface.  Loose on purpose: the question here is "is there a
#: mid-gap to fall back on", and one partially filled state anywhere in
#: the BZ answers it, whatever the smearing width.
_OCC_INTEGER_TOL = 1.0e-6


def _metallic_occupations(ifmax, occupations):
	"""``(metallic, why)`` from a WFN's own occupation record.

	TWO INDEPENDENT SIGNATURES, either of which means "no mid-gap exists":

	* ``ifmax`` — the highest occupied band, per k — is not the same at
	  every k.  That is a band crossing E_F, which is what a Fermi surface
	  IS; ``max(ifmax)`` then names a band that is empty at some k, and
	  ½(VBM+CBM) computed across that split is not a gap centre.
	* any occupation is strictly fractional.  A smeared metal's states at
	  E_F are partially filled by construction.

	Reported separately because they answer different questions when a
	reader comes back to a refusal: the first is geometry, the second is
	smearing.  ``occupations=None`` (a WFN without the dataset) simply
	does not contribute its half.
	"""
	reasons = []
	ifmax = np.asarray(ifmax)
	if ifmax.size and int(np.min(ifmax)) != int(np.max(ifmax)):
		reasons.append(
			f"ifmax varies across k ({int(np.min(ifmax))}..{int(np.max(ifmax))}"
			") — a band crosses E_F")
	if occupations is not None:
		occ = np.asarray(occupations, dtype=np.float64)
		frac = np.abs(occ - np.rint(occ)) > _OCC_INTEGER_TOL
		if bool(np.any(frac)):
			reasons.append(
				f"{int(np.count_nonzero(frac))} of {occ.size} occupations "
				f"are fractional (max deviation "
				f"{float(np.max(np.abs(occ - np.rint(occ)))):.3e})")
	return bool(reasons), "; ".join(reasons) or "insulating"


# ---------------------------------------------------------------------------
# Orchestrator: read the run directory and emit eqp{0,1}.dat
# ---------------------------------------------------------------------------

def _read_eval_energies_ev(
	path: str, *, kirr_to_kfull: np.ndarray, band_start: int, band_stop: int,
) -> np.ndarray:
	"""The IBZ × sigma-window energies (eV) a QP artifact carries.

	Reads either of the two files a run writes its converged spectrum to,
	because both are legitimate answers to "what did Σ get evaluated at"
	and which one is on disk depends on the deck:

	``qp_wfn_rotations.h5`` — ``E_qp_nk_rydberg``, ALREADY on the sigma
	    window (its band axis is ``band_range``), so it is indexed by
	    ``kirr_to_kfull`` and not sliced in bands.  It is read through
	    ``file_io.qp_wfn.read_qp_rotations_full_bz`` because that array may
	    be stored on the file wedge; ``kirr_to_kfull`` is always a full-BZ
	    index, so the indexing below is unchanged either way.  A file with
	    no ``k_storage`` attr comes back verbatim.
	``WFN_qp.h5``           — ``mf_header/kpoints/el``, the WFN file's own
	    k-set (the IBZ) and ALL bands, so it is sliced in bands and not
	    in k.
	"""
	with h5py.File(path, "r") as f:
		has_rot = "E_qp_nk_rydberg" in f
	if has_rot:
		from file_io.qp_wfn import read_qp_rotations_full_bz
		e = np.asarray(read_qp_rotations_full_bz(
			path, datasets=("E_qp_nk_rydberg",))["E_qp_nk_rydberg"],
			dtype=np.float64)
		return e[np.asarray(kirr_to_kfull, dtype=np.int64)] * RYD_TO_EV
	with h5py.File(path, "r") as f:
		if "mf_header/kpoints/el" in f:
			e = np.asarray(f["mf_header/kpoints/el"], dtype=np.float64)
			return e[0][:, int(band_start):int(band_stop)] * RYD_TO_EV
	raise ValueError(
		f"{os.path.basename(path)} carries neither 'E_qp_nk_rydberg' "
		f"(qp_wfn_rotations.h5) nor 'mf_header/kpoints/el' (WFN_qp.h5); it "
		f"cannot say what energies Sigma was evaluated at.")


def make_eqp_bgw(
	run_dir: str,
	*,
	wfn_path: Optional[str] = None,
	kin_ion_path: Optional[str] = None,
	sigma_mnk_path: Optional[str] = None,
	qp_rotations_path: Optional[str] = None,
	eval_energies_path: Optional[str] = None,
	eqp0_out: str = "eqp0.dat",
	eqp1_out: str = "eqp1.dat",
	finite_difference_spacing_ev: float = 0.5,
) -> tuple[str, str]:
	"""Emit BGW-format ``eqp0.dat`` and ``eqp1.dat`` from a LORRAX gw_jax run.

	All file paths default to standard names inside ``run_dir``.  Returns
	``(eqp0_path, eqp1_path)``.

	``eval_energies_path`` — WHERE eqp1 IS LINEARIZED — is the explicit
	OVERRIDE, and it is no longer the only way to get this right.  The two
	candidates on disk are not interchangeable: for a SELF-CONSISTENT run
	``WFN_qp.h5`` / ``qp_wfn_rotations.h5`` hold exactly the converged
	energies Σ was built from and are the right answer, while for a
	ONE-SHOT run those same files hold ``eigh(H₀+Σ)`` — an OUTPUT of the Σ
	that was built at E_DFT, and centring the linearization there would be
	a different, wrong calculation.

	Since 2026-08-22 ``sigma_mnk.h5`` STAMPS which of the two its cube is
	(``file_io.sigma_output.read_eval_energies``), so absent this argument
	this function reads the stamp instead of guessing.  Three outcomes, and
	they are deliberately distinguishable: a stamp saying ``at_e_dft``
	keeps the historical E_DFT centring and says so; a stamp saying
	``self_consistent_qp`` supplies the converged spectrum; and an
	UNSTAMPED file — a cube written before the stamp existed — falls back
	to E_DFT with a printed line saying that is what happened and why it
	may be wrong.  "No stamp" and "stamped at E_DFT" used to look
	identical, and that is the whole defect.  See :func:`compute_eqp_diag`.
	"""
	wfn_path = wfn_path or os.path.join(run_dir, "WFN.h5")
	kin_ion_path = kin_ion_path or os.path.join(run_dir, "kin_ion.h5")
	sigma_mnk_path = sigma_mnk_path or os.path.join(run_dir, "sigma_mnk.h5")
	qp_rotations_path = qp_rotations_path or os.path.join(run_dir, "qp_wfn_rotations.h5")
	eqp0_path = (
		eqp0_out if os.path.isabs(eqp0_out) else os.path.join(run_dir, eqp0_out)
	)
	eqp1_path = (
		eqp1_out if os.path.isabs(eqp1_out) else os.path.join(run_dir, eqp1_out)
	)

	# IBZ k-points + per-state DFT energies (Ry → eV)
	with h5py.File(wfn_path, "r") as wfn:
		kpoints_irr = np.asarray(wfn["mf_header/kpoints/rk"])
		nspin = int(np.asarray(wfn["mf_header/kpoints/nspin"]))
		# energies: (nspin, nk, nbands_total) in Ry
		energies_ry = np.asarray(wfn["mf_header/kpoints/el"])
		ifmax = np.asarray(wfn["mf_header/kpoints/ifmax"])  # (nspin, nk) 1-based
		occupations = (np.asarray(wfn["mf_header/kpoints/occ"])
		               if "mf_header/kpoints/occ" in wfn else None)
	if nspin != 1:
		raise NotImplementedError("LORRAX runs at nspin=1; got nspin={}".format(nspin))

	nk_irr = kpoints_irr.shape[0]

	# IBZ → full-BZ index map; band_range
	with h5py.File(qp_rotations_path, "r") as qp:
		band_range = np.asarray(qp["band_range"], dtype=np.int64)
		kirr_to_kfull = np.asarray(qp["kirr_to_kfull"], dtype=np.int64)
	band_start, band_stop = int(band_range[0]), int(band_range[1])
	nb_window = band_stop - band_start
	if kirr_to_kfull.size != nk_irr:
		raise ValueError(
			f"kirr_to_kfull size {kirr_to_kfull.size} != IBZ kpts {nk_irr}"
		)

	# DFT energies on the IBZ wedge for the sigma window (eV)
	# energies_ry shape (nspin=1, nk_irr, nb_total); take spin 0.
	e_dft_ev = energies_ry[0, :, band_start:band_stop] * RYD_TO_EV
	if e_dft_ev.shape != (nk_irr, nb_window):
		raise ValueError(
			f"WFN energies shape {energies_ry.shape} inconsistent with "
			f"band_range {(band_start, band_stop)} on {nk_irr} IBZ kpts"
		)

	# Post-hoc assembly consumes the completed live-driver receipt.  Older
	# raw cubes cannot prove that their Hartree column came from G-space.
	from file_io.sigma_output import read_eqp_assembly_receipt
	_receipt = read_eqp_assembly_receipt(sigma_mnk_path)
	if _receipt is None:
		raise ValueError(
			f"{os.path.basename(sigma_mnk_path)} has no completed EQP assembly "
			"receipt and cannot authenticate a live G-space Hartree matrix. "
			"Regenerate it with the current driver.")
	omega_rel_ev = _receipt["omega_rel_ev"]
	stamped_ev = _receipt["omega_reference_ev"]
	stamped_provenance = _receipt["omega_reference_provenance"]
	_eval_rel_window = _receipt["eval_energies_rel_ev"]
	_eval_prov = _receipt["eval_energies_provenance"]
	_eval_cov = _receipt["eval_coverage"]

	# ── THE ω REFERENCE: the file's stamp first, midgap only as a legacy
	#    fallback on a file that is demonstrably insulating (audit A2) ──
	#
	# ``sigma_mnk.h5``'s ω axis is RELATIVE, and which zero it is relative
	# to is a property of the RUN that wrote it, not of the WFN this
	# function can see.  The in-run consumers take the finalizer's
	# ``efermi_dft_ev``; this CLI used to recompute ½(VBM+CBM) instead,
	# which on the metal path samples Σ_c(ω) at energies shifted by
	# (mu − midgap) — a measured 2.79 eV on the sodium deck, showing up as
	# a spurious ~+2.4 eV near-E_F QP correction.  So: prefer the stamp;
	# where there is none, fall back to midgap ONLY if the occupations say
	# insulating, and REFUSE otherwise rather than guess wrong by default.
	metallic, why = _metallic_occupations(ifmax, occupations)

	if stamped_ev is not None:
		efermi_ev = float(stamped_ev)
	elif metallic:
		raise ValueError(
			f"make_eqp_bgw: {os.path.basename(sigma_mnk_path)} carries no "
			f"omega_reference_ev stamp, and {os.path.basename(wfn_path)} "
			f"has METALLIC occupations ({why}).\n"
			f"  got  : an unstamped Sigma_c(omega) cube whose axis zero is "
			f"unknown, and a run whose zero is the fixed-N chemical "
			f"potential mu, not mid-gap.\n"
			f"  want : the reference the run interpolated with.  Assuming "
			f"mid-gap here samples Sigma_c at energies shifted by "
			f"(mu - midgap) — 2.79 eV on the sodium deck — and produces "
			f"eqp files that look plausible and are wrong.  There is no "
			f"mid-gap on a metal: the band that would define it crosses "
			f"E_F.\n"
			f"  fix  : regenerate sigma_mnk.h5 with a driver that stamps "
			f"omega_reference_ev (every write since audit A2 does), or "
			f"take eqp0/eqp1 from the run's own output rather than "
			f"reassembling them from disk.  Any comparison already made "
			f"from an unstamped metallic cube through this path is "
			f"invalid.")
	else:
		# Mid-gap Fermi level from the IBZ DFT energies — the pre-stamp
		# insulating convention, kept so every file written before the
		# stamp existed still assembles bit-identically.
		n_occ = int(np.max(ifmax[0]))                   # 1-based highest occ
		occ_idx_local = n_occ - 1 - band_start          # within the window
		if occ_idx_local < 0 or occ_idx_local + 1 >= nb_window:
			raise ValueError(
				"sigma window does not bracket VBM/CBM: band_range="
				f"[{band_start},{band_stop}), VBM index={n_occ - 1}"
			)
		vbm_ev = float(np.max(e_dft_ev[:, : occ_idx_local + 1]))
		cbm_ev = float(np.min(e_dft_ev[:, occ_idx_local + 1 :]))
		efermi_ev = 0.5 * (vbm_ev + cbm_ev)
		stamped_provenance = "midgap (unstamped file, insulating occupations)"
	print(f"  omega reference = {efermi_ev:.6f} eV ({stamped_provenance})")
	e_dft_rel_ev = e_dft_ev - efermi_ev

	# The eqp1 linearization point, on the SAME reference — one subtraction
	# with one ω zero, exactly as the line above.
	e_eval_ev = e_eval_rel_ev = None
	if eval_energies_path is not None:
		e_eval_ev = _read_eval_energies_ev(
			eval_energies_path, kirr_to_kfull=kirr_to_kfull,
			band_start=band_start, band_stop=band_stop)
		if e_eval_ev.shape != e_dft_ev.shape:
			raise ValueError(
				f"eval energies from {os.path.basename(eval_energies_path)} "
				f"have shape {e_eval_ev.shape}, but the sigma window on the "
				f"IBZ is {e_dft_ev.shape}")
		e_eval_rel_ev = e_eval_ev - efermi_ev
		print(f"  eqp1 linearized at {os.path.basename(eval_energies_path)} "
		      f"(max |E_eval − E_DFT| = "
		      f"{float(np.max(np.abs(e_eval_ev - e_dft_ev))):.4f} eV)")

	# kin_ion (Ry → eV), pulled on the IBZ wedge directly.
	#
	# THROUGH ``read_full_bz_dataset``, not a raw h5py read: the file
	# stores the IBZ slab and unfolds on read, so a bare
	# ``kih["kin_ion"]`` here would hand ``kirr_to_kfull`` — full-BZ
	# indices — an ``(nrk, nb, nb)`` array.  Imported lazily (as
	# ``gw.sigma_dispatch`` does) so this module stays importable without
	# pulling in the JAX-dependent file_io stack.
	from file_io.kin_ion import read_full_bz_dataset, read_kin_ion_provenance
	if bool(read_kin_ion_provenance(kin_ion_path).get("has_hartree", False)):
		raise ValueError(
			"post-hoc EQP refuses a retired kin_ion with folded Hartree; "
			"regenerate pristine kin_ion.h5.")
	kin_full = read_full_bz_dataset(kin_ion_path, "kin_ion")
	if kin_full.ndim != 3:
		raise ValueError(f"kin_ion dataset must be (nk, nb, nb); got {kin_full.shape}")
	kin_irr = kin_full[kirr_to_kfull, band_start:band_stop, band_start:band_stop]
	kin_ion_diag_ev = np.real(np.diagonal(kin_irr, axis1=1, axis2=2)) * RYD_TO_EV

	# Sigma payload selection already happened above through its small v5/v6
	# completed-assembly receipt.
	# ── THE LINEARIZATION POINT, FROM THE FILE'S OWN STAMP ────────────
	# ``eval_energies_path`` (above) is the explicit override and still
	# wins; this is the case where nobody passed one.  Before the stamp
	# existed this function could not tell a one-shot cube from a
	# self-consistent one and defaulted to E_DFT: correct for the first,
	# a DIFFERENT CALCULATION for the second, and silent either way.  Now
	# an unstamped file and a file that says "at_e_dft" are distinguishable
	# — the first is an absence and says so out loud, the second is a fact.
	#
	# The format owner already selected this small stamp onto the exact
	# requested file rows and Sigma band window alongside the payload route,
	# so there is no second row remap here.
	from file_io.sigma_output import SIGMA_EVAL_AT_E_DFT
	if e_eval_rel_ev is None:
		if _eval_rel_window is None:
			print(f"  eqp1 linearization: {os.path.basename(sigma_mnk_path)} "
			      f"carries NO evaluation-energy stamp (a file written before "
			      f"2026-08-22).  Falling back to E_DFT, which is correct for "
			      f"a one-shot cube and WRONG for a self-consistent one — "
			      f"pass --eval-energies, or regenerate the cube with a "
			      f"driver that stamps it.")
		elif str(_eval_prov) == SIGMA_EVAL_AT_E_DFT:
			print(f"  eqp1 linearization: stamped {_eval_prov!r} — E_DFT, "
			      f"which is what the historical default did.")
		else:
			_sub = np.asarray(_eval_rel_window, dtype=np.float64)
			if _sub.shape != e_dft_rel_ev.shape:
				raise ValueError(
					f"{os.path.basename(sigma_mnk_path)}'s evaluation-energy "
					f"stamp has IBZ/window shape {_sub.shape} against E_DFT "
					f"{e_dft_rel_ev.shape}; the stamp and the cube disagree "
					f"about the k set or the band window.")
			e_eval_rel_ev = _sub
			e_eval_ev = _sub + efermi_ev
			print(f"  eqp1 linearization: stamped {_eval_prov!r} "
			      f"(max |E_eval − E_DFT| = "
			      f"{float(np.max(np.abs(e_eval_ev - e_dft_ev))):.4f} eV)")
		if _eval_cov and int(_eval_cov["n_uncovered"]):
			print(f"  omega coverage (stamped): "
			      f"{_eval_cov['n_uncovered']} evaluation energies "
			      f"({100.0 * _eval_cov['fraction_uncovered']:.1f}%) lie "
			      f"outside the sampled grid; policy="
			      f"{_eval_cov['policy']}.  Those states' sigC is an "
			      f"endpoint value, not Sigma at their own energy.")

	# The receipt carries the exact conditioned operands used by the live writer.
	if (_receipt["band_start"], _receipt["band_stop"]) != (
			band_start, band_stop):
		raise ValueError(
			f"{os.path.basename(sigma_mnk_path)}'s EQP receipt covers "
			f"[{_receipt['band_start']},{_receipt['band_stop']}) but the "
			f"requested window is [{band_start},{band_stop}).")
	expect_shape = (nk_irr, nb_window)
	if (_receipt["hartree_diag_ev"].shape != expect_shape
			or _receipt["sigma_x_diag_ev"].shape != expect_shape
			or _receipt["sigma_c_at_dft_diag_ev"].shape != expect_shape
			or _receipt["sigma_c_omega_diag_ev"].shape
			!= (omega_rel_ev.size, *expect_shape)):
		raise ValueError("EQP receipt operands do not match the requested window.")
	if not np.array_equal(
			_receipt["file_wedge_full_bz_rows"], kirr_to_kfull):
		raise ValueError(
			"EQP receipt and QP rotations name different full-BZ k rows.")
	hartree_diag = _receipt["hartree_diag_ev"]
	receipt_hartree_scalar = _receipt["hartree_scalar_diag_ev"]
	receipt_hartree_transverse = _receipt["hartree_transverse_diag_ev"]
	sigma_x_diag = _receipt["sigma_x_diag_ev"]
	receipt_c_at_dft = _receipt["sigma_c_at_dft_diag_ev"]
	sigma_c_omega_diag = _receipt["sigma_c_omega_diag_ev"]
	print(
		f"  EQP assembly receipt: schema v{_receipt['schema_version']}, "
		"live G-space H plus conditioned X/C(omega); raw operators untouched.")

	# From here on: zero independent semantics.  Same assembly (mean-field
	# gate + Z-factor + Newton update), same formatter, as
	# ``gw_output.write_results``.  This CLI's whole remaining job is
	# "load artifacts, then call these two".
	assembly = assemble_eqp(
		kpoints_irr_frac=kpoints_irr,
		band_offset=band_start,
		e_dft_ev=e_dft_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=np.real(hartree_diag),
		sigma_x_diag_ev=np.real(sigma_x_diag),
		sigma_c_omega_diag_ev=sigma_c_omega_diag,
		omega_rel_ev=omega_rel_ev,
		e_dft_rel_ev=e_dft_rel_ev,
		e_eval_ev=e_eval_ev,
		e_eval_rel_ev=e_eval_rel_ev,
		dE_ev=finite_difference_spacing_ev,
		nspin=1,
		hartree_scalar_diag_ev=receipt_hartree_scalar,
		hartree_transverse_diag_ev=receipt_hartree_transverse,
	)
	if (receipt_c_at_dft is not None
			and not np.array_equal(
				np.asarray(assembly.sigma_c_at_dft_diag_ev),
				np.asarray(receipt_c_at_dft))):
		raise ValueError(
			f"{os.path.basename(sigma_mnk_path)}'s persisted C(E_DFT) does not "
			"equal the shared assembler's value re-derived from the persisted "
			"conditioned C(omega) curve.")
	return assembly.write(eqp0_path=eqp0_path, eqp1_path=eqp1_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
	p = argparse.ArgumentParser(allow_abbrev=False,
		prog="python -m gw.eqp_bgw",
		description="Reproduce BGW eqp0.dat / eqp1.dat from a LORRAX gw_jax run.",
	)
	p.add_argument("run_dir", help="Run directory containing WFN.h5, kin_ion.h5, sigma_mnk.h5, qp_wfn_rotations.h5")
	p.add_argument("--wfn", default=None, help="Path to WFN.h5 (default: <run_dir>/WFN.h5)")
	p.add_argument("--kin-ion", default=None, help="Path to kin_ion.h5")
	p.add_argument("--sigma-mnk", default=None, help="Path to sigma_mnk.h5")
	p.add_argument("--qp-rotations", default=None, help="Path to qp_wfn_rotations.h5")
	p.add_argument(
		"--eval-energies", default=None,
		help="WFN_qp.h5 or qp_wfn_rotations.h5 holding the energies Sigma "
		     "was evaluated at, for the eqp1 linearization.  SELF-CONSISTENT "
		     "runs only — on a one-shot run those files hold eigh(H0+Sigma), "
		     "an output, and passing them centres eqp1 in the wrong place.  "
		     "Default: linearize at E_DFT (correct for one-shot)")
	p.add_argument("--eqp0", default="eqp0.dat", help="Output eqp0 filename (relative to run_dir unless absolute)")
	p.add_argument("--eqp1", default="eqp1.dat", help="Output eqp1 filename (relative to run_dir unless absolute)")
	p.add_argument(
		"--finite-difference-spacing",
		type=float, default=0.5,
		help="dE (eV) for the Z-factor central difference (BGW default 0.5)",
	)
	return p


def main(argv: Optional[list[str]] = None) -> int:
	args = _build_parser().parse_args(argv)
	eqp0_path, eqp1_path = make_eqp_bgw(
		args.run_dir,
		wfn_path=args.wfn,
		kin_ion_path=args.kin_ion,
		sigma_mnk_path=args.sigma_mnk,
		qp_rotations_path=args.qp_rotations,
		eval_energies_path=args.eval_energies,
		eqp0_out=args.eqp0,
		eqp1_out=args.eqp1,
		finite_difference_spacing_ev=args.finite_difference_spacing,
	)
	print(f"wrote: {eqp0_path}")
	print(f"wrote: {eqp1_path}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
