"""Fermi-surface quadrature on a periodic uniform three-dimensional grid."""

from __future__ import annotations

import itertools

import numpy as np


_REF_VERTICES = np.asarray(
    ((0.0, 0.0, 0.0),
     (1.0, 0.0, 0.0),
     (0.0, 1.0, 0.0),
     (0.0, 0.0, 1.0)),
    dtype=np.float64,
)
_EDGES = ((0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3))
_AXES = np.eye(3, dtype=np.int64)
_TETRA_OFFSETS = tuple(
    np.stack((np.zeros(3, dtype=np.int64),
              _AXES[a],
              _AXES[a] + _AXES[b],
              np.ones(3, dtype=np.int64)))
    for a, b, _c in itertools.permutations(range(3))
)


def _canonical_tetrahedron(offsets):
    """Canonical representative under integer translation and relabelling."""
    offsets = np.asarray(offsets, dtype=np.int64)
    offsets = offsets - np.min(offsets, axis=0, keepdims=True)
    return tuple(sorted(tuple(int(x) for x in vertex) for vertex in offsets))


def _tetrahedron_decomposition_orbit(symmetry_matrices):
    """Distinct periodic Kuhn decompositions generated by a point group."""
    matrices = np.asarray(symmetry_matrices)
    if matrices.ndim != 3 or matrices.shape[1:] != (3, 3):
        raise ValueError(
            "symmetry_matrices must have shape (nsym,3,3), got "
            f"{matrices.shape}")
    rounded = np.rint(matrices).astype(np.int64)
    if (not np.allclose(matrices, rounded, rtol=0.0, atol=1.0e-10)
            or np.any(np.abs(np.rint(np.linalg.det(rounded))) != 1)):
        raise ValueError("symmetry_matrices must be integer unimodular matrices")

    orbit = {}
    for matrix in rounded:
        decomposition = tuple(sorted(
            _canonical_tetrahedron(offsets @ matrix.T)
            for offsets in _TETRA_OFFSETS
        ))
        orbit.setdefault(
            decomposition,
            tuple(np.asarray(tetrahedron, dtype=np.int64)
                  for tetrahedron in decomposition),
        )
    return tuple(orbit.values())


def _tetra_delta_vertex_weights(energy4, chemical_potential):
    """Integral weights for linear vertex data times delta(E-mu)."""
    energy = np.asarray(energy4, dtype=np.float64)
    mu = float(np.nextafter(float(chemical_potential), np.inf))
    if mu <= float(np.min(energy)) or mu >= float(np.max(energy)):
        return np.zeros(4, dtype=np.float64)
    gradient = energy[1:] - energy[0]
    gradient_norm = float(np.linalg.norm(gradient))
    if gradient_norm <= 1.0e-15:
        return np.zeros(4, dtype=np.float64)

    points = []
    barycentric = []
    for i, j in _EDGES:
        di = mu - energy[i]
        dj = mu - energy[j]
        if di * dj >= 0.0:
            continue
        t = di / (energy[j] - energy[i])
        lam = np.zeros(4, dtype=np.float64)
        lam[i] = 1.0 - t
        lam[j] = t
        points.append((1.0 - t) * _REF_VERTICES[i] + t * _REF_VERTICES[j])
        barycentric.append(lam)
    if len(points) not in (3, 4):
        return np.zeros(4, dtype=np.float64)

    points = np.asarray(points, dtype=np.float64)
    barycentric = np.asarray(barycentric, dtype=np.float64)
    centroid = np.mean(points, axis=0)
    normal = gradient / gradient_norm
    u = points[0] - centroid
    u_norm = float(np.linalg.norm(u))
    if u_norm <= 1.0e-15:
        return np.zeros(4, dtype=np.float64)
    u /= u_norm
    v = np.cross(normal, u)
    angles = np.arctan2((points - centroid) @ v, (points - centroid) @ u)
    order = np.argsort(angles)
    points = points[order]
    barycentric = barycentric[order]

    result = np.zeros(4, dtype=np.float64)
    for i in range(1, len(points) - 1):
        area = 0.5 * float(np.linalg.norm(np.cross(
            points[i] - points[0], points[i + 1] - points[0])))
        result += (
            area / (3.0 * gradient_norm)
            * (barycentric[0] + barycentric[i] + barycentric[i + 1])
        )
    return result


def _uniform_grid_indices(kpoints_crystal, kgrid):
    points = np.mod(np.asarray(kpoints_crystal, dtype=np.float64), 1.0)
    grid = np.asarray(kgrid, dtype=np.int64)
    if points.ndim != 2 or points.shape[1] != 3 or np.any(grid < 2):
        raise ValueError("need kpoints (nk,3) and a three-dimensional kgrid >= 2")
    scaled = points * grid[None, :]
    # A common shift is defined modulo an integer.  Taking one point's
    # signed residual avoids the 0/1 branch cut that makes a median of
    # ``mod(scaled,1)`` ambiguous on nominally unshifted grids.
    shift = scaled[0] - np.rint(scaled[0])
    residual = scaled - shift[None, :]
    indices = np.mod(np.rint(residual).astype(np.int64), grid[None, :])
    error = np.max(np.abs(residual - np.rint(residual)))
    if error > 2.0e-7:
        raise ValueError(
            f"kpoints are not one uniformly shifted {tuple(grid)} grid; "
            f"maximum integer-coordinate residual is {error:.3e}")
    return indices


def tetrahedron_delta_weights(
    energies_kn,
    kpoints_crystal,
    kgrid,
    chemical_potential,
    *,
    symmetry_matrices=None,
):
    """Return normalized-BZ weights for ``integral delta(E-mu) g(k) dk``.

    The returned ``weights_kn`` have units inverse to the supplied energies
    and satisfy ``sum_kn weights_kn*g_kn`` for linearly interpolated vertex
    data ``g``.  Every periodic grid cell is split into the six tetrahedra
    sharing its body diagonal.  No smearing or empirical normalization is
    introduced.

    **With ``symmetry_matrices=None`` the returned table is NOT
    star-covariant, by construction.**  The six tetrahedra of
    ``_TETRA_OFFSETS`` all share the ONE hardcoded ``(1,1,1)`` body diagonal
    (the Kuhn triangulation), so the partition is invariant only under the
    crystal ops that map that grid line onto itself and act as signed
    permutations of the grid axes.  Measured on the bcc sodium 8x8x8 deck
    (48 ops, all of them energy-preserving grid automorphisms): 16 preserve
    the ``(1,1,1)`` LINE and only **4 of 48** leave the weight table itself
    invariant, with a 76 percent worst-case relative violation between star
    partners.  Consequences measured on the same deck's converged state:
    ``N(E_F)`` differs by up to 0.0425 states/Ry/cell across one star (2.9x
    the mean per-k value), and the head's Drude tensor comes out 2.68 percent
    ANISOTROPIC on a cubic crystal, with the unique axis along the Cartesian
    image of ``(1,1,1)``.

    Supplying ``symmetry_matrices`` averages the distinct periodic
    decompositions in the Kuhn partition's point-group orbit and makes the
    base rule star covariant.  The metallic caller uses that path and also
    passes the result through :func:`star_symmetrize_weights` as a
    post-integration safeguard.
    """
    energies = np.asarray(energies_kn, dtype=np.float64)
    grid = np.asarray(kgrid, dtype=np.int64)
    nk_expected = int(np.prod(grid))
    if energies.ndim != 2 or energies.shape[0] != nk_expected:
        raise ValueError(
            f"energies must be ({nk_expected},nb), got {energies.shape}")
    indices = _uniform_grid_indices(kpoints_crystal, grid)
    grid_to_flat = np.full(tuple(grid), -1, dtype=np.int64)
    for flat, ijk in enumerate(indices):
        key = tuple(int(x) for x in ijk)
        if grid_to_flat[key] >= 0:
            raise ValueError(f"duplicate k-grid coordinate {key}")
        grid_to_flat[key] = flat
    if np.any(grid_to_flat < 0):
        raise ValueError("the supplied kpoints do not cover the full periodic grid")

    decompositions = ((_TETRA_OFFSETS,) if symmetry_matrices is None else
                      _tetrahedron_decomposition_orbit(symmetry_matrices))
    weights = np.zeros_like(energies)
    cell_jacobian = 1.0 / (float(len(decompositions)) * float(nk_expected))
    nbands = int(energies.shape[1])
    for base in np.ndindex(*(int(x) for x in grid)):
        base_vec = np.asarray(base, dtype=np.int64)
        for decomposition in decompositions:
            for offsets in decomposition:
                vertices = np.mod(base_vec[None, :] + offsets, grid[None, :])
                flat = np.asarray(
                    [grid_to_flat[tuple(int(x) for x in vertex)]
                     for vertex in vertices],
                    dtype=np.int64,
                )
                for band in range(nbands):
                    local = _tetra_delta_vertex_weights(
                        energies[flat, band], chemical_potential)
                    weights[flat, band] += cell_jacobian * local
    return weights


def star_symmetrize_weights(weights_kn, star_index):
    r"""Restore star covariance to a Fermi-surface weight table.

    ``wbar(k, n) = (1/|G|) sum_{R in G} w(Rk, n)``.

    Every ``R`` permutes a star onto itself and carries band ``n`` to band
    ``n`` (the two k share an eigenvalue vector, so the energy-ordered band
    index is the same label), and each member of the star is hit exactly
    ``|G|/|star|`` times.  The group average is therefore the plain MEAN of
    ``w`` over the star -- no symmetry matrices are needed here, only the
    star label of each full-BZ point, which the caller already carries as
    ``sym.irr_idx_k``.

    Why this is EXACT and not an approximation.  The quantity being built is
    ``I[g] = integral delta(E-mu) g(k) dk`` for a star-covariant integrand
    ``g``.  For such a ``g``, ``sum_kn wbar_kn g_kn == sum_kn w_kn g_kn``:
    the symmetrization moves weight only BETWEEN star partners, where ``g``
    is equal, so no integral of a covariant integrand changes value.  What
    it does change is the tensor STRUCTURE of integrals of non-invariant
    integrands -- ``sum_kn w_kn v_a v_b`` is the case that matters -- which
    is exactly the defect.  ``sum_kn wbar_kn == sum_kn w_kn`` identically,
    so ``N(E_F)`` and the Drude trace are untouched to the last bit.

    What it does NOT fix: the O(h^2) accuracy of the linear-tetrahedron rule
    itself, and the anisotropy of the interpolant inside each cell (the same
    Kuhn diagonal biases the linear interpolation, not just the weights).  A
    Bloechl correction is an ACCURACY axis, not a symmetry one -- a corrected
    non-adapted partition is still non-covariant.  The structural fix is a
    symmetry-adapted partition; the production caller supplies its point
    group to :func:`tetrahedron_delta_weights` to construct one.

    Parameters
    ----------
    weights_kn : (nk, nb) array
        The table from :func:`tetrahedron_delta_weights`.
    star_index : (nk,) integer array
        Star (orbit) label per full-BZ k point; ``sym.irr_idx_k`` is one.
    """
    weights = np.asarray(weights_kn, dtype=np.float64)
    labels = np.asarray(star_index, dtype=np.int64)
    if weights.ndim != 2:
        raise ValueError(
            f"star_symmetrize_weights: weights must be (nk,nb), got {weights.shape}")
    if labels.shape != (weights.shape[0],):
        raise ValueError(
            "star_symmetrize_weights: star_index must be (nk,), got "
            f"{labels.shape} against nk={weights.shape[0]}")
    if labels.size and labels.min() < 0:
        raise ValueError("star_symmetrize_weights: star_index must be >= 0")
    # Dense relabelling: `irr_idx_k` indexes the IBZ, so its labels are
    # already dense, but a caller may hand any labelling and a sparse one
    # would silently allocate an oversized accumulator.
    _, compact = np.unique(labels, return_inverse=True)
    counts = np.bincount(compact).astype(np.float64)
    sums = np.zeros((counts.size, weights.shape[1]), dtype=np.float64)
    np.add.at(sums, compact, weights)
    return sums[compact] / counts[compact][:, None]


__all__ = ["tetrahedron_delta_weights", "star_symmetrize_weights"]
