"""Fermi-surface quadrature on a periodic uniform three-dimensional grid."""

from __future__ import annotations

import itertools

import numpy as np


_REF_VERTICES = np.asarray(
    ((0.0, 0.0, 0.0),
     (1.0, 0.0, 0.0),
     (0.0, 1.0, 0.0),
     (0.0, 0.0, 1.0)),
    dtype=np.float64,
)
_EDGES = ((0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3))
_AXES = np.eye(3, dtype=np.int64)
_TETRA_OFFSETS = tuple(
    np.stack((np.zeros(3, dtype=np.int64),
              _AXES[a],
              _AXES[a] + _AXES[b],
              np.ones(3, dtype=np.int64)))
    for a, b, _c in itertools.permutations(range(3))
)


def _canonical_tetrahedron(offsets):
    """Canonical representative under integer translation and relabelling."""
    offsets = np.asarray(offsets, dtype=np.int64)
    offsets = offsets - np.min(offsets, axis=0, keepdims=True)
    return tuple(sorted(tuple(int(x) for x in vertex) for vertex in offsets))


def _tetrahedron_decomposition_orbit(symmetry_matrices):
    """Distinct periodic Kuhn decompositions generated by a point group."""
    matrices = np.asarray(symmetry_matrices)
    if matrices.ndim != 3 or matrices.shape[1:] != (3, 3):
        raise ValueError(
            "symmetry_matrices must have shape (nsym,3,3), got "
            f"{matrices.shape}")
    rounded = np.rint(matrices).astype(np.int64)
    if (not np.allclose(matrices, rounded, rtol=0.0, atol=1.0e-10)
            or np.any(np.abs(np.rint(np.linalg.det(rounded))) != 1)):
        raise ValueError("symmetry_matrices must be integer unimodular matrices")

    orbit = {}
    for matrix in rounded:
        decomposition = tuple(sorted(
            _canonical_tetrahedron(offsets @ matrix.T)
            for offsets in _TETRA_OFFSETS
        ))
        orbit.setdefault(
            decomposition,
            tuple(np.asarray(tetrahedron, dtype=np.int64)
                  for tetrahedron in decomposition),
        )
    return tuple(orbit.values())


def _tetra_delta_vertex_weights(energy4, chemical_potential):
    """Integral weights for linear vertex data times delta(E-mu)."""
    energy = np.asarray(energy4, dtype=np.float64)
    mu = float(np.nextafter(float(chemical_potential), np.inf))
    if mu <= float(np.min(energy)) or mu >= float(np.max(energy)):
        return np.zeros(4, dtype=np.float64)
    gradient = energy[1:] - energy[0]
    gradient_norm = float(np.linalg.norm(gradient))
    if gradient_norm <= 1.0e-15:
        return np.zeros(4, dtype=np.float64)

    points = []
    barycentric = []
    for i, j in _EDGES:
        di = mu - energy[i]
        dj = mu - energy[j]
        if di * dj >= 0.0:
            continue
        t = di / (energy[j] - energy[i])
        lam = np.zeros(4, dtype=np.float64)
        lam[i] = 1.0 - t
        lam[j] = t
        points.append((1.0 - t) * _REF_VERTICES[i] + t * _REF_VERTICES[j])
        barycentric.append(lam)
    if len(points) not in (3, 4):
        return np.zeros(4, dtype=np.float64)

    points = np.asarray(points, dtype=np.float64)
    barycentric = np.asarray(barycentric, dtype=np.float64)
    centroid = np.mean(points, axis=0)
    normal = gradient / gradient_norm
    u = points[0] - centroid
    u_norm = float(np.linalg.norm(u))
    if u_norm <= 1.0e-15:
        return np.zeros(4, dtype=np.float64)
    u /= u_norm
    v = np.cross(normal, u)
    angles = np.arctan2((points - centroid) @ v, (points - centroid) @ u)
    order = np.argsort(angles)
    points = points[order]
    barycentric = barycentric[order]

    result = np.zeros(4, dtype=np.float64)
    for i in range(1, len(points) - 1):
        area = 0.5 * float(np.linalg.norm(np.cross(
            points[i] - points[0], points[i + 1] - points[0])))
        result += (
            area / (3.0 * gradient_norm)
            * (barycentric[0] + barycentric[i] + barycentric[i + 1])
        )
    return result


def _uniform_grid_indices(kpoints_crystal, kgrid):
    points = np.mod(np.asarray(kpoints_crystal, dtype=np.float64), 1.0)
    grid = np.asarray(kgrid, dtype=np.int64)
    # A one-point axis (a slab's z) is admitted: every tetrahedron step along
    # it wraps to the same k, so the Kuhn cells reduce exactly to the
    # triangle rule of the remaining axes (their fibres sum to one).
    if points.ndim != 2 or points.shape[1] != 3 or grid.shape != (3,) or np.any(grid < 1):
        raise ValueError("need kpoints (nk,3) and a three-dimensional kgrid >= 1")
    scaled = points * grid[None, :]
    # A common shift is defined modulo an integer.  Taking one point's
    # signed residual avoids the 0/1 branch cut that makes a median of
    # ``mod(scaled,1)`` ambiguous on nominally unshifted grids.
    shift = scaled[0] - np.rint(scaled[0])
    residual = scaled - shift[None, :]
    indices = np.mod(np.rint(residual).astype(np.int64), grid[None, :])
    error = np.max(np.abs(residual - np.rint(residual)))
    if error > 2.0e-7:
        raise ValueError(
            f"kpoints are not one uniformly shifted {tuple(grid)} grid; "
            f"maximum integer-coordinate residual is {error:.3e}")
    return indices


def tetrahedron_delta_weights(
    energies_kn,
    kpoints_crystal,
    kgrid,
    chemical_potential,
    *,
    symmetry_matrices=None,
):
    """Return normalized-BZ weights for ``integral delta(E-mu) g(k) dk``.

    The returned ``weights_kn`` have units inverse to the supplied energies
    and satisfy ``sum_kn weights_kn*g_kn`` for linearly interpolated vertex
    data ``g``.  Every periodic grid cell is split into the six tetrahedra
    sharing its body diagonal.  No smearing or empirical normalization is
    introduced.

    **With ``symmetry_matrices=None`` the returned table is NOT
    star-covariant, by construction.**  The six tetrahedra of
    ``_TETRA_OFFSETS`` all share the ONE hardcoded ``(1,1,1)`` body diagonal
    (the Kuhn triangulation), so the partition is invariant only under the
    crystal ops that map that grid line onto itself and act as signed
    permutations of the grid axes.  Measured on the bcc sodium 8x8x8 deck
    (48 ops, all of them energy-preserving grid automorphisms): 16 preserve
    the ``(1,1,1)`` LINE and only **4 of 48** leave the weight table itself
    invariant, with a 76 percent worst-case relative violation between star
    partners.  Consequences measured on the same deck's converged state:
    ``N(E_F)`` differs by up to 0.0425 states/Ry/cell across one star (2.9x
    the mean per-k value), and the head's Drude tensor comes out 2.68 percent
    ANISOTROPIC on a cubic crystal, with the unique axis along the Cartesian
    image of ``(1,1,1)``.

    Supplying ``symmetry_matrices`` averages the distinct periodic
    decompositions in the Kuhn partition's point-group orbit and makes the
    base rule star covariant.  The metallic caller uses that path and also
    passes the result through :func:`star_symmetrize_weights` as a
    post-integration safeguard.
    """
    energies = np.asarray(energies_kn, dtype=np.float64)
    grid = np.asarray(kgrid, dtype=np.int64)
    nk_expected = int(np.prod(grid))
    if energies.ndim != 2 or energies.shape[0] != nk_expected:
        raise ValueError(
            f"energies must be ({nk_expected},nb), got {energies.shape}")
    indices = _uniform_grid_indices(kpoints_crystal, grid)
    grid_to_flat = np.full(tuple(grid), -1, dtype=np.int64)
    for flat, ijk in enumerate(indices):
        key = tuple(int(x) for x in ijk)
        if grid_to_flat[key] >= 0:
            raise ValueError(f"duplicate k-grid coordinate {key}")
        grid_to_flat[key] = flat
    if np.any(grid_to_flat < 0):
        raise ValueError("the supplied kpoints do not cover the full periodic grid")

    decompositions = ((_TETRA_OFFSETS,) if symmetry_matrices is None else
                      _tetrahedron_decomposition_orbit(symmetry_matrices))
    weights = np.zeros_like(energies)
    cell_jacobian = 1.0 / (float(len(decompositions)) * float(nk_expected))
    # Every tetrahedron's four grid vertices, in the order of the historical
    # loop (cell, decomposition, tetrahedron): ``flat[t]`` is tetrahedron t.
    bases = np.asarray(list(np.ndindex(*(int(x) for x in grid))),
                       dtype=np.int64).reshape(-1, 3)
    offsets = np.stack([offsets for decomposition in decompositions
                        for offsets in decomposition])
    vertices = np.mod(bases[:, None, None, :] + offsets[None], grid)
    flat = grid_to_flat[vertices[..., 0], vertices[..., 1],
                        vertices[..., 2]].reshape(-1, 4)
    # ``_tetra_delta_vertex_weights`` returns exact zeros unless
    # min E < mu' < max E (mu' = nextafter(mu)), and adding +0.0 changes no
    # weight, so only the (tetrahedron, band) pairs that straddle mu' are
    # visited, in the historical order: the table is bit-identical.
    mu_edge = float(np.nextafter(float(chemical_potential), np.inf))
    block = 4096
    for start in range(0, flat.shape[0], block):
        corner = energies[flat[start:start + block]]
        straddles = ((np.min(corner, axis=1) < mu_edge)
                     & (np.max(corner, axis=1) > mu_edge))
        for tet, band in zip(*np.nonzero(straddles)):
            vertex = flat[start + tet]
            local = _tetra_delta_vertex_weights(
                energies[vertex, band], chemical_potential)
            weights[vertex, band] += cell_jacobian * local
    return weights


def star_symmetrize_weights(weights_kn, star_index):
    r"""Restore star covariance to a Fermi-surface weight table.

    ``wbar(k, n) = (1/|G|) sum_{R in G} w(Rk, n)``.

    Every ``R`` permutes a star onto itself and carries band ``n`` to band
    ``n`` (the two k share an eigenvalue vector, so the energy-ordered band
    index is the same label), and each member of the star is hit exactly
    ``|G|/|star|`` times.  The group average is therefore the plain MEAN of
    ``w`` over the star -- no symmetry matrices are needed here, only the
    star label of each full-BZ point, which the caller already carries as
    ``sym.irr_idx_k``.

    Why this is EXACT and not an approximation.  The quantity being built is
    ``I[g] = integral delta(E-mu) g(k) dk`` for a star-covariant integrand
    ``g``.  For such a ``g``, ``sum_kn wbar_kn g_kn == sum_kn w_kn g_kn``:
    the symmetrization moves weight only BETWEEN star partners, where ``g``
    is equal, so no integral of a covariant integrand changes value.  What
    it does change is the tensor STRUCTURE of integrals of non-invariant
    integrands -- ``sum_kn w_kn v_a v_b`` is the case that matters -- which
    is exactly the defect.  ``sum_kn wbar_kn == sum_kn w_kn`` identically,
    so ``N(E_F)`` and the Drude trace are untouched to the last bit.

    What it does NOT fix: the O(h^2) accuracy of the linear-tetrahedron rule
    itself, and the anisotropy of the interpolant inside each cell (the same
    Kuhn diagonal biases the linear interpolation, not just the weights).  A
    Bloechl correction is an ACCURACY axis, not a symmetry one -- a corrected
    non-adapted partition is still non-covariant.  The structural fix is a
    symmetry-adapted partition; the production caller supplies its point
    group to :func:`tetrahedron_delta_weights` to construct one.

    Parameters
    ----------
    weights_kn : (nk, nb) array
        The table from :func:`tetrahedron_delta_weights`.
    star_index : (nk,) integer array
        Star (orbit) label per full-BZ k point; ``sym.irr_idx_k`` is one.
    """
    weights = np.asarray(weights_kn, dtype=np.float64)
    labels = np.asarray(star_index, dtype=np.int64)
    if weights.ndim != 2:
        raise ValueError(
            f"star_symmetrize_weights: weights must be (nk,nb), got {weights.shape}")
    if labels.shape != (weights.shape[0],):
        raise ValueError(
            "star_symmetrize_weights: star_index must be (nk,), got "
            f"{labels.shape} against nk={weights.shape[0]}")
    if labels.size and labels.min() < 0:
        raise ValueError("star_symmetrize_weights: star_index must be >= 0")
    # Dense relabelling: `irr_idx_k` indexes the IBZ, so its labels are
    # already dense, but a caller may hand any labelling and a sparse one
    # would silently allocate an oversized accumulator.
    _, compact = np.unique(labels, return_inverse=True)
    counts = np.bincount(compact).astype(np.float64)
    sums = np.zeros((counts.size, weights.shape[1]), dtype=np.float64)
    np.add.at(sums, compact, weights)
    return sums[compact] / counts[compact][:, None]


def metal_head_surface_weights(energies_kn, chemical_potential, *, sym, kgrid,
                               bvec_cart, nb_storage=None):
    r"""Return the metallic head's Fermi-surface table ``Nk * w_kn``.

    ``w_kn`` is the star-covariant tetrahedron weight of
    ``integral delta(E_n(k) - mu) dk`` over the normalized zone, at the
    fixed-N chemical potential: the reciprocal lattice's decomposition orbit
    (:func:`tetrahedron_delta_weights`) followed by the star average
    (:func:`star_symmetrize_weights`), then averaged over each degenerate
    multiplet at BGW's TOL_Degeneracy.  The factor ``Nk`` matches the head
    contractions' uniform ``1/Nk``; ``N(E_F) = capacity * sum_kn w_kn``.
    Columns past ``energies_kn.shape[1]`` up to ``nb_storage`` are exact
    zeros.  Every metallic head route (the QSGW map, the frozen DFT head,
    the one-shot head) takes its table here. ``bvec_cart`` has reciprocal
    basis vectors as rows. The partition depends on this geometry and grid,
    never on the WFN's stored operations; no symmetry of the integrand is
    assumed by averaging quadrature partitions.
    """
    energies = np.asarray(energies_kn, dtype=np.float64)
    from symmetry_maps import lattice_grid_point_group
    weights = tetrahedron_delta_weights(
        energies, np.asarray(sym.unfolded_kpts, dtype=np.float64),
        tuple(int(x) for x in kgrid), float(chemical_potential),
        symmetry_matrices=lattice_grid_point_group(bvec_cart, kgrid))
    weights = star_symmetrize_weights(weights, np.asarray(sym.irr_idx_k))
    # One weight per degenerate multiplet: the Drude tensor contracts the
    # multiplet trace, which is basis invariant only for a common weight.
    # Band-sorted linear tetrahedra give members of one multiplet different
    # weights; the mean keeps N(E_F) unchanged.
    from .degen_average import average_within_degenerate_sets
    weights = average_within_degenerate_sets(weights, energies)
    weights = weights * float(energies.shape[0])
    width = int(energies.shape[1] if nb_storage is None else nb_storage)
    if width < energies.shape[1]:
        raise ValueError(
            f"nb_storage={width} is narrower than the {energies.shape[1]} "
            "logical head bands")
    return np.pad(weights, ((0, 0), (0, width - energies.shape[1])))


#: Unit vertices of a regular tetrahedron: zero mean, (1/4) sum t t^T = I/3.
_TETRAHEDRON_UNIT = np.asarray(
    ((1.0, 1.0, 1.0), (1.0, -1.0, -1.0), (-1.0, 1.0, -1.0), (-1.0, -1.0, 1.0)),
    dtype=np.float64) / np.sqrt(3.0)
#: Atoms per scan block of the intraband response (bounds the (nq, block) temporary).
_ATOM_BLOCK = 64


def intraband_pair_fraction(v_local, delta_e, diag_bra, diag_ket, w_bra, w_ket,
                            cell_moment, tol_ry):
    r"""Fermi-surface share ``phi`` of each band pair of a metallic head tile.

    A pair's first-order long-wavelength vertex is the small-q end of the
    two-band overlap ``sin^2 theta(q)``, whose Pade form
    ``(x/4)/(1 + x/2)``, ``x = [(q.dv)^2 + 4|q.v_nm|^2]/Delta^2``
    (``dv = v_mm - v_nn``), is exact at both ends.  Read at the q = 0
    cell's Coulomb-weighted second moment ``Q`` (``vcoul.minibz_coulomb_moment``),

    .. math:: \phi=\frac{\epsilon^2}{\Delta^2+\epsilon^2},\qquad
              \epsilon^2=\mathrm{tr}\,Q\,[\delta v\,\delta v^{\sf T}+4\,\mathrm{Re}\,v_{nm}^*v_{nm}^{\sf T}],

    the interband tensor keeps ``1 - phi`` of the pair and the Fermi-surface
    term takes ``phi``.  Only pairs with Fermi-surface weight
    (``w_bra + w_ket > 0``) move; an exact degeneracy (``|Delta| < tol_ry``)
    has ``phi = 1``.  On an insulator every weight vanishes and ``phi`` is the
    degeneracy rule.  ``docs/theory/metal-q0-head.md`` section 2.

    Shapes (one shard_map tile): ``v_local (3,nk,nx,ny)`` complex,
    ``delta_e (nk,nx,ny)``, ``diag_bra (3,nk,nx)``, ``diag_ket (3,nk,ny)``,
    ``w_bra (nk,nx)``, ``w_ket (nk,ny)``, ``cell_moment (3,3)``.
    """
    import jax.numpy as jnp

    Q = jnp.asarray(cell_moment, jnp.float64)
    dv = diag_ket[:, :, None, :] - diag_bra[:, :, :, None]
    q_dv = jnp.einsum("ab,akxy,bkxy->kxy", Q, dv, dv)
    q_v = jnp.real(jnp.einsum("ab,akxy,bkxy->kxy", Q.astype(v_local.dtype),
                              jnp.conj(v_local), v_local))
    extent = q_dv + 4.0 * q_v
    delta2 = delta_e * delta_e
    exact = jnp.abs(delta_e) < tol_ry
    on_surface = (w_bra[:, :, None] + w_ket[:, None, :]) > 0.0
    share = extent / jnp.where(exact, 1.0, delta2 + extent)
    return jnp.where(exact, 1.0, jnp.where(on_surface, share, 0.0))


def _intraband_blocks(weights, velocities):
    """Pad atoms to whole scan blocks; a padded atom has zero weight and velocity."""
    n = int(weights.shape[0])
    blocks = max(1, -(-n // _ATOM_BLOCK))
    pad = blocks * _ATOM_BLOCK - n
    w = np.pad(np.asarray(weights, np.float64), (0, pad))
    u = np.pad(np.asarray(velocities, np.float64), ((0, pad), (0, 0)))
    return (w.reshape(blocks, _ATOM_BLOCK),
            u.reshape(blocks, _ATOM_BLOCK, 3))


def _atom_kernel(q, z, u):
    """``g = x/(z-x)`` and ``dg/d(z^2) = -x/(2 z (z-x)^2)``, ``x = q.u``."""
    import jax.numpy as jnp

    x = (q @ u.T).astype(jnp.complex128)
    moving = x != 0
    denom = jnp.where(moving, z - x, 1.0 + 0.0j)
    g = jnp.where(moving, x / denom, 0.0)
    safe_z = jnp.where(z == 0, 1.0 + 0.0j, z)
    dg = jnp.where(moving & (z != 0), -x / (2.0 * safe_z * denom * denom), 0.0)
    return g, dg


def _density_response(q, z, w_blocks, u_blocks):
    """``sum_s W_s x_s / (z - x_s)``, ``x_s = q.u_s``, one atom block per scan step.

    ``x`` is formed by broadcasting rather than a K = 3 GEMM and the weighted
    atom sum is a reduction, so each block is one fused elementwise-reduce
    kernel that never writes its ``(nq, block)`` table to device memory.  The
    ``g @ w`` form materialized that table per block and was memory bound:
    2.8 s of a Na 8^3 SC map (17 frequencies x 10 draws x 30 blocks).  The
    ``moving``/``denom`` guards are those of :func:`_atom_kernel`.
    """
    import jax
    import jax.numpy as jnp

    def one(total, block):
        w, u = block
        x = (q[:, 0, None] * u[None, :, 0] + q[:, 1, None] * u[None, :, 1]
             + q[:, 2, None] * u[None, :, 2]).astype(jnp.complex128)
        moving = x != 0
        denom = jnp.where(moving, z - x, 1.0 + 0.0j)
        g = jnp.where(moving, x / denom, 0.0)
        return total + jnp.sum(g * w.astype(jnp.complex128)[None, :], axis=1), None

    total, _ = jax.lax.scan(one, jnp.zeros(q.shape[0], jnp.complex128),
                            (w_blocks, u_blocks), unroll=1)
    return total


def _four_current_response(q, z, w_blocks, u_blocks, halfalpha):
    import jax
    import jax.numpy as jnp

    def contract(g, w, u):
        gw = g * w[None, :]
        cc = jnp.sum(gw, axis=1)
        ct = halfalpha * (gw @ u)
        tt = halfalpha ** 2 * jnp.einsum("qs,sa,sb->qab", gw, u, u)
        out = jnp.zeros((q.shape[0], 4, 4), jnp.complex128)
        out = out.at[:, 0, 0].set(cc)
        out = out.at[:, 0, 1:].set(ct)
        out = out.at[:, 1:, 0].set(ct)
        return out.at[:, 1:, 1:].set(tt)

    def one(total, block):
        w, u = block
        g, dg = _atom_kernel(q, z, u)
        return (total[0] + contract(g, w, u), total[1] + contract(dg, w, u)), None

    zero = jnp.zeros((q.shape[0], 4, 4), jnp.complex128)
    total, _ = jax.lax.scan(one, (zero, zero), (w_blocks, u_blocks), unroll=1)
    return total


_DENSITY_PROGRAM = []


def _density_program():
    """The one jitted scalar intraband program (traced once per shape)."""
    if not _DENSITY_PROGRAM:
        import jax
        _DENSITY_PROGRAM.append(jax.jit(_density_response))
    return _DENSITY_PROGRAM[0]


class FermiSurfaceIntraband:
    r"""Velocity atoms of a metal's intraband (Fermi-surface) response.

    ``Pi_intra^{IJ}(q,z) = sum_s W_s (q.u_s)/(z - q.u_s) gamma^I_s gamma^J_s``
    with ``gamma_s = (1, (alpha/2) u_s)``: the anisotropic Lindhard function
    of the computed bands (``docs/theory/metal-q0-head.md`` section 1).
    ``W_s = C w_s/(Omega Nk)`` from the tetrahedron table, so
    ``sum W = N0 = kappa_TF^2/(8 pi)``.  A state keeps ``u = Re v_nn``; a
    state with intraband partners (a multiplet, or any pair with a Fermi-surface share)
    splits into four atoms ``u + sqrt(3) L_s t_j`` of weight ``W_s/4`` with
    ``L_s L_s^T = sum_{m != n} phi_nm Re(v_nm^* v_nm^T)``, its own degenerate
    velocity spread.  That keeps the zeroth, first and second moments
    exact state by state, so ``sum W u u^T`` is the Drude tensor of
    ``gw.qsgw_head.head_drude_tensor_sharded`` and both limits hold:
    ``-N0`` static, ``q.D.q/z^2`` for ``|z| >> q u``.  Both metallic heads
    (``gw.qsgw_head``, ``gw.photon_direct_head``) take their intraband
    response here.  Atoms are replicated: bytes ``O(4 N_FS)``.
    """

    def __init__(self, surface_kn, velocity_diag, spread_kn, drude_tensor, *,
                 capacity, cell_volume, nk_tot):
        surface = np.asarray(surface_kn, dtype=np.float64)
        diag = np.asarray(velocity_diag, dtype=np.float64)
        spread = np.asarray(spread_kn, dtype=np.float64)
        nk, nb = surface.shape
        if diag.shape[:2] != (3, nk) or diag.shape[2] < nb:
            raise ValueError(
                f"velocity diagonal {diag.shape} does not cover the surface table {surface.shape}")
        if spread.shape[:2] != (nk, diag.shape[2]) or spread.shape[2:] != (3, 3):
            raise ValueError(f"velocity spread {spread.shape} does not match ({nk},{diag.shape[2]},3,3)")
        scale = float(capacity) / (float(nk_tot) * float(cell_volume))
        k_idx, n_idx = np.nonzero(surface > 0.0)
        weights = scale * surface[k_idx, n_idx]
        velocity = diag[:, k_idx, n_idx].T
        spread = 0.5 * (spread[k_idx, n_idx] + np.swapaxes(spread[k_idx, n_idx], 1, 2))
        lam, vec = np.linalg.eigh(spread)
        scale_d = max(float(np.max(np.abs(np.real(drude_tensor)))), 1e-300)
        if lam.size and float(np.min(lam)) * float(np.max(weights, initial=0.0)) < -1e-9 * scale_d:
            raise ValueError(
                "GATE metal_intraband_spread: a state's intraband velocity spread is not "
                f"positive semidefinite (min eigenvalue {float(np.min(lam)):.3e})")
        factor = vec * np.sqrt(np.maximum(lam, 0.0))[:, None, :]
        split = np.max(lam, axis=1, initial=0.0) > 0.0 if lam.size else np.zeros(0, bool)
        atoms_w = [weights[~split]]
        atoms_u = [velocity[~split]]
        if np.any(split):
            offsets = np.sqrt(3.0) * np.einsum("sab,jb->sja", factor[split], _TETRAHEDRON_UNIT)
            atoms_w.append(np.repeat(weights[split] / 4.0, 4))
            atoms_u.append((velocity[split][:, None, :] + offsets).reshape(-1, 3))
        self.weights = np.concatenate(atoms_w)
        self.velocities = np.concatenate(atoms_u)
        self.n_states = int(weights.size)
        self.n_split = int(np.count_nonzero(split))
        self.dos = float(np.sum(self.weights))
        self.drude_tensor = np.asarray(drude_tensor, dtype=np.complex128)
        self.drude = np.real(self.drude_tensor)
        moment = np.einsum("s,sa,sb->ab", self.weights, self.velocities, self.velocities)
        error = float(np.max(np.abs(moment - self.drude)))
        if error > 1e-8 * scale_d:
            raise ValueError(
                "GATE metal_intraband_moments: velocity atoms miss the Drude tensor by "
                f"{error:.3e} (scale {scale_d:.3e}); the pair split of the atoms and of D differ")
        self.moment_error = error
        #: The phi -> 0 Drude tensor (exact multiplets only), set by the builder.
        self.physical_drude = None
        self._blocks = _intraband_blocks(self.weights, self.velocities)

    def describe(self) -> str:
        return (f"{self.n_states} Fermi-surface states, {self.n_split} split by their "
                f"intraband partners, {self.weights.size} velocity atoms; "
                f"|sum W u u - D| = {self.moment_error:.2e}")

    def density_response(self, q_cart, z):
        """Scalar ``chi_intra(q,z)`` at every row of ``q_cart (nq,3)``."""
        import jax.numpy as jnp
        return _density_program()(
            jnp.asarray(q_cart, jnp.float64), jnp.asarray(complex(z), jnp.complex128),
            jnp.asarray(self._blocks[0]), jnp.asarray(self._blocks[1]))

    def device_operands(self):
        """Replicated ``(w_blocks, u_blocks)`` for jitted callers."""
        import jax.numpy as jnp
        return jnp.asarray(self._blocks[0]), jnp.asarray(self._blocks[1])


def four_current_intraband_response(q, z, w_blocks, u_blocks, halfalpha):
    """``(Pi_intra, d Pi_intra / d z^2)``, each ``(nq,4,4)``, from device atoms.

    Traceable (the caller jits); ``z = 0`` returns ``g = -1`` per moving atom
    and a zero derivative.  See :class:`FermiSurfaceIntraband`.
    """
    return _four_current_response(q, z, w_blocks, u_blocks, halfalpha)


__all__ = ["tetrahedron_delta_weights", "star_symmetrize_weights",
           "metal_head_surface_weights", "intraband_pair_fraction",
           "FermiSurfaceIntraband", "four_current_intraband_response"]
