"""Head-excluded W densification — the coarse→fine head channel (C1).

WHY THIS MODULE EXISTS
----------------------
BerkeleyGW never interpolates a divergent object.  ``kernel.x`` writes a
divergence-STRIPPED head, wing and body to ``bsemat.h5``
(``mtxel_kernel.f90:525-556``; for a semiconductor the head is stored as
literally ``1.0``) and ``intkernel`` restores the singular factors at
assembly time, per fine q (``intkernel.f90:1103-1145``).  The rationale is
stated twice in that source, identically:

    "What we actually interpolate is only the head matrix elements (i.e.
     excluding the 1/q² factor), the wing part that does not diverge (i.e.
     multiplied by |q|), and the complete body element."

LORRAX's coarse→fine densifier (``bse.bse_io.make_w_densifier``) inverse-FFTs
``W_q`` to the coarse R-lattice, zero-pads R and FFTs back — exact band-limited
trigonometric interpolation.  Until this module existed, its operand was the
POST-injection tile ``W_body0(q) + Δ·δ_{q,0}``, with
``Δ = (whead/Ω)·conj(g₀)⊗g₀`` — a Kronecker delta carrying a ~2600 meV
geometric prefactor on the Si anchor deck.  A Kronecker delta is the one
function shape a band-limited interpolant cannot represent: its interpolant is
a Dirichlet kernel, which reproduces the coarse samples exactly and between
them oscillates in sign across the whole fine zone.  Two independent defects
follow.  (i) Ringing: a fraction of that prefactor is deposited at fine
q-points that should carry none of it, including at the zone boundary.
(ii) Missing physics: fine q-points inside the coarse Γ cell should each carry
a LARGE head, because W's head diverges as ``v(q)/ε`` — screening divides the
pole by ε∞, it does not remove it — and no smooth interpolant between Γ's
cell-averaged value and its neighbours produces a 1/q² rise.  So the densified
kernel under-binds excitons near the zone centre, and the error GROWS with the
densification factor instead of shrinking.

WHAT C1 DOES
------------
Split the Γ head off BEFORE the densifier, densify only the body, and
re-attach per fine q::

    W_fine(q) = densify(W_body-only)(q)  +  S_fine(q) · conj(g₀) ⊗ g₀ / Ω

    S_fine(Γ)          = ⟨ v/(1 − v qᵀS_cart q) ⟩ over the FINE mini-BZ cell
    S_fine(q ∈ Γ_c, ≠0) =   v(q)/(1 − v(q) qᵀS_cart q)   evaluated pointwise
    S_fine(q ∉ Γ_c)     =   0

where ``Γ_c`` is the Voronoi cell of Γ with respect to the COARSE q-lattice.
Both expressions come from ONE integrand — the one ``vcoul.Bulk3D.q0_average``
already evaluates — averaged at Γ and evaluated pointwise elsewhere.  Nothing
is derived anew and nothing is fitted.

SHAPE FROM THE INTEGRAND, SCALE FROM THE INJECTED HEAD
------------------------------------------------------
What is actually built is ``S_fine(q) = whead · S_raw(q) / S_raw(Γ_coarse)``:
the q-DEPENDENCE comes from the integrand above, and the overall SCALE is
pinned to ``whead`` — the very scalar the loader injects at q = 0 today.  This
is one multiplication, and it is not a fit; it is what makes the on-grid
identity STRUCTURAL rather than contingent.  Two reasons it has to be there.

*``q0_average`` is a Monte-Carlo estimator.*  It is a scrambled-Sobol average
over the Voronoi cell, deterministic given its options but not a closed form.
Recomputing it at the coarse grid reproduces the restart's ``whead`` bit-for-bit
only if ``nsamples``, ``method``, ``qmc_reps``, ``analytic_sphere`` AND the
scipy that supplies the generator all match what the GW run used.  Pinning the
scale to the injected value makes the identity independent of every one of
those, while the ratio ``whead / S_raw(Γ_coarse)`` — which the wiring logs —
becomes a free PROVENANCE CHECK on exactly that agreement.

*Decks override the head.*  ``vhead`` / ``whead_0freq`` in ``cohsex.in`` are a
cross-code validation knob, and the Si anchor deck uses it
(``whead_0freq = 150.3956``).  On such a deck the injected head is an external
pin and the integrand's own value is not the authority on its magnitude; the
integrand is still the authority on how it varies with q, which is all C1 asks
of it.

Because the anchor is applied as ``whead · (S_raw(q) / S_raw(Γ_coarse))``, the
``fine == coarse`` case divides a float by ITSELF — exactly ``1.0`` — so the
re-attached array is ``[whead at Γ, 0 elsewhere]``, which is today's ``Δ`` to
the last bit.  That is the on-grid bit-identity, obtained by construction.

The restriction to ``Γ_c`` is not a scoping choice, it is what stops a double
count.  At q ≠ 0 LORRAX performs NO head/wing/body separation: the
``argmin |q+G|`` slot sits inside ``V_μν`` and is screened by the full solve,
so every coarse tile at q ≠ 0 already carries its own head, generated by the
inversion.  The only head that was ever removed and re-attached as a scalar is
Γ's, and ``Γ_c`` is exactly the region the removed object was responsible for.
Fine q that coincide with coarse q ≠ 0 points are the centres of their own
coarse cells, hence outside ``Γ_c``, hence get nothing added — which is why the
scheme is consistent at the points where both descriptions are available.

HERMITICITY IS STRUCTURAL, NOT CHECKED
--------------------------------------
``S_fine(q)`` is a REAL scalar (:func:`head_scalar_pointwise` and
:func:`gamma_cell_head_scalar` both return float64) and the update is a real
multiple of the rank-one Hermitian projector ``conj(g₀)⊗g₀`` added to a
Hermitian body.  Hermitian by construction, exactly as the loader's own
injection is.  Reciprocity ``W_q = conj(W_{−q})`` survives because ``S_fine``
depends on q only through ``v(q)`` and ``qᵀSq``, both even.  The rule that
keeps this safe is the one the rejected two-tile shape established: **do not
re-solve; only split and re-attach.**  Nothing here inverts anything, so no
non-congruent product can be formed.

THE ONE APPROXIMATION, NAMED
----------------------------
For fine q-points off the coarse grid the exact projector is
``g₀(q) = ζ̃_{q,μ}(G_q)``, and ζ exists only on the coarse grid.  This stage
FREEZES the projector at ``g₀(Γ)`` for every fine point inside the coarse Γ
cell.  That is an O(q·L) relative error on a term of magnitude O(1/q²) —
controlled inside the cell and irrelevant outside it, and exactly the regime
``THEORY_LT_HEAD_TENSOR.md`` §3.3 identifies as the cell average's validity
domain.  The exact alternatives (``psp/finite_q_head_interp.compute_g_mu_at_q``,
or ``jax.jacfwd`` on the closed-form b26p ζ̃ evaluator) are a later stage.
The freeze enters at exactly one place: :func:`attach_head_channel`, which
takes ONE ``g0`` pair and broadcasts it over every fine q.

WHAT THIS MODULE DOES NOT DO
----------------------------
* It does not modify the q=0 full-expression average.  ``Bulk3D.q0_average``
  is CALLED here, at a different cell size, and never touched — that estimator
  is ratified and is better than BerkeleyGW's 3D product-of-averages.
* It adds no wing term.  The Γ-cell wing second moment ``N_ab = ⟨S q_a q_b⟩``
  is staged separately, measurement-first, because it moves the 0.41 meV
  cross-code parity.
* It is bulk-3D only.  The slab twin needs ``slab_2d.q0_average`` and a
  different trace identity; :func:`build_fine_head_scalars` refuses any other
  ``sys_dim`` rather than silently using the 3D pole.
"""
from __future__ import annotations

import numpy as np

from ffi import _services      # noqa: F401  (path bootstrap for ``vcoul``)

_services.ensure_on_path()

import vcoul                                                  # noqa: E402
from vcoul import CoulombGeometry                             # noqa: E402
from vcoul import wrap_points_to_voronoi                      # noqa: E402

__all__ = [
    "head_scalar_pointwise",
    "gamma_cell_head_scalar",
    "fine_q_cart",
    "coarse_gamma_cell_weights",
    "build_fine_head_scalars",
    "head_channel_zone_average",
    "attach_head_channel",
    "EIGHT_PI",
]

#: ``v(q) = 8π/|q|²`` in Ry·bohr³ — the bare 3D Coulomb, NOT divided by Ω.
#: The same convention ``vcoul.Bulk3D._vq_isotropic`` and the restart's
#: ``whead`` use; the 1/Ω is applied once, at :func:`attach_head_channel`,
#: exactly where ``head_correction._head_rank1_scalars`` applies it today.
EIGHT_PI = 8.0 * np.pi

#: Voronoi replica half-width used to reduce a fine q to its SHORTEST
#: representative in the first BZ.  The fftfreq fractional box is not the
#: Voronoi cell on a skewed lattice, so the nearest lattice point can be a
#: replica away (BGW's ``ncell = 3`` exists for the same reason); 2 covers
#: every cell in the tree with margin.
_BZ_WRAP_NMAX = 2


def head_scalar_pointwise(q_cart, S_cart) -> np.ndarray:
    """``S(q) = v(q) / (1 − v(q) qᵀS q)`` — the ratified integrand at a point.

    THE SAME EXPRESSION ``vcoul.Bulk3D.q0_average`` AVERAGES.  There, on a
    Voronoi draw ``rq``::

        vq = 8π/|rq|² ;  qSq = einsum('qi,ij,qj->q', rq, S, rq)
        wcoul0 = mean( vq / (1 − vq·qSq) )

    Here the same two lines run on ONE q and the mean is not taken.  Because
    ``v(q)|q|² = 8π`` identically in 3D bulk, ``v(q)·qᵀSq = 8π q̂ᵀS q̂`` is a
    pure ANGULAR quantity: the denominator depends only on the direction of q,
    and the whole radial divergence lives in the numerator.  That is the
    statement "screening divides the pole by ε∞, it does not remove it", and
    it is why the head cannot be interpolated.

    Parameters
    ----------
    q_cart : array_like, shape (n, 3) or (3,)
        Cartesian q in 1/bohr (``blat`` folded in, i.e. the
        :class:`~vcoul.CoulombGeometry` row convention: ``q_frac @ bvec``).
        ``q = 0`` is refused — the pointwise form does not exist there, and
        the caller wants :func:`gamma_cell_head_scalar` instead.
    S_cart : array_like, shape (3, 3)
        The canonical CARTESIAN q²-coefficient tensor fixed by
        ``docs/theory/s-tensor-convention.md``.  Complex is accepted (the
        ω-dependent S(ω) is complex in general); the RESULT is returned real,
        see below.

    Returns
    -------
    numpy.ndarray, float64, shape (n,) or ()
        ``S(q)`` in Ry·bohr³, REAL.  Realness is not an approximation at the
        static head this stage consumes — ``S_cart(ω=0, η=0)`` is real
        symmetric, so the integrand is real — but it is TAKEN rather than
        assumed, because a real scalar is what makes the rank-one update
        Hermitian by construction (module docstring).  A non-negligible
        imaginary part is a caller error and raises rather than being dropped.
    """
    q_in = np.asarray(q_cart, dtype=np.float64)
    if q_in.ndim == 0 or q_in.shape[-1] != 3:
        raise ValueError(f"head_scalar_pointwise: q_cart must be (...,3); "
                         f"got {np.shape(q_cart)}")
    lead = q_in.shape[:-1]
    q = q_in.reshape(-1, 3)
    S = np.asarray(S_cart, dtype=np.complex128)
    if S.shape != (3, 3):
        raise ValueError(f"head_scalar_pointwise: S_cart must be (3,3); "
                         f"got {S.shape}")
    q2 = np.einsum("qi,qi->q", q, q)
    if np.any(q2 <= 0.0):
        raise ValueError(
            "head_scalar_pointwise: q = 0 has no pointwise value — v(q) "
            "diverges there.  The Γ cell's value is the CELL AVERAGE "
            "⟨v/(1 − v qᵀSq)⟩ over the fine mini-BZ; call "
            "gamma_cell_head_scalar() for it.  (This refusal is the whole "
            "point of the split: the object at Γ is an integral, not a "
            "sample.)")
    vq = EIGHT_PI / q2
    qSq = np.einsum("qi,ij,qj->q", q, S, q)
    val = vq / (1.0 - vq * qSq)
    _refuse_complex(val, "head_scalar_pointwise")
    return np.real(val).reshape(lead)


def _refuse_complex(val, where: str, rtol: float = 1e-10) -> None:
    """Refuse a head scalar with a physically meaningful imaginary part.

    The rank-one update is Hermitian ONLY because its coefficient is real.
    A complex coefficient makes ``s·conj(g₀)⊗g₀`` non-Hermitian by exactly
    ``2i·Im(s)·conj(g₀)⊗g₀`` — which is the deliberate red twin the
    Hermiticity gate trips on.  Dropping the imaginary part silently would
    make that twin invisible, so it is a refusal, not a cast.
    """
    v = np.asarray(val)
    scale = float(np.max(np.abs(v))) if v.size else 0.0
    imag = float(np.max(np.abs(np.imag(v)))) if v.size else 0.0
    if scale > 0.0 and imag > rtol * scale:
        raise ValueError(
            f"{where}: head scalar has |Im| = {imag:.6e} against "
            f"|S| = {scale:.6e} (rel {imag / scale:.3e} > {rtol:.0e}).  A "
            f"complex head coefficient breaks Hermiticity of the rank-one "
            f"update by 2i·Im(S)·conj(g0)⊗g0.  The static (ω=0, η=0) head "
            f"this stage consumes is real; a complex one means S_cart came "
            f"from a finite η or a finite ω and this path has no ruling for "
            f"it.")


def gamma_cell_head_scalar(geometry: CoulombGeometry, kgrid, S_cart, *,
                           analytic_sphere: bool = False,
                           nsamples: int = 2**18,
                           method: str = "auto",
                           qmc_reps: int = 10) -> float:
    """``⟨ v/(1 − v qᵀS q) ⟩`` over the mini-BZ Voronoi cell of ``kgrid``.

    A THIN CALL, NOT A REIMPLEMENTATION.  This is ``vcoul.Bulk3D.q0_average``
    with the caller's ``kgrid`` — the ratified q=0 full-expression average,
    consumed at a different cell size and not modified.  Passing the FINE grid
    is the whole of C1's Γ treatment; passing the COARSE grid reproduces the
    scalar the loader injects today, which is what makes the on-grid identity
    free and the provenance check possible.

    ``analytic_sphere`` is the deck's ``head_minibz_average`` key: it adds the
    Baldereschi-Tosatti analytic sphere term and widens the Voronoi fold to
    BGW's ``ncell = 3``.  It MUST match whatever the GW run used, or the
    coarse-grid call will not reproduce the restart's ``whead`` and the
    provenance check will say so.

    The estimator defaults are ``gw.vcoul.compute_q0_averages``'s, NOT
    ``vcoul.Bulk3D.q0_average``'s — in particular ``method="auto"`` rather
    than ``"sobol"``.  That is deliberate: the GW run reached the estimator
    through ``compute_q0_averages``, so matching its defaults is what makes
    the provenance ratio a check on the PHYSICS rather than on which wrapper
    each side happened to call.  (With scipy present the two resolve to the
    same scrambled-Sobol draw anyway; without it, ``"auto"`` announces the
    uniform fallback where ``"sobol"`` would refuse, and reproducing the run
    matters more here than refusing.)

    Returns
    -------
    float
        Ry·bohr³, real (see :func:`_refuse_complex`).
    """
    _, wcoul0 = vcoul.Bulk3D().q0_average(
        geometry, tuple(int(s) for s in kgrid), S_cart=S_cart,
        nsamples=nsamples, method=method, qmc_reps=qmc_reps,
        analytic_sphere=analytic_sphere,
    )
    val = complex(wcoul0)
    _refuse_complex(np.asarray([val]), "gamma_cell_head_scalar")
    return float(val.real)


def fine_q_cart(bvec, fine_grid) -> np.ndarray:
    """Cartesian q at every point of ``fine_grid``, in FFT index order.

    The k axes of ``W_q`` are FFT axes, so index ``i`` on an axis of length
    ``n`` is the fractional coordinate ``fftfreq(n)[i]`` — ``i/n`` for the
    first half and ``(i−n)/n`` for the second.  Getting that wrong puts the
    head on the wrong side of the zone and is invisible in any norm that does
    not resolve q, which is why it is spelled once, here.

    ``q_cart = q_frac @ bvec`` is the ROW convention
    (:func:`vcoul.minibz.minibz_frac_to_cart`); ``bvec`` rows are the
    Cartesian reciprocal vectors with ``blat`` folded in.  The transposed
    spelling is not a fundamental domain of the lattice and shipped as a
    three-month bias in the 3D body head (fixed 358bb0b).

    THE RESULT IS WRAPPED TO THE FIRST BZ, and that is not cosmetic: the
    fftfreq box ``[−1/2, 1/2)`` in FRACTIONAL coordinates is not the Voronoi
    cell of a skewed reciprocal lattice, so its Cartesian image contains
    points that are not the shortest representative of their BZ point.  Since
    the whole head channel is ``8π/|q|²``, using a non-shortest representative
    would evaluate the pole at the wrong radius.  ``wrap_points_to_voronoi``
    is the tree's one spelling of that reduction.

    Returns
    -------
    numpy.ndarray, shape ``(nfx, nfy, nfz, 3)``, float64
    """
    b = np.asarray(bvec, dtype=np.float64)
    if b.shape != (3, 3):
        raise ValueError(f"fine_q_cart: bvec must be (3,3) rows; got {b.shape}")
    nfx, nfy, nfz = (int(s) for s in fine_grid)
    frac = np.stack(np.meshgrid(np.fft.fftfreq(nfx), np.fft.fftfreq(nfy),
                                np.fft.fftfreq(nfz), indexing="ij"), axis=-1)
    q_raw = (frac @ b).reshape(-1, 3)
    q = np.asarray(wrap_points_to_voronoi(q_raw, b, nmax=_BZ_WRAP_NMAX),
                   dtype=np.float64)
    return q.reshape(nfx, nfy, nfz, 3)


def coarse_gamma_cell_weights(q_cart, coarse_grid, fine_grid) -> np.ndarray:
    """How much of each fine q lies in the Γ Voronoi cell of the COARSE lattice.

    The coarse q-lattice ``Λ_c`` is generated by ``b_i / nc_i``, and its Γ
    Voronoi cell is exactly the region the coarse Γ tile's head scalar was
    responsible for — so this mask is C1's re-attachment domain.

    THE PARTITION IS EXACT, BY CONSTRUCTION RATHER THAN BY A TOLERANCE, and
    that is worth the paragraphs because two obvious implementations are both
    wrong.

    *Not a geometric predicate.*  Asking "is ``|q| ≤ |q − K|`` for every coarse
    lattice vector K" needs a tie rule, and ties are not rare, they are
    generic: an EVEN densification factor (``m = 2``, the commonest case) puts
    fine q exactly on the coarse cell boundary at every face centre.  A first
    cut delegated the tie to ``wrap_points_to_voronoi``'s ``argmin``, and on
    skewed cells that kept 9 points where 8 were due (fcc, 3×3×3 → 6×6×6) and
    18 where 8 were due (hexagonal) — an over-count no norm-based check would
    have caught, because the extra points carry small heads.

    So membership is decided by COSET ARITHMETIC on the indices, where it is
    exact integer bookkeeping.  In fine-index units the fine q-lattice is
    ``Z³`` and ``Λ_c`` is ``m_x Z ⊕ m_y Z ⊕ m_z Z`` with ``m_a = nf_a / nc_a``
    (the full lattice ``Λ`` is ``nf_a Z``, already contained).  Hence the
    ``Λ_c``-cosets of the fine grid are labelled EXACTLY by the index residues
    ``(i mod m_x, j mod m_y, k mod m_z)``: there are ``m_x m_y m_z`` of them,
    no more and no less.  Within each coset the Voronoi representative is, by
    the definition of a Voronoi cell, the member of smallest ``|q|`` — and the
    minimum over the full coset is attained inside the first BZ, because
    ``Λ ⊂ Λ_c`` makes the ``Λ_c`` cell the smaller one, so searching the fine
    grid's first-BZ representatives is searching the whole coset.

    *And not one representative per coset either.*  Picking a single member
    when the minimum is degenerate breaks a symmetry the kernel depends on.
    The map ``q → −q`` sends coset ``c`` to coset ``−c`` bijectively and
    preserves ``|q|``, so when each minimum is UNIQUE the chosen sets are
    exact mirror images and the head channel comes out even in q — which is
    what carries reciprocity ``W_q = conj(W_{−q})`` through the re-attachment.
    When the minimum is DEGENERATE, any lowest-index tie-break keeps ``q`` and
    discards ``−q``, and the channel stops being even.  That is not
    hypothetical: a 3×3×2 → 9×9×4 hexagonal case fails it outright, because
    the pair ``k = ±1`` on the doubled axis is exactly degenerate.

    The rule that is both exact and even is to SHARE: every member of a
    degenerate minimum gets weight ``1/k``.  Physically it is the obvious
    reading — those q sit exactly ON the coarse cell boundary, so they belong
    half (or 1/k) to the Γ cell and the rest to its neighbours — and
    arithmetically the total weight is still one per coset, hence
    ``m_x m_y m_z`` for the grid, so the sum rule is untouched.  With no ties
    every weight is 1.0 and this is identical to the one-per-coset rule.

    The total weight is a free exact invariant, and
    :func:`build_fine_head_scalars` asserts it.  (It is exact to float
    addition rather than bitwise for odd tie multiplicities — ``1/3`` thrice
    does not sum to 1.0 — so the assertion is a tolerance there and only
    there; the ``m = 1`` case that the on-grid identity rests on has a single
    coset with a single member and weight exactly 1.0.)

    Parameters
    ----------
    q_cart : array_like, shape ``(nfx, nfy, nfz, 3)``
        From :func:`fine_q_cart` — already reduced to the first BZ.
    coarse_grid, fine_grid : tuple[int, int, int]

    Returns
    -------
    numpy.ndarray, float64, shape ``(nfx, nfy, nfz)``
        Weights in [0, 1] summing to ``∏(nf_a/nc_a)``.
    """
    q = np.asarray(q_cart, dtype=np.float64)
    fg = tuple(int(s) for s in fine_grid)
    cg = tuple(int(s) for s in coarse_grid)
    if q.shape != (*fg, 3):
        raise ValueError(f"coarse_gamma_cell_weights: q_cart {q.shape} does "
                         f"not match fine_grid {fg}")
    m = tuple(f // c for f, c in zip(fg, cg))
    idx = np.indices(fg)
    # Flat coset label from the index residues — the exact Λ_f/Λ_c labelling.
    coset = ((idx[0] % m[0]) * m[1] + (idx[1] % m[1])) * m[2] + (idx[2] % m[2])
    n_coset = m[0] * m[1] * m[2]
    flat_coset = coset.reshape(-1)
    flat_q2 = np.einsum("xyza,xyza->xyz", q, q).reshape(-1)

    # Per-coset minimum of |q|², then EVERY member attaining it.  The
    # degeneracy test is a scaled tolerance rather than ``==`` because the two
    # members of a ± pair reach the same norm through different float sums
    # (the Cartesian q come from a matmul), so an exact comparison would
    # declare a genuine tie broken at the 1e-16 level and silently reinstate
    # the evenness bug this weighting exists to remove.
    qmin = np.full(n_coset, np.inf)
    np.minimum.at(qmin, flat_coset, flat_q2)
    scale = float(np.max(flat_q2)) or 1.0
    tied = flat_q2 <= qmin[flat_coset] + 1e-12 * scale
    mult = np.bincount(flat_coset[tied], minlength=n_coset).astype(np.float64)
    if np.any(mult <= 0):
        raise AssertionError(
            f"coarse_gamma_cell_weights: {int(np.sum(mult <= 0))} of "
            f"{n_coset} cosets have no representative — the index arithmetic "
            f"is wrong, not the geometry.")
    w = np.zeros(flat_q2.size, dtype=np.float64)
    w[tied] = 1.0 / mult[flat_coset[tied]]
    return w.reshape(fg)


def build_fine_head_scalars(
    geometry: CoulombGeometry,
    coarse_grid,
    fine_grid,
    S_cart,
    *,
    head_ref: float,
    gamma_ref: float,
    ref_grid,
    sys_dim=None,
    analytic_sphere: bool = False,
    nsamples: int = 2**18,
    method: str = "auto",
    qmc_reps: int = 10,
    gamma_cell: str = "fine",
) -> np.ndarray:
    """The head-channel scalar ``S_fine(q)`` at every fine q.  THE C1 OBJECT.

    ``S_fine(Γ)`` is the cell average over the FINE mini-BZ; ``S_fine(q)`` for
    the other fine q inside the coarse Γ cell is the pointwise integrand; every
    fine q outside the coarse Γ cell gets ZERO, because the coarse tile there
    already carries its own head (module docstring).  All three are scaled by
    ``head_ref / gamma_ref`` — shape from the integrand, scale from the head
    the loader actually injects (module docstring, "SHAPE FROM THE INTEGRAND,
    SCALE FROM THE INJECTED HEAD").

    Parameters
    ----------
    geometry : CoulombGeometry
        Cartesian reciprocal ROWS (1/bohr) and Ω (bohr³).
    coarse_grid, fine_grid : tuple[int, int, int]
        ``fine`` must be a positive multiple of ``coarse`` on every axis —
        the same containment the densifier requires (coarse BZ ⊂ fine BZ).
    S_cart : array_like, shape (3, 3)
    head_ref, gamma_ref, ref_grid
        THE ANCHOR PAIR AND THE GRID IT BELONGS TO.  ``head_ref`` is the head
        scalar the loader actually injects (Ry·bohr³ — the restart's
        ``whead[0]``, or the deck's ``whead_0freq`` override, whichever
        ``_resolve_head_params`` chose); ``gamma_ref`` is
        ``gamma_cell_head_scalar(geometry, ref_grid, S_cart, ...)``, what the
        integrand itself says that same cell average is.  Their ratio is a
        free PROVENANCE CHECK (≈ 1 when the restart's head and this ``S_cart``
        came from the same GW run) and the caller logs it.

        ``ref_grid`` is the grid ``head_ref`` was measured on, and the two
        shipping paths differ in it, which is the whole reason it is an
        argument rather than assumed:

        * ``bse_k_grid`` — a COARSE restart densified up.  ``ref_grid`` is the
          coarse grid, so with ``fine == coarse`` the Γ entry is ``gamma_ref``
          divided by itself and the result is exactly ``head_ref``.
        * ``--w-coarse-grid`` — a NATIVE FINE restart decimated and densified
          back.  ``ref_grid`` is the fine grid, so C1's Γ entry reproduces the
          native restart's own ``whead`` EXACTLY.  That is not a coincidence
          to be checked, it is the identity the harness needs to be honest:
          the arm that simulates a coarse W must put back the head the fine
          run really had.
    sys_dim : optional
        Refused unless bulk 3D.  The slab twin is a separate stage: in 2D the
        head is a ``|q|`` cusp rather than a ``1/q²`` pole and the estimator
        is ``slab_2d.q0_average``, so silently running the 3D pole on a slab
        would be a wrong number with no shape error.
    analytic_sphere, nsamples, method, qmc_reps
        Passed to :func:`gamma_cell_head_scalar`; must match the GW run.
    gamma_cell : {"fine", "coarse"}
        ``"fine"`` is C1.  ``"coarse"`` is THE RED TWIN the design names:
        re-attach at the coarse mini-BZ scale instead of the fine one.  It is
        INVISIBLE when the grids are equal and breaks the head sum rule
        everywhere else, which is exactly the shape of the offset-versus-
        momentum twin the moment tensor's trace identity exists to catch.  It
        is exposed here — rather than hidden in a test — so the false arm runs
        the SHIPPED code path with one argument changed, not a reimplementation
        of it.

    Returns
    -------
    numpy.ndarray, float64, shape ``fine_grid``
        Ry·bohr³.  Divide by Ω at attachment, not here.
    """
    if gamma_cell not in ("fine", "coarse"):
        raise ValueError(f"build_fine_head_scalars: gamma_cell must be 'fine' "
                         f"(C1) or 'coarse' (the red twin); got {gamma_cell!r}")
    _refuse_non_bulk(sys_dim)
    cg = tuple(int(s) for s in coarse_grid)
    fg = tuple(int(s) for s in fine_grid)
    for a, (f, c) in enumerate(zip(fg, cg)):
        if c <= 0 or f <= 0 or f % c != 0:
            raise ValueError(
                f"build_fine_head_scalars axis {a}: fine {f} must be a "
                f"positive multiple of coarse {c} (coarse BZ ⊂ fine BZ).")

    q = fine_q_cart(geometry.bvec, fg)                        # (fx,fy,fz,3)
    weight = coarse_gamma_cell_weights(q, cg, fg)             # (fx,fy,fz)

    # FREE EXACT INVARIANT.  The weight in the coarse Γ cell totals the index
    # [Λ_f : Λ_c] = ∏(nf_a/nc_a) — no lattice dependence, and no dependence on
    # how many boundary q happened to tie.  Asserted rather than trusted
    # because an over-count deposits extra heads at q the coarse tiles already
    # screen, and the resulting error is small enough per point to hide in any
    # norm.
    n_expect = 1
    for f, c in zip(fg, cg):
        n_expect *= f // c
    total = float(np.sum(weight))
    if abs(total - n_expect) > 1e-12 * n_expect:
        raise AssertionError(
            f"build_fine_head_scalars: the coarse Γ cell holds weight "
            f"{total!r} but [Λ_f : Λ_c] = {n_expect} for {cg} → {fg}.  The "
            f"re-attachment domain is not a fundamental domain of the coarse "
            f"lattice, so the head channel would be double-counted (or "
            f"dropped).")
    if weight[0, 0, 0] != 1.0:
        raise AssertionError(
            f"build_fine_head_scalars: Γ carries weight {weight[0, 0, 0]!r}, "
            f"not 1.0.  Γ is the unique zero-norm point of its coset, so any "
            f"other weight means the index convention slipped (the k axes are "
            f"FFT axes and Γ is index (0,0,0)).")

    gamma_r = float(gamma_ref)
    if not np.isfinite(gamma_r) or gamma_r == 0.0:
        raise ValueError(
            f"build_fine_head_scalars: gamma_ref = {gamma_ref!r} is not a "
            f"usable scale.  It must be the integrand's own cell average on "
            f"ref_grid, gamma_cell_head_scalar(geometry, ref_grid, S_cart).")
    rg = tuple(int(s) for s in ref_grid)

    S = np.zeros(fg, dtype=np.float64)
    # Every fine q inside the coarse Γ cell EXCEPT Γ itself: the pointwise
    # integrand, times its boundary-sharing weight.
    off_gamma = weight > 0.0
    off_gamma[0, 0, 0] = False
    if np.any(off_gamma):
        S[off_gamma] = (head_scalar_pointwise(q[off_gamma], S_cart)
                        * weight[off_gamma])

    # Γ: the cell average over the FINE cell (C1) or the COARSE one (the red
    # twin).  When that grid IS ``ref_grid`` the caller's ``gamma_ref`` is
    # reused rather than re-estimated — the estimator is a Monte-Carlo average
    # and calling it twice with the same options gives the same float, but
    # reusing makes the cancellation below EXACT by construction instead of by
    # determinism, and it is one fewer 2.6M-sample integral per run.
    gamma_grid = fg if gamma_cell == "fine" else cg
    S[0, 0, 0] = (gamma_r if gamma_grid == rg else gamma_cell_head_scalar(
        geometry, gamma_grid, S_cart, analytic_sphere=analytic_sphere,
        nsamples=nsamples, method=method, qmc_reps=qmc_reps))

    # THE ANCHOR, and the reason it is spelled as a ratio.  When the Γ entry
    # IS ``gamma_r``, ``S / gamma_r`` is exactly 1.0 there and the result is
    # exactly ``head_ref`` — a float divided by itself, not a tolerance.  The
    # other spelling, ``(head_ref/gamma_r) * S``, is NOT exact and would have
    # made the on-grid identity a ~1e-16 claim instead of a bitwise one.
    return float(head_ref) * (S / gamma_r)


def _refuse_non_bulk(sys_dim) -> None:
    """Bulk 3D only, said out loud.  See ``build_fine_head_scalars``."""
    if sys_dim is None:
        return
    from vcoul import SysDim
    try:
        sd = SysDim(int(sys_dim))
    except (TypeError, ValueError):
        raise ValueError(f"head_densify: sys_dim={sys_dim!r} invalid; "
                         f"expected 0 (box), 2 (slab) or 3 (bulk).")
    if sd is not SysDim.BULK_3D:
        raise NotImplementedError(
            f"head_densify: C1's head channel is the 3D bulk pole "
            f"v(q) = 8π/|q|², and this run is sys_dim={sd.name}.  In 2D the "
            f"head is a |q| CUSP, the estimator is slab_2d.q0_average, and "
            f"the trace identity that gates it is a different closed form — "
            f"so running the 3D expression here would be a wrong number with "
            f"no shape error to catch it.  The slab twin is a separate stage; "
            f"until it lands, use w_head_densify = legacy on this deck and "
            f"read the coarse→fine result knowing the Γ head is interpolated.")


def head_channel_zone_average(S_grid) -> float:
    """``(1/N_q) Σ_q S(q)`` — the head channel's zone average.  THE SUM RULE.

    This number is a property of the material and the cell, not of the grid.
    Its exact statement, and the two arms that gate it:

    * **Exact arm.** With ``fine == coarse`` the only fine q inside the coarse
      Γ cell IS Γ, and the fine mini-BZ cell IS the coarse one, so
      ``head_channel_zone_average(S_fine) == S_coarse / N_c`` EXACTLY — the
      same float, not a tolerance.
    * **Refinement arm.** With ``fine = m·coarse`` the Γ cell is integrated
      exactly (it is a cell average) and the remainder of the coarse Γ cell is
      a midpoint quadrature of the SAME integral ``(1/V_BZ)∫_{Γ_c} S d³q``, so
      the zone average converges back to ``S_coarse / N_c`` under refinement.

    Contrast with what the trigonometric interpolant does.  The interpolant
    also preserves the zone average — ``ifft → zero-pad → fft`` is linear and
    its R = 0 component is fixed, so the sum is conserved identically — but it
    conserves it by FREEZING the coarse answer and smearing it over the zone
    as a Dirichlet kernel.  Refining the grid does not refine the quadrature:
    it re-deposits the same coarse number, in the wrong places, with the wrong
    sign at many of them.  So the discriminating statement is not "is the sum
    conserved" but "is the sum a REFINEMENT of the same integral", and that is
    what the refinement arm and the ``gamma_cell='coarse'`` red twin measure.

    Returns
    -------
    float
        Ry·bohr³.  Multiply by 1/Ω to compare against an injected scalar.
    """
    S = np.asarray(S_grid, dtype=np.float64)
    return float(np.sum(S) / S.size)


def attach_head_channel(W_q, g0_X, g0_Y, S_grid, cell_volume):
    """``W_q += (S(q)/Ω) · conj(g₀) ⊗ g₀`` at EVERY fine q.  Split-and-reattach.

    The same rank-one shape ``head_correction.apply_q0_head_rank1_sharded``
    applies at the single q = 0 slice, broadcast over the k axes with a
    per-q real coefficient.  ``g0_X`` and ``g0_Y`` are the same
    ``ζ(0, μ, G=0)`` vector held in TWO copies — one ``P("x")`` on μ, one
    ``P("y")`` on ν — so the outer product is process-local on every rank and
    no ``N_μ²``-class array is ever replicated.

    THE FROZEN PROJECTOR ENTERS HERE, AND ONLY HERE.  One ``g0`` pair is
    broadcast over every fine q; the exact object would be ``g₀(q)``.  See the
    module docstring for the bound and for what would replace it.

    Parameters
    ----------
    W_q : jax.Array
        ``(n_μ, n_ν, nfx, nfy, nfz)``, sharded ``P("x","y",None,None,None)``.
    g0_X, g0_Y : jax.Array
        ``(n_μ,)`` / ``(n_ν,)``, sharded ``P("x")`` / ``P("y")``.
    S_grid : array_like
        ``(nfx, nfy, nfz)`` REAL head scalars from
        :func:`build_fine_head_scalars`.  Real is load-bearing: it is what
        makes the result Hermitian by construction.
    cell_volume : float
        Ω in bohr³.  Applied here — once — exactly where
        ``head_correction._head_rank1_scalars`` applies it today.

    Returns
    -------
    jax.Array
        Same shape and sharding as ``W_q``.
    """
    import jax.numpy as jnp

    S = np.asarray(S_grid, dtype=np.float64)
    if S.ndim != 3:
        raise ValueError(f"attach_head_channel: S_grid must be (nfx,nfy,nfz); "
                         f"got {S.shape}")
    if tuple(W_q.shape[-3:]) != tuple(S.shape):
        raise ValueError(
            f"attach_head_channel: W_q k-axes {tuple(W_q.shape[-3:])} do not "
            f"match S_grid {tuple(S.shape)} — the head scalars were built for "
            f"a different grid than the densifier produced.")
    s = jnp.asarray(S / float(cell_volume), dtype=W_q.dtype)
    g0g0 = jnp.conj(g0_X)[:, None] * g0_Y[None, :]            # (μ, ν), local
    return W_q + g0g0[:, :, None, None, None] * s[None, None, :, :, :]
