"""Time-reversal check for a two-component DFT reference.

The check compares occupied one-particle density operators at ``k`` and
``-k`` directly in G space. Evidence may come from a raw stored partner,
from the canonical spatial-only unfold of a stored partner, or from Kramers
closure at a TRIM. A state generated by a time-reversal row is never
evidence because that comparison would pass by construction.

The comparison is gauge invariant and accepts fractional occupations. It
does not build an FFT box or a real-space density, and it is intentionally
inactive for scalar, collinear-two-channel, and four-component inputs.
"""

from __future__ import annotations

import os
import sys
import time
import warnings
from dataclasses import dataclass, field

import numpy as np

__all__ = [
    "DensitySymmetryReport",
    "cached_density_symmetry_check",
    "check_density_symmetries",
    "check_spinor_reference_trs",
    "occupation_operator_residual",
    "trs_check_mode",
]

TOL_TRS = 1.0e-6
MAX_K_DEFAULT = 12
_ALGORITHM_VERSION = "occupied-density-subspace-v1"


@dataclass(frozen=True)
class DensitySymmetryReport:
    """Retained TRS receipt; density/spatial fields are compatibility data."""

    trs_holds: bool
    trs_basis: str
    m_rel: float | None
    m_rel_total: float | None
    trs_coverage: float
    tol_trs: float
    trs_implied_by_mesh: bool | None
    spatial_ops_ok: bool
    spatial_residual: np.ndarray
    spatial_untested: tuple[int, ...]
    spatial_failed: tuple[int, ...]
    tol_spatial: float
    charge: float
    charge_expected: float
    charge_rel_err: float
    rho_min_rel: float
    invariants_ok: bool
    manifold_gap: float
    path: str
    nocc: int
    nspin: int
    nspinor: int
    n_k_used: int
    n_k_total: int
    subsampled: bool
    fft_grid: tuple[int, ...]
    seconds: float
    seconds_io: float = 0.0
    seconds_quad: float = 0.0
    messages: tuple[str, ...] = field(default_factory=tuple)
    method: str = "real-space-density"
    subspace_residual: float | None = None
    min_overlap_singular_value: float | None = None
    evidence_counts: tuple[tuple[str, int], ...] = field(default_factory=tuple)
    conclusive: bool = True

    @property
    def ok(self) -> bool:
        return bool(self.trs_holds and self.spatial_ops_ok
                    and self.invariants_ok)

    def summary(self) -> str:
        residual = ("n/a" if self.subspace_residual is None else
                    f"{self.subspace_residual:.2e}")
        evidence = ", ".join(
            f"{kind}={count}" for kind, count in self.evidence_counts)
        if self.trs_basis == "not-2c":
            state = "NOT APPLICABLE"
        elif not self.trs_holds:
            state = "BROKEN"
        elif self.conclusive:
            state = "CONSISTENT"
        else:
            state = "INCONCLUSIVE"
        return (
            f"[2c-TRS] {os.path.basename(self.path)}: {state} "
            f"({self.trs_basis}, residual={residual}, "
            f"coverage={self.trs_coverage:.0%}, {evidence or 'no evidence'}) "
            f"| {self.seconds:.2f}s "
            f"(io {self.seconds_io:.2f} + overlap {self.seconds_quad:.2f})"
        )


@dataclass(frozen=True)
class _TRSEvidence:
    kind: str
    source: int
    target_raw: int
    spatial_op: int | None = None


def trs_check_mode() -> str:
    """Return ``off``, ``on``, or ``strict`` from ``LORRAX_TRS_CHECK``."""
    raw = os.environ.get("LORRAX_TRS_CHECK", "1").strip().lower()
    if raw in {"0", "false", "off", "no"}:
        return "off"
    if raw == "strict":
        return "strict"
    if raw in {"", "1", "true", "on", "yes"}:
        return "on"
    raise ValueError(
        "LORRAX_TRS_CHECK must be 0/off, 1/on, or strict; "
        f"got {raw!r}")


def _env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None:
        return default
    value = float(raw)
    if not np.isfinite(value) or value <= 0.0:
        raise ValueError(f"{name} must be finite and positive; got {raw!r}")
    return value


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    value = int(raw)
    if value < 0:
        raise ValueError(f"{name} must be non-negative; got {raw!r}")
    return value


def _is_reporting_process() -> bool:
    try:
        import jax
        return int(jax.process_index()) == 0
    except Exception:
        return True


def _periodic_max_delta(a: np.ndarray, b: np.ndarray) -> float:
    delta = np.asarray(a, dtype=np.float64) - np.asarray(b, dtype=np.float64)
    delta -= np.rint(delta)
    return float(np.max(np.abs(delta)))


def _plan_two_component_evidence(
    kpoints: np.ndarray,
    sym_mats_k: np.ndarray,
    weights: np.ndarray,
    *,
    max_k: int,
    tol: float = 1.0e-7,
) -> list[_TRSEvidence]:
    """Choose raw, spatial-only, and TRIM comparisons."""
    kpts = np.asarray(kpoints, dtype=np.float64)
    spatial = np.asarray(sym_mats_k, dtype=np.int64)
    candidates: list[_TRSEvidence] = []
    for i, ki in enumerate(kpts):
        raw = [j for j, kj in enumerate(kpts)
               if _periodic_max_delta(kj, -ki) < tol]
        if raw:
            j = int(raw[0])
            if j == i:
                candidates.append(_TRSEvidence("trim", i, j))
            elif i < j:
                candidates.append(_TRSEvidence("raw-pair", i, j))
            continue

        hit = None
        for j, kj in enumerate(kpts):
            for s, S in enumerate(spatial):
                if _periodic_max_delta(S @ kj, -ki) < tol:
                    hit = _TRSEvidence("spatial-pair", i, j, s)
                    break
            if hit is not None:
                break
        if hit is not None:
            candidates.append(hit)

    priority = {"raw-pair": 0, "spatial-pair": 1, "trim": 2}
    candidates.sort(key=lambda e: (
        -float(weights[e.source]), priority[e.kind], e.source,
        e.target_raw, -1 if e.spatial_op is None else e.spatial_op))
    return candidates if max_k <= 0 else candidates[:max_k]


def _raw_ibz_psi_k(loader, ik: int, nb: int, *, b_lo: int = 0) -> np.ndarray:
    """Read one raw stored coefficient slab as ``(band,spinor,G)``."""
    ds = loader._file["wfns/coeffs"]
    start = int(loader.kpt_starts[int(ik)])
    ngk = int(loader.ngk[int(ik)])
    raw = ds[int(b_lo):int(nb), :, start:start + ngk, :]
    return raw[..., 0] + 1j * raw[..., 1]


def _theta_overlap(
    source: np.ndarray,
    source_g: np.ndarray,
    source_k: np.ndarray,
    target: np.ndarray,
    target_g: np.ndarray,
    target_k: np.ndarray,
) -> np.ndarray:
    """Return ``<target_a|Theta source_b>`` with ``Theta=i sigma_y K``."""
    src = np.asarray(source, dtype=np.complex128)
    dst = np.asarray(target, dtype=np.complex128)
    if src.ndim != 3 or dst.ndim != 3 or src.shape[1] != 2 or dst.shape[1] != 2:
        raise ValueError("2c TRS overlap requires (band,2,G) coefficients")
    if src.shape[0] != dst.shape[0]:
        raise ValueError("source and target occupation supports differ")

    shift_f = np.asarray(source_k) + np.asarray(target_k)
    shift = np.rint(shift_f).astype(np.int64)
    if np.max(np.abs(shift_f - shift)) > 1.0e-7:
        raise ValueError(
            "TRS target is not reciprocal-equivalent to -k_source: "
            f"k_source+k_target={shift_f.tolist()}")

    target_lookup = {
        tuple(int(v) for v in g): i
        for i, g in enumerate(np.asarray(target_g, dtype=np.int64))
    }
    src_rows: list[int] = []
    dst_rows: list[int] = []
    for ig, g in enumerate(np.asarray(source_g, dtype=np.int64)):
        jg = target_lookup.get(tuple(int(v) for v in (-g - shift)))
        if jg is not None:
            src_rows.append(ig)
            dst_rows.append(jg)
    if not src_rows:
        return np.zeros((dst.shape[0], src.shape[0]), dtype=np.complex128)

    si = np.asarray(src_rows, dtype=np.int64)
    ti = np.asarray(dst_rows, dtype=np.int64)
    theta_up = np.conj(src[:, 1, si])
    theta_dn = -np.conj(src[:, 0, si])
    return (np.conj(dst[:, 0, ti]) @ theta_up.T
            + np.conj(dst[:, 1, ti]) @ theta_dn.T)


def occupation_operator_residual(
    overlap: np.ndarray,
    target_occupations: np.ndarray,
    source_occupations: np.ndarray,
) -> tuple[float, float]:
    """Distance between target and time-reversed one-particle densities."""
    M = np.asarray(overlap, dtype=np.complex128)
    ft = np.asarray(target_occupations, dtype=np.float64).reshape(-1)
    fs = np.asarray(source_occupations, dtype=np.float64).reshape(-1)
    if M.shape != (ft.size, fs.size):
        raise ValueError(
            f"overlap shape {M.shape} does not match occupations "
            f"({ft.size}, {fs.size})")
    if not (np.all(np.isfinite(ft)) and np.all(np.isfinite(fs))):
        raise ValueError("occupations must be finite")
    denom = float(np.dot(ft, ft) + np.dot(fs, fs))
    if denom <= np.finfo(np.float64).tiny:
        raise ValueError("empty occupied one-particle density operator")
    cross = float(np.einsum(
        "a,b,ab->", ft, fs, np.abs(M) ** 2, optimize=True))
    distance2 = denom - 2.0 * cross
    roundoff = 128.0 * np.finfo(np.float64).eps * max(1.0, denom)
    if distance2 < -roundoff:
        raise ValueError(
            "negative density-operator distance: coefficient rows are not "
            f"orthonormal enough for the overlap identity ({distance2:.3e})")
    residual = float(np.sqrt(max(0.0, distance2) / denom))
    singular = np.linalg.svd(M, compute_uv=False)
    return residual, (float(np.min(singular)) if singular.size else 0.0)


# Compatibility for focused tests and older diagnostic imports.
_occupation_operator_residual = occupation_operator_residual


def _spatial_mesh_needs_trs(
    kpoints: np.ndarray,
    kgrid: np.ndarray,
    shift: np.ndarray,
    sym_mats_k: np.ndarray,
    *,
    tol: float = 1.0e-7,
) -> bool | None:
    """Whether spatial stars alone fail to cover the uniform mesh."""
    kg = np.asarray(kgrid, dtype=np.int64)
    if kg.shape != (3,) or np.any(kg <= 0):
        return None
    sh = np.asarray(shift, dtype=np.float64).reshape(3) / kg
    grid = np.indices(tuple(int(v) for v in kg)).reshape(3, -1).T
    full = grid / kg[None, :] + sh[None, :]
    images = [S @ k for k in np.asarray(kpoints) for S in sym_mats_k]
    return any(not any(_periodic_max_delta(q, image) < tol for image in images)
               for q in full)


def _empty_report(
    loader,
    *,
    basis: str,
    message: str,
    tol_trs: float,
    nspin: int,
    nspinor: int,
    conclusive: bool,
    trs_holds: bool = True,
) -> DensitySymmetryReport:
    return DensitySymmetryReport(
        trs_holds=bool(trs_holds), trs_basis=basis, m_rel=None,
        m_rel_total=None,
        trs_coverage=0.0, tol_trs=tol_trs, trs_implied_by_mesh=None,
        spatial_ops_ok=True, spatial_residual=np.zeros(0),
        spatial_untested=(), spatial_failed=(), tol_spatial=float("nan"),
        charge=float("nan"), charge_expected=float("nan"),
        charge_rel_err=0.0, rho_min_rel=0.0, invariants_ok=True,
        manifold_gap=float("nan"),
        path=str(getattr(loader, "path", getattr(loader, "_path", "<wfn>"))),
        nocc=0, nspin=nspin, nspinor=nspinor, n_k_used=0,
        n_k_total=int(getattr(loader, "nkpts", 0)), subsampled=False,
        fft_grid=tuple(int(v) for v in getattr(loader, "fft_grid", ())),
        seconds=0.0, messages=(message,),
        method="occupied-density-subspace", conclusive=conclusive,
    )


def _check_two_component_trs(
    loader,
    *,
    tol_trs: float,
    max_k: int,
    nocc: int | None,
) -> DensitySymmetryReport:
    t0 = time.perf_counter()
    kpoints = np.asarray(loader.kpoints, dtype=np.float64)
    weights = np.asarray(loader.kweights, dtype=np.float64)
    if weights.shape != (kpoints.shape[0],) or not np.all(np.isfinite(weights)):
        raise ValueError("WFN k weights are missing or non-finite")
    weight_norm = float(np.sum(weights))
    if weight_norm <= 0.0:
        raise ValueError("WFN k weights have non-positive sum")

    stop = int(loader.physical_density_band_stop if nocc is None else nocc)
    stop = max(1, min(stop, int(loader.nbands)))
    occupations = np.asarray(
        loader.physical_density_occupations(k="file", unit_as_none=False),
        dtype=np.float64)[:, :stop]
    ntran = int(getattr(loader, "ntran", 1) or 1)
    spatial = np.asarray(loader.sym_matrices, dtype=np.int64)[:ntran]
    sym_mats_k = spatial.transpose(0, 2, 1)
    evidence = _plan_two_component_evidence(
        kpoints, sym_mats_k, weights, max_k=max_k)

    raw_cache: dict[int, tuple[np.ndarray, np.ndarray]] = {}
    t_io = 0.0

    def raw(ik: int) -> tuple[np.ndarray, np.ndarray]:
        nonlocal t_io
        if ik not in raw_cache:
            tic = time.perf_counter()
            coeff = _raw_ibz_psi_k(loader, ik, stop)
            start = int(loader.kpt_starts[ik])
            ngk = int(loader.ngk[ik])
            gvec = np.asarray(loader._gvecs_raw[start:start + ngk],
                              dtype=np.int64)
            t_io += time.perf_counter() - tic
            raw_cache[ik] = (coeff, gvec)
        return raw_cache[ik]

    operator_tables = None
    residuals: list[float] = []
    singular_values: list[float] = []
    covered = np.zeros(kpoints.shape[0], dtype=bool)
    counts = {"raw-pair": 0, "spatial-pair": 0, "trim": 0}
    t_overlap = 0.0
    for item in evidence:
        source, source_g = raw(item.source)
        if item.kind == "spatial-pair":
            if operator_tables is None:
                from symmetry_maps.maps import build_spatial_operator_tables
                operator_tables = build_spatial_operator_tables(loader)
            from symmetry_maps.maps import unfold_psi
            s = int(item.spatial_op)
            if not 0 <= s < ntran:
                raise AssertionError("antiunitary row entered 2c TRS evidence")
            target_raw, target_raw_g = raw(item.target_raw)
            target = unfold_psi(
                target_raw, sym_idx=s, g_kbar=target_raw_g,
                sym_mats_k=operator_tables.sym_mats_k,
                translations=operator_tables.translations,
                U_spinor_spatial=operator_tables.U_spinor)
            S = np.asarray(operator_tables.sym_mats_k[s], dtype=np.int64)
            target_k = -np.asarray(kpoints[item.source], dtype=np.float64)
            sk = S @ np.asarray(kpoints[item.target_raw], dtype=np.float64)
            kg0_f = target_k - sk
            kg0 = np.rint(kg0_f).astype(np.int64)
            if np.max(np.abs(kg0_f - kg0)) > 1.0e-7:
                raise ValueError("spatial TRS partner has non-integer umklapp")
            target_g = np.einsum(
                "ij,gj->gi", S, target_raw_g, optimize=True) - kg0
        else:
            target, target_g = raw(item.target_raw)
            target_k = np.asarray(kpoints[item.target_raw], dtype=np.float64)

        tic = time.perf_counter()
        overlap = _theta_overlap(
            source, source_g, kpoints[item.source],
            target, target_g, target_k)
        residual, min_singular = occupation_operator_residual(
            overlap, occupations[item.target_raw], occupations[item.source])
        t_overlap += time.perf_counter() - tic
        residuals.append(residual)
        singular_values.append(min_singular)
        counts[item.kind] += 1
        covered[item.source] = True
        covered[item.target_raw] = True
        raw_cache.clear()

    max_residual = max(residuals, default=None)
    min_singular = min(singular_values, default=None)
    broken = bool(max_residual is not None and max_residual > tol_trs)
    worst_kind = (None if not residuals else
                  evidence[int(np.argmax(np.asarray(residuals)))].kind)
    if broken:
        if worst_kind == "raw-pair":
            basis, conclusive = "raw-falsified", True
        elif worst_kind == "spatial-pair":
            basis, conclusive = "spatial-conditional-failure", False
        else:
            basis, conclusive = "trim-falsified", True
    elif counts["raw-pair"]:
        basis, conclusive = "raw-subspace", True
    elif counts["spatial-pair"]:
        basis, conclusive = "spatial-conditional", True
    elif counts["trim"]:
        basis, conclusive = "trim-only", False
    else:
        basis, conclusive = "unmeasurable", False

    messages: list[str] = []
    if broken and worst_kind == "spatial-pair":
        messages.append(
            "The two-component reference is incompatible with simultaneous "
            "TRS and its claimed spatial-only unfold: occupied-density "
            f"residual {max_residual:.3e} exceeds {tol_trs:.1e}. The check "
            "cannot assign the mismatch to TRS alone, so antiunitary "
            "unfolding is treated as unsafe.")
    elif broken:
        messages.append(
            "TIME-REVERSAL SYMMETRY IS BROKEN in the two-component DFT "
            f"reference: occupied-density residual {max_residual:.3e} "
            f"exceeds {tol_trs:.1e}.")
    elif basis == "spatial-conditional":
        messages.append(
            "TRS is consistent with the sampled IBZ subspaces conditional "
            "on the claimed spatial operation and canonical spatial unfold.")
    elif basis == "trim-only":
        messages.append(
            "Only TRIM/Kramers closure was independently testable. It can "
            "falsify TRS, but a pass does not establish it away from TRIM.")
    elif basis == "unmeasurable":
        messages.append(
            "No raw or spatial-only -k partner and no TRIM was available. "
            "An antiunitary-generated partner is excluded because it would "
            "pass by construction.")

    try:
        trs_implied = _spatial_mesh_needs_trs(
            kpoints, np.asarray(loader.kgrid), np.asarray(loader.shift),
            sym_mats_k)
    except Exception:
        trs_implied = None
    charge_expected = float(getattr(loader, "num_electrons", np.nan))
    n_used = int(np.count_nonzero(covered))
    return DensitySymmetryReport(
        # A pass with only TRIM closure cannot establish TRS away from the
        # measured point.  Likewise, no evidence is not permissive evidence.
        # Disable antiunitary unfolding unless the test is both passing and
        # conclusive; an explicit LORRAX_TRS_CHECK=0 remains the opt-out.
        trs_holds=bool(not broken and conclusive), trs_basis=basis,
        m_rel=max_residual, m_rel_total=None,
        trs_coverage=float(np.sum(weights[covered]) / weight_norm),
        tol_trs=tol_trs, trs_implied_by_mesh=trs_implied,
        spatial_ops_ok=True, spatial_residual=np.zeros(0),
        spatial_untested=(), spatial_failed=(), tol_spatial=float("nan"),
        charge=charge_expected, charge_expected=charge_expected,
        charge_rel_err=0.0, rho_min_rel=0.0, invariants_ok=True,
        manifold_gap=float("nan"),
        path=str(getattr(loader, "path", getattr(loader, "_path", "<wfn>"))),
        nocc=stop, nspin=1, nspinor=2, n_k_used=n_used,
        n_k_total=int(kpoints.shape[0]), subsampled=bool(n_used < kpoints.shape[0]),
        fft_grid=tuple(int(v) for v in loader.fft_grid),
        seconds=time.perf_counter() - t0, seconds_io=t_io,
        seconds_quad=t_overlap, messages=tuple(messages),
        method="occupied-density-subspace",
        subspace_residual=max_residual,
        min_overlap_singular_value=min_singular,
        evidence_counts=tuple((kind, counts[kind]) for kind in
                              ("raw-pair", "spatial-pair", "trim")),
        conclusive=conclusive,
    )


def check_spinor_reference_trs(
    loader,
    *,
    tol_trs: float | None = None,
    tol_spatial: float | None = None,
    max_k: int | None = None,
    nocc: int | None = None,
    want_transverse: bool = True,
    valence_density_fn=None,
    spin_degeneracy_fn=None,
    spin_density_fields_fn=None,
) -> DensitySymmetryReport:
    """Check a two-component DFT reference before antiunitary unfolding."""
    del tol_spatial, want_transverse, valence_density_fn
    del spin_degeneracy_fn, spin_density_fields_fn
    tol = TOL_TRS if tol_trs is None else float(tol_trs)
    cap = MAX_K_DEFAULT if max_k is None else int(max_k)
    nspin = int(getattr(loader, "nspin", 1) or 1)
    nspinor = int(getattr(loader, "nspinor", 1) or 1)
    if (nspin, nspinor) != (1, 2):
        return _empty_report(
            loader, basis="not-2c",
            message=("DFT reference TRS check is intentionally limited to "
                     "nspin=1, nspinor=2 wavefunctions."),
            tol_trs=tol, nspin=nspin, nspinor=nspinor, conclusive=True)
    return _check_two_component_trs(
        loader, tol_trs=tol, max_k=cap, nocc=nocc)


check_density_symmetries = check_spinor_reference_trs


_CACHE: dict[tuple, DensitySymmetryReport] = {}


def _cache_key(loader, nocc: int, tol_trs: float, max_k: int) -> tuple:
    path = os.path.realpath(str(getattr(loader, "path", "")))
    try:
        st = os.stat(path)
        stamp = (int(st.st_mtime_ns), int(st.st_size))
    except OSError:
        stamp = (0, 0)
    return (path, *stamp, _ALGORITHM_VERSION, int(nocc), float(tol_trs),
            int(max_k))


def _enforce_policy(
    report: DensitySymmetryReport,
    mode: str,
    *,
    announce: bool,
) -> None:
    if report.trs_basis == "not-2c":
        return
    strict_inconclusive = mode == "strict" and not report.conclusive
    if mode == "strict" and (not report.ok or strict_inconclusive):
        detail = "\n  ".join(report.messages)
        state = "INCONCLUSIVE" if not report.conclusive else "FAILED"
        raise RuntimeError(
            f"WFN two-component TRS check {state} for {report.path}:\n  "
            f"{detail}")
    if not announce:
        return
    if _is_reporting_process():
        print(report.summary(), flush=True)
    if not report.ok:
        detail = "\n  ".join(report.messages)
        text = (f"WFN two-component TRS check FAILED for {report.path}:\n  "
                f"{detail}")
        print(f"\n*** {text}\n", file=sys.stderr, flush=True)
        warnings.warn(text, RuntimeWarning)


def cached_density_symmetry_check(loader) -> DensitySymmetryReport | None:
    """Process-local cached front door used by ``WfnLoader``."""
    mode = trs_check_mode()
    if mode == "off":
        return None
    tol = _env_float("LORRAX_TRS_TOL", TOL_TRS)
    max_k = _env_int("LORRAX_TRS_MAX_K", MAX_K_DEFAULT)
    nocc = int(loader.physical_density_band_stop)
    key = _cache_key(loader, nocc, tol, max_k)
    report = _CACHE.get(key)
    if report is not None:
        _enforce_policy(report, mode, announce=False)
        return report

    try:
        report = check_spinor_reference_trs(
            loader, tol_trs=tol, max_k=max_k)
    except Exception as exc:
        if mode == "strict":
            raise
        warnings.warn(
            "two-component TRS reference check failed to run on "
            f"{getattr(loader, 'path', '<wfn>')}: {exc!r}. Proceeding with "
            "the permissive symmetry treatment. Set LORRAX_TRS_CHECK=0 "
            "to disable the check.", RuntimeWarning)
        report = _empty_report(
            loader, basis="skipped", message=repr(exc), tol_trs=tol,
            nspin=int(getattr(loader, "nspin", 0) or 0),
            nspinor=int(getattr(loader, "nspinor", 0) or 0),
            conclusive=False, trs_holds=False)
    _CACHE[key] = report
    _enforce_policy(report, mode, announce=True)
    return report
