// context.cc — NCCL + cusolverMp context construction/teardown.
//
// The `LorraxCusolverMpCtx` struct is ONLY lived inside the .so.  Python
// sees it as an opaque int64 handle (reinterpret_cast<uintptr_t>).

#include <cstdint>
#include <cstring>
#include <cstdio>
#include <sstream>
#include <stdexcept>
#include <string>

#include <cuda_runtime.h>
#include <nccl.h>
#include <cusolverMp.h>

#include "../../common/cpp/xla_ffi_glue.h"
#include "ctx.h"

namespace lorrax_ffi::cusolvermp {

// ----- tiny throwing checks (for setup path; FFI handlers use Error) ------
static void throw_if_cuda(cudaError_t st, const char* what) {
    if (st == cudaSuccess) return;
    std::ostringstream os;
    os << what << ": " << cudaGetErrorName(st) << " (" << cudaGetErrorString(st) << ")";
    throw std::runtime_error(os.str());
}
static void throw_if_nccl(ncclResult_t st, const char* what) {
    if (st == ncclSuccess) return;
    std::ostringstream os;
    os << what << ": nccl=" << ncclGetErrorString(st);
    throw std::runtime_error(os.str());
}
static void throw_if_cusolver(cusolverStatus_t st, const char* what) {
    if (st == CUSOLVER_STATUS_SUCCESS) return;
    std::ostringstream os;
    os << what << ": cusolver status=" << static_cast<int>(st);
    throw std::runtime_error(os.str());
}

// ----- context lifecycle --------------------------------------------------
int64_t create_context(int rank, int world_size,
                       uintptr_t nccl_unique_id_addr,
                       int nccl_unique_id_nbytes,
                       int p, int q,
                       bool grid_layout_col_major)
{
    if (p * q != world_size) {
        std::ostringstream os;
        os << "create_cusolvermp_context: p*q (=" << p*q
           << ") must equal world_size (=" << world_size << ")";
        throw std::runtime_error(os.str());
    }
    if (nccl_unique_id_nbytes != static_cast<int>(sizeof(ncclUniqueId))) {
        std::ostringstream os;
        os << "create_cusolvermp_context: nccl_unique_id_nbytes ("
           << nccl_unique_id_nbytes << ") != sizeof(ncclUniqueId) ("
           << sizeof(ncclUniqueId) << ")";
        throw std::runtime_error(os.str());
    }

    auto* ctx = new LorraxCusolverMpCtx{};
    ctx->rank       = rank;
    ctx->world_size = world_size;
    ctx->p          = p;
    ctx->q          = q;
    ctx->grid_layout_col_major = grid_layout_col_major;

    // Ensure this thread's current CUDA device matches the caller's local
    // rank (NERSC: srun binds 1 GPU per rank; cudaGetDevice returns 0 in
    // the narrow view, but that *is* the correct local GPU for this proc).
    //
    // Importantly, the subsequent stream create MUST happen while that
    // device is current — a known cusolverMp pitfall (see NVIDIA devtalk
    // thread 313054).
    int current_device = 0;
    throw_if_cuda(cudaGetDevice(&current_device), "cudaGetDevice");
    throw_if_cuda(cudaSetDevice(current_device), "cudaSetDevice");
    // Ensure CUDA primary context is live on this device.
    throw_if_cuda(cudaFree(nullptr), "cudaFree(nullptr)");
    ctx->local_device_id = current_device;

    // ncclCommInitRank: collective among all `world_size` processes.  The
    // unique id was generated by rank 0 and broadcast by the caller.
    ncclUniqueId uid;
    std::memcpy(&uid, reinterpret_cast<void*>(nccl_unique_id_addr),
                sizeof(ncclUniqueId));
    throw_if_nccl(ncclCommInitRank(&ctx->nccl_comm, world_size, uid, rank),
                  "ncclCommInitRank");

    // Private CUDA stream for cusolverMp operations.  XLA still passes us
    // its own per-call stream; we serialise between the two in the FFI
    // handler.
    throw_if_cuda(cudaStreamCreateWithFlags(&ctx->stream, cudaStreamNonBlocking),
                  "cudaStreamCreate");

    // cusolverMp handle — tied to (localDeviceId, stream).
    throw_if_cusolver(
        cusolverMpCreate(&ctx->handle, ctx->local_device_id, ctx->stream),
        "cusolverMpCreate");

    // Single process grid used for all matrices this context will solve
    // (p × q).  Larger matrices can reuse the same grid across many
    // FFI calls.
    cusolverMpGridMapping_t layout = grid_layout_col_major
        ? CUSOLVERMP_GRID_MAPPING_COL_MAJOR
        : CUSOLVERMP_GRID_MAPPING_ROW_MAJOR;
    // cuSOLVERMp's API declares the comm parameter as `cal_comm_t`.  In
    // NVIDIA's mp_syevd.c sample (CUDALibrarySamples), an `ncclComm_t` is
    // passed directly; C implicitly converts unrelated pointer types, but
    // C++ requires an explicit reinterpret_cast.  As of cuSOLVERMp 0.6.x
    // (HPC SDK 25.5) the library internally accepts an NCCL comm handle
    // regardless of the static type.  Release notes: "cuSOLVERMp has
    // transitioned from using libcal to using NCCL directly".
    throw_if_cusolver(
        cusolverMpCreateDeviceGrid(ctx->handle, &ctx->grid,
                                   reinterpret_cast<cal_comm_t>(ctx->nccl_comm),
                                   /*numRowDevices=*/p,
                                   /*numColDevices=*/q, layout),
        "cusolverMpCreateDeviceGrid");

    // Device buffer for d_info (int) used by every Syevd call.
    throw_if_cuda(cudaMalloc(&ctx->d_info, sizeof(int)), "cudaMalloc(d_info)");
    throw_if_cuda(cudaMemset(ctx->d_info, 0, sizeof(int)), "cudaMemset(d_info)");

    // Workspace scratchpads start empty; grown on demand in the FFI.
    ctx->d_workspace = nullptr;
    ctx->d_workspace_bytes = 0;
    ctx->h_workspace = nullptr;
    ctx->h_workspace_bytes = 0;

    return reinterpret_cast<int64_t>(ctx);
}

void destroy_context(int64_t ctx_handle) {
    if (ctx_handle == 0) return;
    auto* ctx = reinterpret_cast<LorraxCusolverMpCtx*>(ctx_handle);

    if (ctx->grid)    { cusolverMpDestroyGrid(ctx->grid);        ctx->grid = nullptr; }
    if (ctx->handle)  { cusolverMpDestroy(ctx->handle);          ctx->handle = nullptr; }
    if (ctx->stream)  { cudaStreamDestroy(ctx->stream);          ctx->stream = nullptr; }
    if (ctx->nccl_comm){ ncclCommDestroy(ctx->nccl_comm);        ctx->nccl_comm = nullptr; }
    if (ctx->d_info)  { cudaFree(ctx->d_info);                   ctx->d_info = nullptr; }
    if (ctx->d_workspace) { cudaFree(ctx->d_workspace);          ctx->d_workspace = nullptr; }
    if (ctx->h_workspace) { free(ctx->h_workspace);              ctx->h_workspace = nullptr; }

    delete ctx;
}

// Grow workspace on demand; preserves the larger allocation on future calls.
void ensure_workspace(LorraxCusolverMpCtx* ctx, size_t d_need, size_t h_need) {
    if (d_need > ctx->d_workspace_bytes) {
        if (ctx->d_workspace) cudaFree(ctx->d_workspace);
        throw_if_cuda(cudaMalloc(&ctx->d_workspace, d_need),
                      "cudaMalloc(d_workspace)");
        ctx->d_workspace_bytes = d_need;
    }
    if (h_need > ctx->h_workspace_bytes) {
        if (ctx->h_workspace) free(ctx->h_workspace);
        ctx->h_workspace = malloc(h_need);
        if (!ctx->h_workspace)
            throw std::runtime_error("malloc(h_workspace) failed");
        ctx->h_workspace_bytes = h_need;
    }
}

// ----- smoke: ncclAllReduce on a device float buffer ---------------------
int smoke_allreduce_sum(int64_t ctx_handle,
                        uintptr_t device_ptr,
                        int nelems)
{
    auto* ctx = reinterpret_cast<LorraxCusolverMpCtx*>(ctx_handle);
    ncclResult_t st = ncclAllReduce(
        reinterpret_cast<const void*>(device_ptr),
        reinterpret_cast<void*>(device_ptr),
        static_cast<size_t>(nelems),
        ncclFloat32,
        ncclSum,
        ctx->nccl_comm,
        ctx->stream);
    if (st != ncclSuccess) return static_cast<int>(st);
    cudaError_t ce = cudaStreamSynchronize(ctx->stream);
    if (ce != cudaSuccess) return 1000 + static_cast<int>(ce);
    return 0;
}

}  // namespace lorrax_ffi::cusolvermp
