"""Real 4-rank CUDA gate: the narrow one-shot insulating low_mem_bands
envelope, end to end, comparing FOUR real production `gw.gw_jax` runs.

Guide: reports/gwjax_low_mem_bands_audit_2026-08-22/report.md, landing-order
step 4 ("Gate the narrow one-shot insulating envelope end to end, with
low_mem_bands=false bit-identical to the incumbent path") and the
verification section ("Matched fresh/restart one-shot legs ... Use the
existing output parsers for numerical comparisons").

UNLIKE the sibling `*_gate.py` scripts in this directory, this one does NOT
call any driver function directly -- it compares the ON-DISK OUTPUT of four
independent, real `python3 -m gw.gw_jax -i cohsex.in` invocations, because
"end to end" here means the actual production CLI entry point, not a
paraphrase of its internals. It takes no jax/CUDA of its own; it is a pure
file comparator, runnable on a login node once the four legs have been
produced (see the module docstring below for how they were produced this
session).

The four legs, and how they were produced (claims/0429.md has the full
narrative, jobids, and wall-clock table):

  a_legacy_main   -- low_mem_bands unset, run against UNMODIFIED
                     origin/main (a separate checkout/tree)
  a_legacy_mine   -- byte-identical deck to a_legacy_main, run against
                     THIS branch's tree with low_mem_bands left at its
                     default (false) -- i.e. the exact existing legacy path
  b_face_fresh    -- a_legacy_mine's deck plus low_mem_bands=true,
                     write_restart_tensors=true (fresh ISDF fit)
  c_face_restart  -- a_legacy_mine's deck plus low_mem_bands=true,
                     restart=true, reading b_face_fresh's
                     tmp/isdf_tensors_<n_rmu>.h5 (copied, not symlinked)

Each leg is a real 4-rank (2x2 mesh) CUDA run of the production driver on
the MoS2 k6_c50 deck (675 centroids), compute_mode=cohsex (the mode
ACTUALLY ported to face layout -- see the gnppm_bug_evidence_* siblings and
KNOWN_LORRAX_ISSUES.md for why compute_mode=gn_ppm, the guide's own cited
example, is NOT used here), qp_solver=one_shot_dft, head_correction=off.

Checks, strongest first:

  1. sigma_diag.dat / eqp0.dat / eqp1.dat are BODY-byte-identical (every
     line after the "# Generated by LORRAX ... at <timestamp>" provenance
     line) across all four legs -- text-level, no tolerance.
  2. qp_wfn_rotations.h5's E_qp_nk_{hartree,rydberg} match to a tight
     numerical tolerance (this run measured ~1e-14, floating-point noise)
     between a_legacy_mine and each of b_face_fresh/c_face_restart.
  3. Reports (does not fail on) qp_wfn_rotations.h5's U_mnk gauge
     difference -- see claims/0429.md's "gauge note": both U are confirmed
     unitary; the QP energies (check 2) are what is physically meaningful.

Run (comparison only, no CUDA needed):
    python3 tests/multi_device/low_mem_bands_one_shot_insulating_envelope_gate.py \\
        <attempt_dir>/a_legacy_main <attempt_dir>/a_legacy_mine \\
        <attempt_dir>/b_face_fresh <attempt_dir>/c_face_restart

Exit 0 and "VERDICT PASS" on success; nonzero and "VERDICT FAIL" naming the
first mismatch otherwise.
"""
from __future__ import annotations

import hashlib
import sys


def _body_sha256(path):
    """sha256 of every line after the first (the timestamp provenance
    line every LORRAX text output carries) -- see PARSE_OUTPUTS.md."""
    with open(path, "rb") as f:
        lines = f.readlines()
    return hashlib.sha256(b"".join(lines[1:])).hexdigest()


def compare_text_outputs(ref_dir, other_dir, filenames=(
        "sigma_diag.dat", "eqp0.dat", "eqp1.dat")):
    """Return a list of (filename, ref_hash, other_hash) mismatches;
    empty means every named file's body is byte-identical."""
    mismatches = []
    for name in filenames:
        ref_hash = _body_sha256(f"{ref_dir}/{name}")
        other_hash = _body_sha256(f"{other_dir}/{name}")
        if ref_hash != other_hash:
            mismatches.append((name, ref_hash, other_hash))
    return mismatches


def compare_qp_rotations(ref_dir, other_dir, tol=1e-10):
    """Return (max_diff_hartree, max_diff_rydberg, u_mnk_max_diff) between
    two qp_wfn_rotations.h5 files' E_qp_nk_* datasets (the physically
    meaningful quantity) and U_mnk (reported, not tolerance-checked -- see
    module docstring's "gauge note")."""
    import h5py
    import numpy as np

    with h5py.File(f"{ref_dir}/qp_wfn_rotations.h5", "r") as a, \
            h5py.File(f"{other_dir}/qp_wfn_rotations.h5", "r") as b:
        dh = float(np.max(np.abs(
            a["E_qp_nk_hartree"][()] - b["E_qp_nk_hartree"][()])))
        dr = float(np.max(np.abs(
            a["E_qp_nk_rydberg"][()] - b["E_qp_nk_rydberg"][()])))
        du = float(np.max(np.abs(a["U_mnk"][()] - b["U_mnk"][()])))
    if dh > tol or dr > tol:
        raise AssertionError(
            f"{other_dir} vs {ref_dir}: E_qp_nk mismatch "
            f"(hartree {dh:.3e}, rydberg {dr:.3e}) exceeds tol={tol:.1e}")
    return dh, dr, du


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 4:
        print(__doc__)
        return 2
    a_main, a_mine, b_fresh, c_restart = argv
    failures = []

    print("[1/3] a_legacy_main vs a_legacy_mine (bit-identical baseline)")
    mism = compare_text_outputs(a_main, a_mine)
    if mism:
        failures.append(f"a_legacy_main vs a_legacy_mine: {mism}")
    else:
        print("  PASS: sigma_diag.dat/eqp0.dat/eqp1.dat body byte-identical")

    for label, leg_dir in (("b_face_fresh", b_fresh),
                            ("c_face_restart", c_restart)):
        print(f"[2/3] a_legacy_mine vs {label} (text outputs)")
        mism = compare_text_outputs(a_mine, leg_dir)
        if mism:
            failures.append(f"a_legacy_mine vs {label}: {mism}")
        else:
            print("  PASS: sigma_diag.dat/eqp0.dat/eqp1.dat body byte-identical")

        print(f"[3/3] a_legacy_mine vs {label} (qp_wfn_rotations.h5)")
        try:
            dh, dr, du = compare_qp_rotations(a_mine, leg_dir)
            print(f"  PASS: E_qp_nk max|diff| hartree={dh:.3e} "
                  f"rydberg={dr:.3e} (tol 1e-10); U_mnk max|diff|={du:.3e} "
                  f"(reported only -- see module docstring's gauge note)")
        except (AssertionError, OSError, KeyError) as exc:
            failures.append(f"a_legacy_mine vs {label} qp_wfn_rotations: {exc}")

    if failures:
        print("VERDICT FAIL")
        for f in failures:
            print(f"  FAIL: {f}")
        return 1
    print("VERDICT PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
