#!/usr/bin/env python3
"""Generate docs/input_reference.md from gw_config._DEFAULTS.

Rerunnable: ``python3 tools/gen_input_reference.py`` from the repo root.
Defaults are harvested from the ``_DEFAULTS`` dict literal in
``src/gw/gw_config.py`` by AST parse (no import, no jax).  The one-line
meanings below are hand-polished from the dataclass/parse-site comments;
the script REFUSES if the key set in the source and the key set here
drift apart, so a new deck key cannot land without a reference row.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "src" / "gw" / "gw_config.py"
OUT = REPO / "docs" / "input_reference.md"

HEADER = """\
# Input reference

Every deck key of the `[cohsex]` section: name, default, one-line meaning.
Generated by `tools/gen_input_reference.py` from `gw_config._DEFAULTS`
(the single source of truth for deck keys); regenerate after any change there.
Unknown keys warn: a key not in `_DEFAULTS` and not covered by a legacy branch
is reported in one aggregated rank-0 warning and ignored; `strict_keys = true`
upgrades this to a refusal naming every unknown key.
Longer discussions of the load-bearing keys are in [drivers.md](drivers.md).
"""

# key -> (group, one-line meaning).  Groups render in GROUP_ORDER.
GROUP_ORDER = [
    "System",
    "ISDF / zeta",
    "Screening",
    "Sigma",
    "IO / restart",
    "Solver",
    "BSE",
]

KEYS: dict[str, tuple[str, str]] = {
    # ---- System ----
    "nval": ("System", "Interior valence edge of the sigma window: b1 = nelec - nval (gates the ISDF pair-density right window, not the QP window bottom)."),
    "ncond": ("System", "Conduction bands in the sigma/QP window; sigma diagonals are computed for [0, nelec+ncond)."),
    "nband": ("System", "chi0/Sigma band-sum top b4, rounded up to the world size (pads are zeroed)."),
    "sys_dim": ("System", "System dimensionality (2 = slab): selects the Coulomb truncation."),
    "ecutrho": ("System", "Density-grid cutoff (Ry) for the psp tools (kin_ion/dipole); None = the WFN's own ecutwfc."),
    "bispinor": ("System", "Bispinor (4-spinor) run: 4-channel zeta-fit, Sigma^B transverse channels, two centroid files."),
    "fermi_reference": ("System", "Where E_F sits inside the gap for the G/W time kernels (midgap default)."),
    # ---- ISDF / zeta ----
    "centroids_file": ("ISDF / zeta", "Charge-channel ISDF centroid table written by centroid.kmeans_cli."),
    "centroids_file_current": ("ISDF / zeta", "Second centroid table (Gordon-current weight) for the bispinor transverse channels; empty = not set."),
    "zeta_ridge": ("ISDF / zeta", "Opt-in Tikhonov ridge epsilon on the charge CCT (fraction of mean diagonal); 0 = bit-identical historical factor. Env LORRAX_ZETA_RIDGE."),
    "charge_zeta_solve": ("ISDF / zeta", "Charge zeta conditioner: rank_truncate (default; rank-revealing eigh pseudo-inverse) or the historical cholesky."),
    "distributed_zeta_solve": ("ISDF / zeta", "Zeta back-solve tier: replicated | per_q | distributed (nothing O(mu^2) replicated); auto = replicated under the 4 GiB gather cap, else per_q."),
    "zeta_rcond": ("ISDF / zeta", "Rank-truncation cutoff relative to lambda_max (default 1e-8, low end of the recovery plateau). Env LORRAX_ZETA_RCOND."),
    "zeta_cutoff": ("ISDF / zeta", "Zeta-sphere G-cutoff (Ry) for per-q zeta_q_G writes; None = ecutwfc; must be >= bare_coulomb_cutoff."),
    "gamma_contract_mode": ("ISDF / zeta", "HLO variant of the gamma-tilde double contraction: take (default) | einsum | scan; math-identical."),
    "gflat_chunk_size": ("ISDF / zeta", "Flat-axis chunk of the r-chunk G-accumulation; 0 = planner-chosen, explicit > 0 wins."),
    "vq_g_chunk_size": ("ISDF / zeta", "V_q inner G-axis GEMM chunk; 0 = auto (largest divisor of ngkmax <= 4096)."),
    "band_chunk_size": ("ISDF / zeta", "Bands per chunk in the band-chunked FFT/pair-density loops."),
    "r_chunk_size": ("ISDF / zeta", "Real-space columns per zeta-fit chunk; 0 = auto from the memory model."),
    "memory_per_device_gb": ("ISDF / zeta", "Per-device memory budget for the chunk planners; 0 = auto-detect."),
    # ---- Screening ----
    "do_screened": ("Screening", "Legacy mode flag: build W and the screened Sigma terms (false = bare exchange only); compute_mode=auto reads it."),
    "screening_method": ("Screening", "chi0 frequency treatment (minimax quadrature is the only production method)."),
    "minimax_target_error": ("Screening", "Target uniform error of the minimax time/frequency quadrature."),
    "minimax_max_nodes": ("Screening", "Node-count cap for the minimax quadrature solver."),
    "regenerate_minimax_tables": ("Screening", "Force re-solving the minimax tables instead of reusing cached ones."),
    "minimax_energy_reference": ("Screening", "Energy reference for the minimax transition range (midgap default)."),
    "ppm_model": ("Screening", "Plasmon-pole ansatz: gn (Godby-Needs, imaginary probe) | hl (Hybertsen-Louie, real probe)."),
    "ppm_omega_p": ("Screening", "Second PPM probe frequency (Ry): i*omega_p for GN, real omega_p for HL."),
    "ppm_fallback_omega": ("Screening", "Positive real fallback pole (Ry) for elements with no valid Omega^2 fit."),
    "ppm_head_omega_h_ry": ("Screening", "Override the q->0 head pole Omega_h (Ry) directly; None = compute normally. BGW comparison aid."),
    "ppm_invalid_mode": ("Screening", "Invalid-pole treatment: static_limit (default, BGW mode 3) | zero (BGW 0) | 2ry (BGW 2)."),
    "use_ppm_sigma": ("Screening", "Legacy flag for the dynamic PPM Sigma^c(omega); compute_mode=auto reads it."),
    "w_dyson_solver": ("Screening", "W Dyson plan: local (per-q pivoted LU; auto alias) | distributed (2-D block-cyclic backsolve; refuses loudly, never downgrades)."),
    "bare_coulomb_cutoff": ("Screening", "G-cutoff (Ry) of the bare Coulomb V_q build; None = ecutwfc."),
    "mc_average_vcoul_body": ("Screening", "Monte-Carlo mini-BZ average of the Coulomb body (BGW convention)."),
    "head_minibz_average": ("Screening", "Coulomb head as mini-BZ cell average instead of point value (fixes 4-13% near-Gamma error at finite Q); false = bit-identical legacy."),
    "wcoul0_source": ("Screening", "Where W(q=0) head comes from (s_tensor = analytic head correction from dipole.h5)."),
    "wcoul0_eta": ("Screening", "Broadening eta for the W head evaluation."),
    "vhead": ("Screening", "Override the bare Coulomb head value; None = analytic."),
    "whead_0freq": ("Screening", "Override the static W head; None = computed."),
    "whead_imfreq": ("Screening", "Override the imaginary-frequency W head (GN probe); None = computed."),
    "use_bgw_vcoul": ("Screening", "Diagnostic: read v(q,G) from a BGW vcoul file instead of building it."),
    "bgw_vcoul_file": ("Screening", "Path of the BGW vcoul file for use_bgw_vcoul."),
    "bgw_vcoul_sym_wfn": ("Screening", "Aux WFN supplying the full symmetry group to fold LORRAX q's onto BGW's IBZ q-list."),
    # ---- Sigma ----
    "compute_mode": ("Sigma", "Self-energy ansatz: x_only | cohsex | gn_ppm | hl_ppm; auto infers from the legacy do_screened/use_ppm_sigma/ppm_model flags."),
    "ppm_sigma_target_error": ("Sigma", "Target error of the PPM Sigma^c tau-quadrature."),
    "ppm_sigma_max_nodes": ("Sigma", "Node-count cap for the PPM Sigma^c quadrature."),
    "sigma_omega_min_ev": ("Sigma", "Sigma(omega) grid lower edge (eV, relative to E_DFT)."),
    "sigma_omega_max_ev": ("Sigma", "Sigma(omega) grid upper edge (eV)."),
    "sigma_omega_step_ev": ("Sigma", "Sigma(omega) grid step (eV)."),
    "sigma_regularization_ev": ("Sigma", "Lorentzian regularization of the Sigma(omega) evaluation (eV)."),
    "sigma_window_edge_factor": ("Sigma", "Widens the minimax window past the sigma omega-grid edges (T = omega_max + factor*xi)."),
    "sigma_omega_batch_size": ("Sigma", "Omega points evaluated per batch in the Sigma^c(omega) loop."),
    "sigma_omega_accumulation": ("Sigma", "How per-branch Sigma(omega) contributions are accumulated (auto = pick by size)."),
    "sigma_omega_layout": ("Sigma", "Sigma_c(omega,k,m,n) cube layout: replicated (default) | sharded (stays mesh-tiled end-to-end; refuses for self_consistent, indivisible window, h5py_allgather at P>1)."),
    "no_degen_averaging": ("Sigma", "Disable BGW-style averaging of diagonal Sigma within degenerate sets."),
    "degen_avg_tol_ry": ("Sigma", "Degeneracy tolerance for the averaging (BGW TOL_Degeneracy = 1e-6 Ry)."),
    "sigma_at_dft_extrapolate": ("Sigma", "Extrapolate Sigma to E_DFT outside the omega grid instead of clamping."),
    "sigma_at_dft_energies": ("Sigma", "DEPRECATED alias for qp_solver = one_shot_dft (now the default)."),
    "sigma_freq_debug_output": ("Sigma", "Dump the per-branch Sigma(omega) debug table."),
    "sigma_freq_debug_file": ("Sigma", "Path of the Sigma(omega) debug dump."),
    # ---- IO / restart ----
    "wfn_file": ("IO / restart", "BGW-format wavefunction input (WFN.h5)."),
    "kin_ion_file": ("IO / restart", "kin_ion.h5 from gw.kin_ion_io: T+V_loc+V_NL matrix (+ stored v_hartree)."),
    "hartree_source": ("IO / restart", "The G-space vs ISDF V_H switch: auto (stored -> folded -> isdf) | stored | isdf | gspace."),
    "sigma_diag_file": ("IO / restart", "LORRAX-native per-(k,n) Sigma-decomposition text output."),
    "eqp0_file": ("IO / restart", "BGW-format zeroth-order QP energies output."),
    "eqp1_file": ("IO / restart", "BGW-format Z-linearized QP energies output (Z=1 in static COHSEX)."),
    "sigma_omega_h5_file": ("IO / restart", "Sigma_c(omega,k,m,n) HDF5 output."),
    "restart": ("IO / restart", "Reuse tmp/isdf_tensors_{n_rmu}.h5 (skip zeta-fit/V_q); guarded by band-window attrs + centroid-table md5 stamps."),
    "use_ffi_io": ("IO / restart", "DEPRECATED tri-state, superseded by slab_io; explicit false = h5py_allgather."),
    "slab_io": ("IO / restart", "Distributed HDF5 routing: auto (capability-probed) | phdf5_ffi | phdf5_host | h5py_allgather; explicit values fail loudly if unavailable."),
    "gspace_mode": ("IO / restart", "psi(G) host lifecycle: host_cache (resident, default) | file_reread (rebuild per r-chunk; zero persistent residency)."),
    "write_wfn_h5": ("IO / restart", "End-of-run WFN_qp.h5 write (BGW format, psi rotated by the final U, E_QP energies)."),
    "strict_keys": ("IO / restart", "Unknown deck keys refuse (ValueError naming every one) instead of the default aggregated warning."),
    # ---- Solver ----
    "qp_solver": ("Solver", "QP extraction: one_shot_dft (G0W0 at E_DFT; auto default) | fixed_point (on-shell) | self_consistent (QSGW loop)."),
    "do_G0": ("Solver", "Compute the analytic q->0 static head terms (needs dipole.h5); part of every production run."),
    "self_consistent": ("Solver", "DEPRECATED alias for qp_solver = self_consistent."),
    "sc_max_iter": ("Solver", "Self-consistency iteration cap."),
    "sc_tol_ev": ("Solver", "Self-consistency convergence tolerance (eV)."),
    "sc_accelerator": ("Solver", "SC mixing accelerator: rcrop | linear."),
    "sc_history_depth": ("Solver", "rCROP history depth."),
    "sc_mixing": ("Solver", "Linear-mixing alpha (accelerator = linear only)."),
    "sc_dump_dir": ("Solver", "Directory for per-iteration E-history npy dumps; empty = off."),
    "eigh_backend": ("Solver", "BSE/htransform distributed-eigh sites: auto|off = q-batched native eigh; distributed | cusolvermp | slate | scalapack spread ONE tile over the mesh. CLI --eigh-backend overrides."),
    "use_low_mem_eigh": ("Solver", "Same axis by intent: one (rank,rank) matrix does not fit a rank; true + auto => distributed; true + off refused at parse."),
    "distributed_cholesky": ("Solver", "Charge-channel zeta-fit Cholesky backend: auto | off | cusolvermp | slate."),
    "distributed_lu": ("Solver", "Transverse-channel LU backend: auto | off | cusolvermp | scalapack (host CPU; explicit only)."),
    # ---- BSE ----
    "bse_k_grid": ("BSE", "\"NX NY NZ\" fine grid: densify the whole BSE bundle (psi/eps, V_Q, W) from the coarse restart grid before any solve; empty = coarse, byte-identical."),
    "get_centroids_fi": ("BSE", "htransform -> BSE handoff: also compute fine-grid psi at the coarse centroids (bse_setup.compute_wfns_fi)."),
    "wfn_fi_min": ("BSE", "Sub-window lower edge on the htransform band axis (0-based)."),
    "wfn_fi_max": ("BSE", "Sub-window upper edge, exclusive; 0 = full window."),
    "kgrid_fi": ("BSE", "\"nx ny nz\" fine k-grid for the wfn recovery; empty = none."),
    "wfn_fi_q_chunk": ("BSE", "Fine-grid q-points per f(H(q)) build; 0 = N_q_coarse (same per-rank residency as fH_R); floor, rounded to device count."),
}


def harvest_defaults(path: Path) -> dict[str, object]:
    tree = ast.parse(path.read_text())
    for node in ast.walk(tree):
        if (isinstance(node, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id == "_DEFAULTS"
                        for t in node.targets)):
            return ast.literal_eval(node.value)
    raise SystemExit(f"_DEFAULTS dict not found in {path}")


def fmt_default(v: object) -> str:
    if v is None:
        return "None"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return f'`"{v}"`' if v else '`""`'
    return f"`{v!r}`".replace("'", "")


def main() -> None:
    defaults = harvest_defaults(CONFIG)
    src_keys = set(defaults)
    doc_keys = set(KEYS)
    if src_keys != doc_keys:
        missing = sorted(src_keys - doc_keys)
        stale = sorted(doc_keys - src_keys)
        raise SystemExit(
            "gen_input_reference: key drift vs gw_config._DEFAULTS\n"
            f"  missing one-liners for: {missing}\n"
            f"  stale entries for removed keys: {stale}")

    lines = [HEADER]
    for group in GROUP_ORDER:
        rows = [(k, KEYS[k][1]) for k in defaults if KEYS[k][0] == group]
        if not rows:
            continue
        lines.append(f"\n## {group}\n")
        lines.append("| key | default | meaning |")
        lines.append("|---|---|---|")
        for k, meaning in rows:
            d = fmt_default(defaults[k])
            d = d.replace("|", "\\|")
            lines.append(f"| `{k}` | {d} | {meaning} |")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(defaults)} keys)")


if __name__ == "__main__":
    sys.exit(main())
