// GENERATED from /pscratch/sd/j/jackm/wt_hybrid_wiring_2026-08-29/src/ffi/cpp/cufft/conv_kminor_cuda_ffi.cc; do not edit this file.


// 16-byte complex128, so every global and shared access is ONE 128-bit
// transaction instead of two 64-bit ones.  Declared here rather than using the
// toolkit's `double2` to keep this source header-free under NVRTC, which is
// the sibling flat-k kernel's rule and costs one line.
struct __align__(16) lrx_c2 { double x, y; };

// ONE separable axis pass over this thread's EPT elements.
//
// TEMPLATED ON EPT, and that is not style.  With a runtime element count the
// accumulator array cannot be proven register-resident and nvcc puts it in
// LOCAL memory — i.e. in DRAM behind L1 — so every one of the six passes pays
// a round trip that does not appear anywhere in the algorithm.  A compile-time
// EPT makes acc[] registers.  The host picks EPT and the kernel switches once,
// uniformly, at entry.
//
// TEMPLATED ON AXIS for the same class of reason.  The element's 3-D index
// (kx,ky,kz) is FIXED for a thread across all six passes, so it is decomposed
// ONCE by the caller; each pass then derives its (base, mid) from it with
// multiplies.  Spelling the pass generically over (len, stride) instead —
// which the first working version did — forces `k % stride`, `k / stride`,
// `. % len`, `. / len` per element per pass: 24 runtime integer divisions per
// element, ~20 emulated instructions each, against ~140 instructions of actual
// arithmetic.  That version ran the whole sweep at a flat ~320 GB/s and the
// index math, not the memory system, was what it was waiting on.
template <int EPT, int AXIS>
__device__ __forceinline__ void lrx_pass(
    const lrx_c2* rowp, const lrx_c2* twv,
    int nk, int lane, int tpr, int n0, int n1, int n2,
    const int (&kx)[EPT], const int (&ky)[EPT], const int (&kz)[EPT],
    double sgn, lrx_c2 (&acc)[EPT])
{
    const int len    = (AXIS == 0) ? n0 : ((AXIS == 1) ? n1 : n2);
    const int stride = (AXIS == 0) ? (n1 * n2) : ((AXIS == 1) ? n2 : 1);
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e * tpr;
        if (k < nk) {
            int b, md;
            if (AXIS == 0)      { b = ky[e] * n2 + kz[e];      md = kx[e]; }
            else if (AXIS == 1) { b = kx[e] * n1 * n2 + kz[e]; md = ky[e]; }
            else                { b = (kx[e] * n1 + ky[e]) * n2; md = kz[e]; }
            double ar = 0.0, ai = 0.0;
            int m = 0;                     // (md·j) mod len, carried
            for (int j = 0; j < len; ++j) {
                const lrx_c2 v = rowp[b + j * stride];
                const lrx_c2 w = twv[m];
                const double wi = sgn * w.y;
                ar += v.x * w.x - v.y * wi;
                ai += v.x * wi + v.y * w.x;
                m += md;
                if (m >= len) m -= len;
            }
            acc[e].x = ar;
            acc[e].y = ai;
        }
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_writeback(
    lrx_c2* rowp, int nk, int lane, int tpr, const lrx_c2 (&acc)[EPT])
{
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e * tpr;
        if (k < nk) rowp[k] = acc[e];
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_conv_body(
    const lrx_c2* tin, const lrx_c2* __restrict__ wgt, lrx_c2* uout,
    long long R, long long d1, long long d2, long long d3, long long d4,
    int nk, int n0, int n1, int n2, int SP, double scale, int out_layout,
    lrx_c2* sm)
{
    const int tpr  = blockDim.x;
    const int RB   = blockDim.y;
    const int tid  = threadIdx.y * tpr + threadIdx.x;
    const int nthr = tpr * RB;
    const int lane = threadIdx.x;
    const int ntw  = n0 + n1 + n2;
    const int tile = RB * nk;

    lrx_c2* tw = sm + (long long)RB * SP;
    long long* meta = (long long*)(tw + ntw);   // [0,RB) W offset; [RB,2RB) dst
    const long long r0 = (long long)blockIdx.x * RB;
    const long long kstride = d3 * d1 * d4 * d2;   // out_layout=1 k stride

    // --- twiddle rings: tw_x[n0], tw_y[n1], tw_z[n2], exp(-2πi m/len) ---
    for (int i = tid; i < ntw; i += nthr) {
        int m, len;
        if (i < n0)            { m = i;           len = n0; }
        else if (i < n0 + n1)  { m = i - n0;      len = n1; }
        else                   { m = i - n0 - n1; len = n2; }
        double s, c;
        // sincospi, not sincos(2*pi*x): the CUDA math API is available to
        // NVRTC with no include, and sincospi takes HALF-TURNS, so it never
        // rounds a multiple of pi into the angle.  sincos(-2*PI*m/len) would
        // carry ~1e-15 of angle error straight into the twiddle and eat the
        // whole parity budget.
        sincospi(-2.0 * (double)m / (double)len, &s, &c);
        tw[i].x = c;
        tw[i].y = s;
    }
    const lrx_c2* twx = tw;
    const lrx_c2* twy = tw + n0;
    const lrx_c2* twz = tw + n0 + n1;

    // --- PER-ROW METADATA.  The ONLY 64-bit div/mod in the kernel, and it
    //     runs RB times per block instead of RB·nk.  Row r decomposes as
    //     (i0,i1,i2,i3,i4) with i4 fastest; from that,
    //        W row  = (r / (d3·d4)) mod (d1·d2) = i1·d2 + i2
    //        dst(k) = dbase + k·kstride,  because
    //                 ((((i0·nk+k)·d3+i3)·d1+i1)·d4+i4)·d2+i2
    //               = i0·nk·kstride + k·kstride + ((i3·d1+i1)·d4+i4)·d2 + i2
    //     Rows past the end still decompose in range on i1..i4 (only i0 runs
    //     over), so the W offset is always a legal read and the store is
    //     guarded instead.
    for (int j = tid; j < RB; j += nthr) {
        long long q  = r0 + j;
        const long long i4 = q % d4; q /= d4;
        const long long i3 = q % d3; q /= d3;
        const long long i2 = q % d2; q /= d2;
        const long long i1 = q % d1; q /= d1;
        const long long i0 = q;
        meta[j]      = (i1 * d2 + i2) * nk;
        meta[RB + j] = i0 * (long long)nk * kstride
                     + ((i3 * d1 + i1) * d4 + i4) * d2 + i2;
    }

    // --- LOAD: flat and fully coalesced.  (j,k) advances INCREMENTALLY, so
    //     the loop carries no division; the one at entry is 32-bit. ---
    {
        int i = tid;
        int j = i / nk, k = i - j * nk;
        const int dj = nthr / nk, dk = nthr - dj * nk;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            lrx_c2 v;
            v.x = 0.0; v.y = 0.0;
            if (r < R) v = tin[r * (long long)nk + k];
            sm[(long long)j * SP + k] = v;
            k += dk;
            if (k >= nk) { k -= nk; j += 1; }
            j += dj;
        }
    }
    __syncthreads();

    lrx_c2* rowp = sm + (long long)threadIdx.y * SP;
    lrx_c2 acc[EPT];

    // --- the element's 3-D index, decomposed ONCE for all six passes ---
    int kx[EPT], ky[EPT], kz[EPT];
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        int t = lane + e * tpr;
        if (t >= nk) t = 0;                 // inactive lane: keep it in range
        kz[e] = t % n2; t /= n2;
        ky[e] = t % n1;
        kx[e] = t / n1;
    }

    // ================= THE SIX PASSES =================
    // A length-1 axis is the IDENTITY transform, so its pass is a shared-memory
    // round trip and two barriers that compute nothing.  Every 2-D k-grid the
    // BSE runs (3x3x1, 4x4x1) has one, and this kernel is SHARED-MEMORY
    // BANDWIDTH bound — measured 10-18 TB/s of an A100's ~19.5 TB/s roof — so
    // skipping them is not a micro-optimisation, it is 4 of the 22 shared
    // accesses per element at 3x3x1.  The conditions are kernel ARGUMENTS, so
    // every thread in the block takes the same arm and the __syncthreads()
    // inside them are reached uniformly.
#define LRX_MULT_W                                                            \
    {                                                                         \
        const lrx_c2* wp = wgt + meta[threadIdx.y];                           \
        _Pragma("unroll")                                                     \
        for (int e = 0; e < EPT; ++e) {                                       \
            const int k = lane + e * tpr;                                     \
            if (k < nk) {                                                     \
                const lrx_c2 w = wp[k];                                       \
                const double ar = acc[e].x, ai = acc[e].y;                    \
                acc[e].x = ar * w.x - ai * w.y;                               \
                acc[e].y = ar * w.y + ai * w.x;                               \
            }                                                                 \
        }                                                                     \
    }
#define LRX_SCALE                                                             \
    {                                                                         \
        _Pragma("unroll")                                                     \
        for (int e = 0; e < EPT; ++e) {                                       \
            acc[e].x *= scale;                                                \
            acc[e].y *= scale;                                                \
        }                                                                     \
    }
    // AX = axis index, TWV = its ring, LEN = its extent, SGN = direction,
    // FOLD = the thing fused into the LAST executed pass of this direction
    // (the W multiply on the inverse, the folded constant on the forward), so
    // neither ever costs a round trip of its own.
#define LRX_DO_PASS(AX, TWV, LEN, SGN, FOLD)                                  \
    if ((LEN) > 1) {                                                          \
        lrx_pass<EPT, AX>(rowp, TWV, nk, lane, tpr, n0, n1, n2,               \
                          kx, ky, kz, SGN, acc);                              \
        __syncthreads();                                                      \
        if (--rem == 0) { FOLD }                                              \
        lrx_writeback<EPT>(rowp, nk, lane, tpr, acc);                         \
        __syncthreads();                                                      \
    }

    const int nact = (n0 > 1) + (n1 > 1) + (n2 > 1);
    if (nact == 0) {
        // Every axis is length 1: both transforms are the identity and the
        // whole kernel is U = scale * T * W.  Stated rather than assumed —
        // with nact==0 the loops below would leave the W multiply and the
        // constant unapplied, silently.
        const lrx_c2* wp = wgt + meta[threadIdx.y];
#pragma unroll
        for (int e = 0; e < EPT; ++e) {
            const int k = lane + e * tpr;
            if (k < nk) {
                const lrx_c2 v = rowp[k], w = wp[k];
                rowp[k].x = (v.x * w.x - v.y * w.y) * scale;
                rowp[k].y = (v.x * w.y + v.y * w.x) * scale;
            }
        }
        __syncthreads();
    } else {
        int rem = nact;
        LRX_DO_PASS(2, twz, n2, -1.0, LRX_MULT_W)
        LRX_DO_PASS(1, twy, n1, -1.0, LRX_MULT_W)
        LRX_DO_PASS(0, twx, n0, -1.0, LRX_MULT_W)
        rem = nact;
        LRX_DO_PASS(2, twz, n2, 1.0, LRX_SCALE)
        LRX_DO_PASS(1, twy, n1, 1.0, LRX_SCALE)
        LRX_DO_PASS(0, twx, n0, 1.0, LRX_SCALE)
    }
#undef LRX_DO_PASS
#undef LRX_SCALE
#undef LRX_MULT_W

    // ============================ THE STORE ============================
    if (out_layout == 0) {
        // same layout as the operand: the flat map, mirror of the load.
        int i = tid;
        int j = i / nk, k = i - j * nk;
        const int dj = nthr / nk, dk = nthr - dj * nk;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            if (r < R) uout[r * (long long)nk + k] = sm[(long long)j * SP + k];
            k += dk;
            if (k >= nk) { k -= nk; j += 1; }
            j += dj;
        }
    } else {
        // (d0, nk, d3, d1, d4, d2): consecutive threads walk the ROW axis, so
        // consecutive d2 — the destination's MINOR axis — land adjacent.  A
        // block covering RB = nn·(d3·d4) consecutive rows therefore writes nn
        // contiguous elements per (k, d3, d4); RB is rounded to a multiple of
        // d3·d4 host-side for exactly this.
        int i = tid;
        int k = i / RB, j = i - k * RB;
        const int dk = nthr / RB, dj = nthr - dk * RB;
        for (; i < tile; i += nthr) {
            if (r0 + j < R) {
                uout[meta[RB + j] + (long long)k * kstride] =
                    sm[(long long)j * SP + k];
            }
            j += dj;
            if (j >= RB) { j -= RB; k += 1; }
            k += dk;
        }
    }
}

// ---------------------------------------------------------------------------
//  EIGHT ENTRY POINTS, one per EPT, instead of one kernel with a switch.
//
//  ptxas allocates registers for the WHOLE entry function, so a single kernel
//  switching over eight instantiations pays the EPT=8 arm's 148 registers on
//  every launch — and 148 registers x a 576-thread block is 85k registers
//  against the SM's 64k, i.e. a launch failure at the small grids where the
//  block is largest.  Separate entry points let each arm cost what it costs.
//
//  EPT is therefore NOT a kernel argument any more: it is the entry point's
//  identity.  The host picks the name from its own launch plan, so the two
//  cannot disagree.
//
//  __launch_bounds__(LRX_MAX_BLOCK) then makes the remaining case impossible
//  rather than merely unlikely: it tells ptxas the block will never exceed
//  that size, so it caps registers accordingly and every launch the host can
//  construct is guaranteed to fit.  The host's own block cap is the same
//  constant, named once on each side.
// ---------------------------------------------------------------------------
#define LRX_MAX_BLOCK 512

#define LRX_ENTRY(N)                                                          \
extern "C" __global__ __launch_bounds__(LRX_MAX_BLOCK)                        \
void lrx_conv_kminor_c128_e##N(                                               \
    const lrx_c2* tin,                  /* NOT __restrict__: may alias uout */\
    const lrx_c2* __restrict__ wgt,                                           \
    lrx_c2* uout,                                                             \
    long long R, long long MN,                                                \
    long long d1, long long d2, long long d3, long long d4,                   \
    int nk, int n0, int n1, int n2,                                           \
    int SP,                                                                   \
    double scale, int out_layout)                                             \
{                                                                             \
    extern __shared__ lrx_c2 sm[];                                            \
    lrx_conv_body<N>(tin, wgt, uout, R, d1, d2, d3, d4, nk,                   \
                     n0, n1, n2, SP, scale, out_layout, sm);                  \
}

LRX_ENTRY(1) LRX_ENTRY(2) LRX_ENTRY(3) LRX_ENTRY(4)
LRX_ENTRY(5) LRX_ENTRY(6) LRX_ENTRY(7) LRX_ENTRY(8)
#undef LRX_ENTRY

// ===========================================================================
//  ARM 2 of 2: CONTIGUOUS-OWNERSHIP.  Fewer shared-memory round trips.
// ===========================================================================
//  The strided arm above moves every element through shared memory SIX times
//  (once per axis pass), because a thread owning k = lane + e*tpr shares no
//  axis line with itself: every pass is a cross-thread read.  Measured, that
//  makes the kernel SHARED-MEMORY BANDWIDTH bound (10-18 TB/s of an A100's
//  roof) while HBM idles at 400-650 GB/s.
//
//  THE FIX: give a thread a CONTIGUOUS run of k, sized to one whole line along
//  the innermost non-trivial axis.  That axis's transform then sums over the
//  thread's OWN elements — no shared memory, no barrier — and only the
//  remaining axes stay cross-thread.  Shared accesses per element fall from
//  2 + 2*(n0+n1+n2) + 6 to 2 + 2*(sum of the CROSS axes) + 4.
//
//  THE PROBLEM THIS HAD TO SOLVE, and it is the whole reason the arm looks
//  like this.  A register array can only be indexed by a COMPILE-TIME
//  constant; index it with a runtime value and nvcc silently moves it to
//  LOCAL memory, which is DRAM behind L1 — strictly worse than the shared
//  memory it was meant to replace.  A thread owning a 2-D (y,z) plane needs
//  acc[(e/n2)*n2 + j], whose index depends on the runtime n2, so the plane
//  variant cannot be written without making n1 and n2 template parameters —
//  i.e. a per-size compiled family, which is exactly what this handler must
//  not have.
//
//  A LINE is different, and that is the insight the arm rests on: the DFT
//  along the owned axis sums over ALL of the thread's own elements, so the
//  inner loop runs s = 0..C-1 over the WHOLE register array.  Both the output
//  index o and the source index s are then compile-time loop counters of
//  unrolled loops, and the array stays in registers — with C, and every axis
//  extent, still a RUNTIME value.  One code path, no per-size compilation, any
//  (nkx,nky,nkz).
//
//  WHY THE TWIDDLE READS DO NOT GIVE THE SAVING BACK.  The intra-thread pass
//  reads twv[(o*s) mod C] from shared memory, which looks like it just trades
//  one shared access for another.  It does not: o, s and C are identical
//  across every lane of the warp at each unrolled step, so the address is
//  WARP-UNIFORM and the read is a broadcast — one transaction, not 32.  The
//  data reads it replaces were 32 distinct addresses.  Bandwidth, not
//  instruction count, is what binds here, so the trade is real.
//
//  CMAX is the compile-time capacity of the register arrays.  The host picks
//  the smallest instantiation with CMAX >= C and FALLS BACK TO THE STRIDED ARM
//  when C exceeds the largest — a plan-time selection, stated, with both arms
//  gated to the same reference.  Slots past C are never executed (the unrolled
//  loops `break`), so a loose fit costs only register footprint.
//
//  WHY CMAX STOPS AT 8, and it is measured, not chosen: the own-pass is an
//  O(CMAX^2) fully-unrolled body, so acc[]+tmp[] is 4*CMAX doubles and the
//  code grows quadratically.  ptxas reports ZERO spill at CMAX = 2, 4 and 8
//  and 1168 bytes of SPILL STORES at 16 under the 512-thread launch bound —
//  i.e. the 16 arm puts the very array this design exists to keep in registers
//  back into local memory, which would make it slower than the arm it
//  replaces.  Every k-grid in the campaign sweep has an innermost non-trivial
//  extent of 2, 3, 4 or 6, so all of them take this arm; grids with a larger
//  innermost axis take the strided arm and are correct, just not faster.
// ===========================================================================

//: One cross-thread axis pass, for a thread owning C contiguous elements.
//: The axis is described entirely by (len, stride, base0, mid): because the
//: owned run is a line along the INNERMOST non-trivial axis, every element of
//: the run has the same `mid` and its source base is simply base0 + o.  The
//: host derives those four numbers from (nkx,nky,nkz) and the thread's fixed
//: outer indices; the kernel does no division at all.
template <int CMAX>
__device__ __forceinline__ void lrx_ctg_cross(
    const lrx_c2* rowp, const lrx_c2* twv,
    int C, int len, int stride, int base0, int mid, double sgn,
    lrx_c2 (&acc)[CMAX])
{
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        const int b = base0 + o;
        double ar = 0.0, ai = 0.0;
        int m = 0;
        for (int j = 0; j < len; ++j) {
            const lrx_c2 v = rowp[b + j * stride];
            const lrx_c2 w = twv[m];
            const double wi = sgn * w.y;
            ar += v.x * w.x - v.y * wi;
            ai += v.x * wi + v.y * w.x;
            m += mid;
            if (m >= len) m -= len;
        }
        acc[o].x = ar;
        acc[o].y = ai;
    }
}

//: The INTRA-thread pass over the owned axis: no shared data traffic and no
//: barrier.  Both loop counters are compile-time, which is what keeps acc[]
//: and tmp[] in registers with C still a runtime value.
template <int CMAX>
__device__ __forceinline__ void lrx_ctg_own(
    const lrx_c2* twv, int C, double sgn, lrx_c2 (&acc)[CMAX])
{
    lrx_c2 tmp[CMAX];
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        double ar = 0.0, ai = 0.0;
        int m = 0;
#pragma unroll
        for (int s = 0; s < CMAX; ++s) {
            if (s >= C) break;
            const lrx_c2 v = acc[s];        // COMPILE-TIME index: registers
            const lrx_c2 w = twv[m];        // warp-uniform: a broadcast read
            const double wi = sgn * w.y;
            ar += v.x * w.x - v.y * wi;
            ai += v.x * wi + v.y * w.x;
            m += o;
            if (m >= C) m -= C;
        }
        tmp[o].x = ar;
        tmp[o].y = ai;
    }
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        acc[o] = tmp[o];
    }
}

template <int CMAX>
__device__ __forceinline__ void lrx_ctg_store_regs(
    lrx_c2* rowp, int C, int kbase, const lrx_c2 (&acc)[CMAX])
{
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        rowp[kbase + o] = acc[o];
    }
}

template <int CMAX>
__device__ __forceinline__ void lrx_conv_body_ctg(
    const lrx_c2* tin, const lrx_c2* __restrict__ wgt, lrx_c2* uout,
    long long R, long long d1, long long d2, long long d3, long long d4,
    int nk, int n0, int n1, int n2, int SP, int C, int oa,
    double scale, int out_layout, lrx_c2* sm)
{
    const int tpr  = blockDim.x;
    const int RB   = blockDim.y;
    const int tid  = threadIdx.y * tpr + threadIdx.x;
    const int nthr = tpr * RB;
    const int lane = threadIdx.x;
    const int ntw  = n0 + n1 + n2;
    const int tile = RB * nk;

    lrx_c2* tw = sm + (long long)RB * SP;
    long long* meta = (long long*)(tw + ntw);
    const long long r0 = (long long)blockIdx.x * RB;
    const long long kstride = d3 * d1 * d4 * d2;

    for (int i = tid; i < ntw; i += nthr) {
        int m, len;
        if (i < n0)            { m = i;           len = n0; }
        else if (i < n0 + n1)  { m = i - n0;      len = n1; }
        else                   { m = i - n0 - n1; len = n2; }
        double s, c;
        sincospi(-2.0 * (double)m / (double)len, &s, &c);
        tw[i].x = c;
        tw[i].y = s;
    }
    const lrx_c2* twx = tw;
    const lrx_c2* twy = tw + n0;
    const lrx_c2* twz = tw + n0 + n1;

    for (int j = tid; j < RB; j += nthr) {
        long long q  = r0 + j;
        const long long i4 = q % d4; q /= d4;
        const long long i3 = q % d3; q /= d3;
        const long long i2 = q % d2; q /= d2;
        const long long i1 = q % d1; q /= d1;
        const long long i0 = q;
        meta[j]      = (i1 * d2 + i2) * nk;
        meta[RB + j] = i0 * (long long)nk * kstride
                     + ((i3 * d1 + i1) * d4 + i4) * d2 + i2;
    }

    {   // coalesced global -> shared, identical to the strided arm
        int i = tid;
        int j = i / nk, k = i - j * nk;
        const int dj = nthr / nk, dk = nthr - dj * nk;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            lrx_c2 v;
            v.x = 0.0; v.y = 0.0;
            if (r < R) v = tin[r * (long long)nk + k];
            sm[(long long)j * SP + k] = v;
            k += dk;
            if (k >= nk) { k -= nk; j += 1; }
            j += dj;
        }
    }
    __syncthreads();

    lrx_c2* rowp = sm + (long long)threadIdx.y * SP;
    const int kbase = lane * C;

    // --- THE THREAD'S FIXED OUTER INDICES.  The owned run is a line along the
    //     innermost non-trivial axis, so the two outer indices are CONSTANT
    //     over the run — no per-slot decomposition, no per-slot division, and
    //     no index arrays competing with acc[] for registers.
    int ix = 0, iy = 0;
    if (oa == 2)      { ix = lane / n1; iy = lane - ix * n1; }
    else if (oa == 1) { ix = lane; }
    // oa == 0: the whole row belongs to this thread; ix, iy unused.

    // Cross-axis descriptors (len, stride, base0, mid), derived once.  See the
    // header for the algebra; each is exact, not an approximation of it.
    int yc_len = 0, yc_str = 0, yc_b0 = 0, yc_mid = 0;
    int xc_len = 0, xc_str = 0, xc_b0 = 0, xc_mid = 0;
    if (oa == 2) {
        if (n1 > 1) { yc_len = n1; yc_str = n2; yc_b0 = ix * n1 * n2; yc_mid = iy; }
        if (n0 > 1) { xc_len = n0; xc_str = n1 * n2; xc_b0 = iy * n2;  xc_mid = ix; }
    } else if (oa == 1) {
        if (n0 > 1) { xc_len = n0; xc_str = n1;      xc_b0 = 0;        xc_mid = ix; }
    }

    lrx_c2 acc[CMAX];
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        acc[o] = rowp[kbase + o];
    }

    // ===================== INVERSE (unnormalised, sgn = -1) =====================
    if (C > 1) {
        lrx_ctg_own<CMAX>((oa == 2) ? twz : ((oa == 1) ? twy : twx),
                          C, -1.0, acc);
    }
    if (yc_len > 1) {
        __syncthreads();                       // everyone has read; safe to write
        lrx_ctg_store_regs<CMAX>(rowp, C, kbase, acc);
        __syncthreads();
        lrx_ctg_cross<CMAX>(rowp, twy, C, yc_len, yc_str, yc_b0, yc_mid,
                            -1.0, acc);
    }
    if (xc_len > 1) {
        __syncthreads();
        lrx_ctg_store_regs<CMAX>(rowp, C, kbase, acc);
        __syncthreads();
        lrx_ctg_cross<CMAX>(rowp, twx, C, xc_len, xc_str, xc_b0, xc_mid,
                            -1.0, acc);
    }

    // --- the stored kernel's multiply, in registers between the halves ---
    {
        const lrx_c2* wp = wgt + meta[threadIdx.y] + kbase;
#pragma unroll
        for (int o = 0; o < CMAX; ++o) {
            if (o >= C) break;
            const lrx_c2 w = wp[o];
            const double ar = acc[o].x, ai = acc[o].y;
            acc[o].x = ar * w.x - ai * w.y;
            acc[o].y = ar * w.y + ai * w.x;
        }
    }

    // ===================== FORWARD (unnormalised, sgn = +1) =====================
    if (xc_len > 1) {
        __syncthreads();
        lrx_ctg_store_regs<CMAX>(rowp, C, kbase, acc);
        __syncthreads();
        lrx_ctg_cross<CMAX>(rowp, twx, C, xc_len, xc_str, xc_b0, xc_mid,
                            1.0, acc);
    }
    if (yc_len > 1) {
        __syncthreads();
        lrx_ctg_store_regs<CMAX>(rowp, C, kbase, acc);
        __syncthreads();
        lrx_ctg_cross<CMAX>(rowp, twy, C, yc_len, yc_str, yc_b0, yc_mid,
                            1.0, acc);
    }
    if (C > 1) {
        lrx_ctg_own<CMAX>((oa == 2) ? twz : ((oa == 1) ? twy : twx),
                          C, 1.0, acc);
    }

    // --- the single folded constant, applied once on the way back out ---
#pragma unroll
    for (int o = 0; o < CMAX; ++o) {
        if (o >= C) break;
        acc[o].x *= scale;
        acc[o].y *= scale;
    }
    __syncthreads();
    lrx_ctg_store_regs<CMAX>(rowp, C, kbase, acc);
    __syncthreads();

    // ============================ THE STORE ============================
    // Byte-identical to the strided arm's: the store pattern is a property of
    // the OUTPUT layout, not of how the transform was decomposed.
    if (out_layout == 0) {
        int i = tid;
        int j = i / nk, k = i - j * nk;
        const int dj = nthr / nk, dk = nthr - dj * nk;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            if (r < R) uout[r * (long long)nk + k] = sm[(long long)j * SP + k];
            k += dk;
            if (k >= nk) { k -= nk; j += 1; }
            j += dj;
        }
    } else {
        int i = tid;
        int k = i / RB, j = i - k * RB;
        const int dk = nthr / RB, dj = nthr - dk * RB;
        for (; i < tile; i += nthr) {
            if (r0 + j < R) {
                uout[meta[RB + j] + (long long)k * kstride] =
                    sm[(long long)j * SP + k];
            }
            j += dj;
            if (j >= RB) { j -= RB; k += 1; }
            k += dk;
        }
    }
}

#define LRX_ENTRY_CTG(N)                                                      \
extern "C" __global__ __launch_bounds__(LRX_MAX_BLOCK)                        \
void lrx_conv_kminor_c128_ctg##N(                                             \
    const lrx_c2* tin,                                                        \
    const lrx_c2* __restrict__ wgt,                                           \
    lrx_c2* uout,                                                             \
    long long R, long long MN,                                                \
    long long d1, long long d2, long long d3, long long d4,                   \
    int nk, int n0, int n1, int n2,                                           \
    int SP, int C, int oa,                                                    \
    double scale, int out_layout)                                             \
{                                                                             \
    extern __shared__ lrx_c2 sm[];                                            \
    lrx_conv_body_ctg<N>(tin, wgt, uout, R, d1, d2, d3, d4, nk,               \
                         n0, n1, n2, SP, C, oa, scale, out_layout, sm);       \
}

LRX_ENTRY_CTG(2) LRX_ENTRY_CTG(4) LRX_ENTRY_CTG(8)
#undef LRX_ENTRY_CTG

