// GENERATED from /pscratch/sd/j/jackm/wt_hybrid_wiring_2026-08-29/src/ffi/cpp/cufft/conv_kpair_cuda_ffi.cc; do not edit this file.

struct __align__(16) lrx_c2 { double x, y; };

__device__ __forceinline__ lrx_c2 lrx_mul(lrx_c2 a, lrx_c2 b) {
    lrx_c2 z = {a.x*b.x - a.y*b.y, a.x*b.y + a.y*b.x};
    return z;
}

__device__ __forceinline__ lrx_c2 lrx_phase(lrx_c2 z, int code) {
    if (code == 1) { lrx_c2 q = {-z.y, z.x}; return q; }
    if (code == 2) { lrx_c2 q = {-z.x, -z.y}; return q; }
    if (code == 3) { lrx_c2 q = {z.y, -z.x}; return q; }
    return z;
}

template <int EPT, int AXIS>
__device__ __forceinline__ void lrx_pass(
    const lrx_c2* row, const lrx_c2* tw,
    int nk, int lane, int tpr, int n0, int n1, int n2,
    const int (&kx)[EPT], const int (&ky)[EPT], const int (&kz)[EPT],
    double sign, lrx_c2 (&out)[EPT]) {
    const int len = AXIS == 0 ? n0 : (AXIS == 1 ? n1 : n2);
    const int stride = AXIS == 0 ? n1*n2 : (AXIS == 1 ? n2 : 1);
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e*tpr;
        if (k < nk) {
            int base, freq;
            if (AXIS == 0) {
                base = ky[e]*n2 + kz[e]; freq = kx[e];
            } else if (AXIS == 1) {
                base = kx[e]*n1*n2 + kz[e]; freq = ky[e];
            } else {
                base = (kx[e]*n1 + ky[e])*n2; freq = kz[e];
            }
            double ar = 0.0, ai = 0.0;
            int m = 0;
            for (int j = 0; j < len; ++j) {
                const lrx_c2 v = row[base + j*stride];
                const lrx_c2 w = tw[m];
                const double wi = sign*w.y;
                ar += v.x*w.x - v.y*wi;
                ai += v.x*wi + v.y*w.x;
                m += freq;
                if (m >= len) m -= len;
            }
            out[e].x = ar; out[e].y = ai;
        }
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_write(
    lrx_c2* row, int nk, int lane, int tpr, const lrx_c2 (&v)[EPT]) {
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e*tpr;
        if (k < nk) row[k] = v[e];
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_transform_resident(
    lrx_c2* row, const lrx_c2* twx, const lrx_c2* twy,
    const lrx_c2* twz, int nk, int n0, int n1, int n2, double sign) {
    const int lane = threadIdx.x;
    const int tpr = blockDim.x;
    int kx[EPT], ky[EPT], kz[EPT];
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        int k = lane + e*tpr;
        if (k >= nk) k = 0;
        kz[e] = k % n2; k /= n2;
        ky[e] = k % n1; kx[e] = k / n1;
    }
    lrx_c2 v[EPT];
#define LRX_AXIS(A,TW,LEN)                                             \
    if ((LEN) > 1) {                                                   \
        lrx_pass<EPT,A>(row,TW,nk,lane,tpr,n0,n1,n2,kx,ky,kz,sign,v); \
        __syncthreads();                                               \
        lrx_write<EPT>(row,nk,lane,tpr,v);                             \
        __syncthreads();                                               \
    }
    LRX_AXIS(2,twz,n2)
    LRX_AXIS(1,twy,n1)
    LRX_AXIS(0,twx,n0)
#undef LRX_AXIS
}

template <int EPT>
__device__ __forceinline__ void lrx_transform_resident_pair(
    lrx_c2* arow,lrx_c2* brow,const lrx_c2* twx,const lrx_c2* twy,
    const lrx_c2* twz,int nk,int n0,int n1,int n2,double sign) {
    const int lane=threadIdx.x,tpr=blockDim.x;
    int kx[EPT],ky[EPT],kz[EPT];
#pragma unroll
    for (int e=0;e<EPT;++e) {
        int k=lane+e*tpr;
        if (k>=nk) k=0;
        kz[e]=k%n2;k/=n2;ky[e]=k%n1;kx[e]=k/n1;
    }
    lrx_c2 av[EPT],bv[EPT];
    // The two banks have no dependency before the R-space multiply.  Sharing
    // each barrier avoids serializing identical transform schedules.
#define LRX_PAIR_AXIS(A,TW,LEN)                                      \
    if ((LEN)>1) {                                                   \
        lrx_pass<EPT,A>(arow,TW,nk,lane,tpr,n0,n1,n2,kx,ky,kz,sign,av); \
        lrx_pass<EPT,A>(brow,TW,nk,lane,tpr,n0,n1,n2,kx,ky,kz,sign,bv); \
        __syncthreads();                                             \
        lrx_write<EPT>(arow,nk,lane,tpr,av);                         \
        lrx_write<EPT>(brow,nk,lane,tpr,bv);                         \
        __syncthreads();                                             \
    }
    LRX_PAIR_AXIS(2,twz,n2)
    LRX_PAIR_AXIS(1,twy,n1)
    LRX_PAIR_AXIS(0,twx,n0)
#undef LRX_PAIR_AXIS
}

template <int EPT>
__device__ __forceinline__ void lrx_resident_body(
    const lrx_c2* ain, const lrx_c2* bin, lrx_c2* uout,
    long long rows, int ns, int nk, int n0, int n1, int n2, int sp,
    double scale, unsigned long long perm_l, unsigned long long phase_l,
    unsigned long long perm_r, unsigned long long phase_r, lrx_c2* sm) {
    const int tpr = blockDim.x;
    const int rb = blockDim.y;
    const int tid = threadIdx.y*tpr + threadIdx.x;
    const int nthr = tpr*rb;
    const long long r0 = (long long)blockIdx.x*rb;
    const int ntw = n0+n1+n2;
    const int banks = ns == 1 ? 2 : 3;
    lrx_c2* abank = sm;
    lrx_c2* bbank = abank + (long long)rb*sp;
    lrx_c2* accum = ns == 1 ? abank : bbank + (long long)rb*sp;
    lrx_c2* tw = sm + (long long)banks*rb*sp;

    // O(axis) rings serve every row and spin pair; runtime lengths cover
    // primes without a radix table or per-grid compilation.
    for (int i = tid; i < ntw; i += nthr) {
        int m, len;
        if (i < n0) { m=i; len=n0; }
        else if (i < n0+n1) { m=i-n0; len=n1; }
        else { m=i-n0-n1; len=n2; }
        double s,c; sincospi(-2.0*(double)m/(double)len,&s,&c);
        tw[i].x=c; tw[i].y=s;
    }
    __syncthreads();
    const lrx_c2* twx=tw;
    const lrx_c2* twy=tw+n0;
    const lrx_c2* twz=tw+n0+n1;

    for (int a = 0; a < ns; ++a) {
        const int ap = (perm_l >> (4*a)) & 15;
        const int pc_l = (phase_l >> (2*a)) & 3;
        for (int b = 0; b < ns; ++b) {
            const int bp = (perm_r >> (4*b)) & 15;
            const int pc = (pc_l + ((phase_r >> (2*b)) & 3)) & 3;
            const int tile = rb*nk;
            for (int i = tid; i < tile; i += nthr) {
                const int k = i/rb;
                const int j = i-k*rb;
                const long long row = r0+j;
                lrx_c2 av={0.0,0.0}, bv={0.0,0.0};
                if (row < rows) {
                    const long long base = (long long)k*ns*rows*ns;
                    av=ain[base + (long long)a*rows*ns + row*ns + b];
                    bv=bin[base + (long long)ap*rows*ns + row*ns + bp];
                }
                abank[(long long)j*sp+k]=av;
                bbank[(long long)j*sp+k]=bv;
            }
            __syncthreads();
            lrx_c2* ar=abank+(long long)threadIdx.y*sp;
            lrx_c2* br=bbank+(long long)threadIdx.y*sp;
            lrx_transform_resident_pair<EPT>(
                ar,br,twx,twy,twz,nk,n0,n1,n2,-1.0);
            for (int k=threadIdx.x;k<nk;k+=tpr) {
                const lrx_c2 ac={ar[k].x,-ar[k].y};
                const lrx_c2 term=lrx_phase(lrx_mul(ac,br[k]),pc);
                lrx_c2* dst=accum+(long long)threadIdx.y*sp+k;
                if (a==0&&b==0) *dst=term;
                else {dst->x+=term.x;dst->y+=term.y;}
            }
            __syncthreads();
        }
    }

    lrx_c2* outrow=accum+(long long)threadIdx.y*sp;
    lrx_transform_resident<EPT>(outrow,twx,twy,twz,nk,n0,n1,n2,1.0);
    for (int i = tid; i < rb*nk; i += nthr) {
        const int k=i/rb;
        const int j=i-k*rb;
        const long long row=r0+j;
        if (row < rows) {
            const lrx_c2 v=accum[(long long)j*sp+k];
            uout[(long long)k*rows+row]={v.x*scale,v.y*scale};
        }
    }
}

// Global-workspace line transforms are the coverage arm, not the small-grid
// throughput arm.  One block owns a row for the entire kernel, so every
// barrier is row-local and no grid synchronization or collective is needed.
__device__ __forceinline__ void lrx_axis_pair(
    lrx_c2* wa, lrx_c2* wb, int n0, int n1, int n2, int axis,
    double sign, lrx_c2* lines_a, lrx_c2* lines_b, const lrx_c2* tw) {
    const int lane=threadIdx.x&31;
    const int warp=threadIdx.x>>5;
    const int nwarp=blockDim.x>>5;
    const int len=axis==0?n0:(axis==1?n1:n2);
    const int nline=axis==0?n1*n2:(axis==1?n0*n2:n0*n1);
    lrx_c2* line_a=lines_a+warp*24;
    lrx_c2* line_b=lines_b+warp*24;
    // One warp owns one line at a time.  Line lengths never exceed 24, so
    // no inter-warp dependency exists and inactive lanes stay spectators.
    for (int line=warp; line<nline; line+=nwarp) {
        int base,stride;
        if (axis==0) { base=line; stride=n1*n2; }
        else if (axis==1) {
            const int x=line/n2,z=line-x*n2;
            base=x*n1*n2+z; stride=n2;
        } else { base=line*n2; stride=1; }
        if (lane < len) {
            line_a[lane]=wa[base+lane*stride];
            line_b[lane]=wb[base+lane*stride];
        }
        __syncwarp();
        lrx_c2 oa={0.0,0.0},ob={0.0,0.0};
        if (lane < len) {
            int m=0;
            for (int j=0;j<len;++j) {
                const lrx_c2 w=tw[m];
                const double wi=sign*w.y;
                const lrx_c2 va=line_a[j],vb=line_b[j];
                oa.x += va.x*w.x-va.y*wi; oa.y += va.x*wi+va.y*w.x;
                ob.x += vb.x*w.x-vb.y*wi; ob.y += vb.x*wi+vb.y*w.x;
                m += lane; if (m >= len) m -= len;
            }
        }
        __syncwarp();
        if (lane < len) {
            wa[base+lane*stride]=oa;
            wb[base+lane*stride]=ob;
        }
        __syncwarp();
    }
    // The next axis consumes every line written by this axis.
    __syncthreads();
}

__device__ __forceinline__ void lrx_axis_one(
    lrx_c2* work, int n0, int n1, int n2, int axis,
    double sign, lrx_c2* lines, const lrx_c2* tw) {
    const int lane=threadIdx.x&31;
    const int warp=threadIdx.x>>5;
    const int nwarp=blockDim.x>>5;
    const int len=axis==0?n0:(axis==1?n1:n2);
    const int nline=axis==0?n1*n2:(axis==1?n0*n2:n0*n1);
    lrx_c2* line=lines+warp*24;
    for (int li=warp;li<nline;li+=nwarp) {
        int base,stride;
        if (axis==0) { base=li; stride=n1*n2; }
        else if (axis==1) {
            const int x=li/n2,z=li-x*n2;
            base=x*n1*n2+z; stride=n2;
        } else { base=li*n2; stride=1; }
        if (lane < len) line[lane]=work[base+lane*stride];
        __syncwarp();
        lrx_c2 out={0.0,0.0};
        if (lane < len) {
            int m=0;
            for (int j=0;j<len;++j) {
                const lrx_c2 w=tw[m],v=line[j];
                const double wi=sign*w.y;
                out.x += v.x*w.x-v.y*wi; out.y += v.x*wi+v.y*w.x;
                m += lane; if (m >= len) m -= len;
            }
        }
        __syncwarp();
        if (lane < len) work[base+lane*stride]=out;
        __syncwarp();
    }
    __syncthreads();
}

extern "C" __global__ void lrx_pair_stage1(
    const lrx_c2* ain, const lrx_c2* bin, lrx_c2* wa_all,
    lrx_c2* wb_all, lrx_c2* tmp, long long rows, int ns, int nk,
    int n0, int n1, int n2, unsigned long long perm_l,
    unsigned long long phase_l, unsigned long long perm_r,
    unsigned long long phase_r) {
    extern __shared__ lrx_c2 sm[];
    const long long row=blockIdx.x;
    if (row >= rows) return;
    const int nwarp=blockDim.x>>5;
    lrx_c2* line_a=sm;
    lrx_c2* line_b=line_a+nwarp*24;
    lrx_c2* tw=line_b+nwarp*24;
    for (int i=threadIdx.x;i<n0+n1+n2;i+=blockDim.x) {
        int m,len;
        if (i<n0) {m=i;len=n0;}
        else if (i<n0+n1) {m=i-n0;len=n1;}
        else {m=i-n0-n1;len=n2;}
        double s,c;sincospi(-2.0*(double)m/(double)len,&s,&c);
        tw[i]={c,s};
    }
    __syncthreads();
    lrx_c2* wa=wa_all+row*nk;
    lrx_c2* wb=wb_all+row*nk;
    for (int a=0;a<ns;++a) {
        const int ap=(perm_l>>(4*a))&15;
        const int pcl=(phase_l>>(2*a))&3;
        for (int b=0;b<ns;++b) {
            const int bp=(perm_r>>(4*b))&15;
            const int pc=(pcl+((phase_r>>(2*b))&3))&3;
            for (int k=threadIdx.x;k<nk;k+=blockDim.x) {
                const long long base=(long long)k*ns*rows*ns;
                wa[k]=ain[base+(long long)a*rows*ns+row*ns+b];
                wb[k]=bin[base+(long long)ap*rows*ns+row*ns+bp];
            }
            __syncthreads();
            lrx_axis_pair(wa,wb,n0,n1,n2,2,-1.0,line_a,line_b,tw+n0+n1);
            lrx_axis_pair(wa,wb,n0,n1,n2,1,-1.0,line_a,line_b,tw+n0);
            lrx_axis_pair(wa,wb,n0,n1,n2,0,-1.0,line_a,line_b,tw);
            for (int k=threadIdx.x;k<nk;k+=blockDim.x) {
                lrx_c2 ac={wa[k].x,-wa[k].y};
                lrx_c2 term=lrx_phase(lrx_mul(ac,wb[k]),pc);
                lrx_c2* dst=tmp+row*nk+k;
                if (a==0 && b==0) *dst=term;
                else {dst->x+=term.x;dst->y+=term.y;}
            }
            __syncthreads();
        }
    }
}

extern "C" __global__ void lrx_pair_stage2(
    lrx_c2* tmp, lrx_c2* uout, long long rows, int nk,
    int n0, int n1, int n2, double scale) {
    extern __shared__ lrx_c2 sm[];
    const long long row=blockIdx.x;
    if (row >= rows) return;
    const int nwarp=blockDim.x>>5;
    lrx_c2* line=sm;
    lrx_c2* tw=line+nwarp*24;
    for (int i=threadIdx.x;i<n0+n1+n2;i+=blockDim.x) {
        int m,len;
        if (i<n0) {m=i;len=n0;}
        else if (i<n0+n1) {m=i-n0;len=n1;}
        else {m=i-n0-n1;len=n2;}
        double s,c;sincospi(-2.0*(double)m/(double)len,&s,&c);
        tw[i]={c,s};
    }
    __syncthreads();
    lrx_c2* work=tmp+row*nk;
    lrx_axis_one(work,n0,n1,n2,2,1.0,line,tw+n0+n1);
    lrx_axis_one(work,n0,n1,n2,1,1.0,line,tw+n0);
    lrx_axis_one(work,n0,n1,n2,0,1.0,line,tw);
    for (int k=threadIdx.x;k<nk;k+=blockDim.x) {
        const lrx_c2 v=work[k];
        uout[(long long)k*rows+row]={v.x*scale,v.y*scale};
    }
}

#define LRX_ENTRY(N)                                                    \
extern "C" __global__ __launch_bounds__(512)                          \
void lrx_pair_resident_e##N(                                           \
    const lrx_c2* a,const lrx_c2* b,lrx_c2* u,long long rows,int ns,   \
    int nk,int n0,int n1,int n2,int sp,double scale,                   \
    unsigned long long pl,unsigned long long hl,                       \
    unsigned long long pr,unsigned long long hr) {                     \
    extern __shared__ lrx_c2 sm[];                                     \
    lrx_resident_body<N>(a,b,u,rows,ns,nk,n0,n1,n2,sp,scale,           \
                         pl,hl,pr,hr,sm);                               \
}
LRX_ENTRY(1) LRX_ENTRY(2) LRX_ENTRY(3) LRX_ENTRY(4)
LRX_ENTRY(5) LRX_ENTRY(6) LRX_ENTRY(7) LRX_ENTRY(8)
LRX_ENTRY(9) LRX_ENTRY(10) LRX_ENTRY(11) LRX_ENTRY(12)
LRX_ENTRY(13) LRX_ENTRY(14) LRX_ENTRY(15) LRX_ENTRY(16)
#undef LRX_ENTRY

