// GENERATED from /pscratch/sd/j/jackm/wt_hybrid_wiring_2026-08-29/src/ffi/cpp/cufft/conv_klead_cuda_ffi.cc; do not edit this file.

struct __align__(16) lrx_c2 { double x, y; };

template <int EPT, int AXIS>
__device__ __forceinline__ void lrx_pass(
    const lrx_c2* rowp, const lrx_c2* twv,
    int nk, int lane, int tpr, int n0, int n1, int n2,
    const int (&kx)[EPT], const int (&ky)[EPT], const int (&kz)[EPT],
    double sgn, lrx_c2 (&acc)[EPT])
{
    const int len = (AXIS == 0) ? n0 : ((AXIS == 1) ? n1 : n2);
    const int stride = (AXIS == 0) ? (n1 * n2) : ((AXIS == 1) ? n2 : 1);
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e * tpr;
        if (k < nk) {
            int base, mid;
            if (AXIS == 0) {
                base = ky[e] * n2 + kz[e]; mid = kx[e];
            } else if (AXIS == 1) {
                base = kx[e] * n1 * n2 + kz[e]; mid = ky[e];
            } else {
                base = (kx[e] * n1 + ky[e]) * n2; mid = kz[e];
            }
            double ar = 0.0, ai = 0.0;
            int m = 0;
            for (int j = 0; j < len; ++j) {
                const lrx_c2 v = rowp[base + j * stride];
                const lrx_c2 w = twv[m];
                const double wi = sgn * w.y;
                ar += v.x * w.x - v.y * wi;
                ai += v.x * wi + v.y * w.x;
                m += mid;
                if (m >= len) m -= len;
            }
            acc[e].x = ar;
            acc[e].y = ai;
        }
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_writeback(
    lrx_c2* rowp, int nk, int lane, int tpr, const lrx_c2 (&acc)[EPT])
{
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        const int k = lane + e * tpr;
        if (k < nk) rowp[k] = acc[e];
    }
}

template <int EPT>
__device__ __forceinline__ void lrx_conv_body(
    const lrx_c2* tin, const lrx_c2* __restrict__ wgt, lrx_c2* uout,
    long long Tg, long long Tv, long long mx, long long b, long long my,
    int nk, int n0, int n1, int n2, int SP, double scale, lrx_c2* sm)
{
    const int tpr = blockDim.x;
    const int RB = blockDim.y;
    const int tid = threadIdx.y * tpr + threadIdx.x;
    const int nthr = tpr * RB;
    const int lane = threadIdx.x;
    const int ntw = n0 + n1 + n2;
    const int tile = RB * nk;
    const long long r0 = (long long)blockIdx.x * RB;

    lrx_c2* ts = sm;
    lrx_c2* ws = ts + (long long)RB * SP;
    lrx_c2* tw = ws + (long long)RB * SP;
    long long* wrow = (long long*)(tw + ntw);

    // Store O(n) twiddle rings; lrx_pass advances (mid*j)%len by add/sub.
    // This avoids an O(n^2) table and per-size radix specializations in the
    // validated <=24 envelope.
    for (int i = tid; i < ntw; i += nthr) {
        int m, len;
        if (i < n0) { m = i; len = n0; }
        else if (i < n0 + n1) { m = i - n0; len = n1; }
        else { m = i - n0 - n1; len = n2; }
        double s, c;
        sincospi(-2.0 * (double)m / (double)len, &s, &c);
        tw[i].x = c;
        tw[i].y = s;
    }
    const lrx_c2* twx = tw;
    const lrx_c2* twy = tw + n0;
    const lrx_c2* twz = tw + n0 + n1;

    // One 64-bit decomposition per ROW, not per k element.  T's trailing
    // order is (a,mx,b,my); W's is (mx,my).
    for (int j = tid; j < RB; j += nthr) {
        long long q = r0 + j;
        const long long iy = q % my; q /= my;
        q /= b;
        const long long ix = q % mx;
        wrow[j] = ix * my + iy;
    }
    __syncthreads();

    // In-place T/U aliasing is safe: each block stages the complete T rows for
    // its disjoint row set before any output store, and blocks never read one
    // another's rows.
    // T stays k-leading across the FFI.  Flattened threads keep j fast, so
    // each fixed-k group reads consecutive mu-nu-major global elements.  The
    // scatter into odd-stride ts[j,k] is the in-SMEM transpose and ts itself
    // remains the resident transform bank: no second staging tile or barrier.
    {
        int i = tid;
        int k = i / RB, j = i - k * RB;
        const int dk = nthr / RB, dj = nthr - dk * RB;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            lrx_c2 tv = {0.0, 0.0};
            if (r < Tg) tv = tin[(long long)k * Tg + r];
            ts[(long long)j * SP + k] = tv;
            j += dj;
            if (j >= RB) { j -= RB; k += 1; }
            k += dk;
        }
    }
    {
        int i = tid;
        int k = i / RB, j = i - k * RB;
        const int dk = nthr / RB, dj = nthr - dk * RB;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            lrx_c2 wv = {0.0, 0.0};
            if (r < Tg) {
                wv = wgt[(long long)k * Tv + wrow[j]];
            }
            ws[(long long)j * SP + k] = wv;
            j += dj;
            if (j >= RB) { j -= RB; k += 1; }
            k += dk;
        }
    }
    __syncthreads();

    lrx_c2* trow = ts + (long long)threadIdx.y * SP;
    lrx_c2* wline = ws + (long long)threadIdx.y * SP;
    lrx_c2 ta[EPT], wa[EPT];
    int kx[EPT], ky[EPT], kz[EPT];
#pragma unroll
    for (int e = 0; e < EPT; ++e) {
        int k = lane + e * tpr;
        if (k >= nk) k = 0;
        kz[e] = k % n2; k /= n2;
        ky[e] = k % n1;
        kx[e] = k / n1;
    }

#define LRX_MULT                                                    \
    {                                                               \
        _Pragma("unroll")                                          \
        for (int e = 0; e < EPT; ++e) {                             \
            const int k = lane + e * tpr;                           \
            if (k < nk) {                                           \
                const double ar = ta[e].x, ai = ta[e].y;            \
                ta[e].x = ar * wa[e].x - ai * wa[e].y;              \
                ta[e].y = ar * wa[e].y + ai * wa[e].x;              \
            }                                                       \
        }                                                           \
    }
#define LRX_SCALE                                                   \
    {                                                               \
        _Pragma("unroll")                                          \
        for (int e = 0; e < EPT; ++e) {                             \
            ta[e].x *= scale;                                       \
            ta[e].y *= scale;                                       \
        }                                                           \
    }
#define LRX_INVERSE_PASS(AX, TWV, LEN)                              \
    if ((LEN) > 1) {                                                \
        lrx_pass<EPT, AX>(trow, TWV, nk, lane, tpr, n0, n1, n2,    \
                          kx, ky, kz, -1.0, ta);                    \
        lrx_pass<EPT, AX>(wline, TWV, nk, lane, tpr, n0, n1, n2,  \
                          kx, ky, kz, -1.0, wa);                    \
        __syncthreads();                                            \
        if (--rem == 0) { LRX_MULT }                               \
        lrx_writeback<EPT>(trow, nk, lane, tpr, ta);               \
        if (rem != 0) lrx_writeback<EPT>(wline, nk, lane, tpr, wa);\
        __syncthreads();                                            \
    }
#define LRX_FORWARD_PASS(AX, TWV, LEN)                              \
    if ((LEN) > 1) {                                                \
        lrx_pass<EPT, AX>(trow, TWV, nk, lane, tpr, n0, n1, n2,    \
                          kx, ky, kz, 1.0, ta);                     \
        __syncthreads();                                            \
        if (--rem == 0) { LRX_SCALE }                              \
        lrx_writeback<EPT>(trow, nk, lane, tpr, ta);               \
        __syncthreads();                                            \
    }

    const int nact = (n0 > 1) + (n1 > 1) + (n2 > 1);
    if (nact == 0) {
#pragma unroll
        for (int e = 0; e < EPT; ++e) {
            const int k = lane + e * tpr;
            if (k < nk) {
                const lrx_c2 t = trow[k], w = wline[k];
                trow[k].x = (t.x * w.x - t.y * w.y) * scale;
                trow[k].y = (t.x * w.y + t.y * w.x) * scale;
            }
        }
        __syncthreads();
    } else {
        int rem = nact;
        LRX_INVERSE_PASS(2, twz, n2)
        LRX_INVERSE_PASS(1, twy, n1)
        LRX_INVERSE_PASS(0, twx, n0)
        rem = nact;
        LRX_FORWARD_PASS(2, twz, n2)
        LRX_FORWARD_PASS(1, twy, n1)
        LRX_FORWARD_PASS(0, twx, n0)
    }
#undef LRX_FORWARD_PASS
#undef LRX_INVERSE_PASS
#undef LRX_SCALE
#undef LRX_MULT

    // row-major shared -> k-leading global, the mirror of the load.  The
    // output stays in the exact layout Sigma's projection consumes.
    {
        int i = tid;
        int k = i / RB, j = i - k * RB;
        const int dk = nthr / RB, dj = nthr - dk * RB;
        for (; i < tile; i += nthr) {
            const long long r = r0 + j;
            if (r < Tg) {
                uout[(long long)k * Tg + r] =
                    ts[(long long)j * SP + k];
            }
            j += dj;
            if (j >= RB) { j -= RB; k += 1; }
            k += dk;
        }
    }
}

#define LRX_MAX_BLOCK 512
#define LRX_ENTRY(N)                                                     \
extern "C" __global__ __launch_bounds__(LRX_MAX_BLOCK)                  \
void lrx_conv_klead_c128_e##N(                                          \
    const lrx_c2* tin, const lrx_c2* __restrict__ wgt, lrx_c2* uout,    \
    long long Tg, long long Tv, long long mx, long long b, long long my,\
    int nk, int n0, int n1, int n2, int SP, double scale)               \
{                                                                        \
    extern __shared__ lrx_c2 sm[];                                      \
    lrx_conv_body<N>(tin, wgt, uout, Tg, Tv, mx, b, my, nk,             \
                     n0, n1, n2, SP, scale, sm);                         \
}

LRX_ENTRY(1) LRX_ENTRY(2) LRX_ENTRY(3) LRX_ENTRY(4)
LRX_ENTRY(5) LRX_ENTRY(6) LRX_ENTRY(7) LRX_ENTRY(8)
#undef LRX_ENTRY

