# Extract the one authored NVRTC raw string into a CUDA translation unit.
#
# The handler source remains the single source of truth.  The sm_80 AOT build
# consumes this generated file; the runtime fallback consumes kKernelSrc from
# the same handler source.
if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR
        "extract_nvrtc_kernel: INPUT does not name an existing handler source")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
    message(FATAL_ERROR "extract_nvrtc_kernel: OUTPUT is required")
endif()

file(READ "${INPUT}" _handler)
set(_open "static const char* kKernelSrc = R\"__lrx__(")
set(_close ")__lrx__\";")
string(FIND "${_handler}" "${_open}" _open_at)
if(_open_at LESS 0)
    message(FATAL_ERROR
        "extract_nvrtc_kernel: ${INPUT} has no exact kKernelSrc raw-string opener")
endif()
string(LENGTH "${_open}" _open_len)
math(EXPR _body_at "${_open_at} + ${_open_len}")
string(SUBSTRING "${_handler}" ${_body_at} -1 _tail)
string(FIND "${_tail}" "${_close}" _close_at)
if(_close_at LESS 0)
    message(FATAL_ERROR
        "extract_nvrtc_kernel: ${INPUT} has no exact kKernelSrc raw-string closer")
endif()
string(SUBSTRING "${_tail}" 0 ${_close_at} _kernel)
file(WRITE "${OUTPUT}"
    "// GENERATED from ${INPUT}; do not edit this file.\n${_kernel}\n")
